### ISSUE TITLE
2 songs playing at the same time

### ISSUE THREAD

**Issue by codenift** [LibreTime/libretime#922] opened 2019-11-25 15:38 UTC
**Describe the bug**
This is might be something to look into since it's not a good look when having hundreds of listeners. Songs are playing on top of each other, two tracks playing at the same time. This is something that happen to me a few times already, more than 20 times I'd say. Seems like a Liquidsoap or Icecast issue. At first I thought it would only happen if I start rearranging the tracks that are about to play, not something we would want to happen anyways. This morning I noticed it again, although I haven't rearrange anything or touched anything for 3 days. Something else must be causing it.

**To Reproduce**
At first I thought it would happen when rearranging upcoming tracks, but something else is causing it to go on top of each other automatically.

**Expected behavior**
Not play two tracks at the same time, find a way to detect if playing two tracks and kill the previous one.

**LibreTime version:**
Latest version.

**Installation method:**
 - OS: Ubuntu
 - OS Version: 18.04.3 LTS
 - Method: /install 

**Additional context**
To get it back to normal I simply restart the streaming server, via terminal or LT panel (uncheck enabled and save, then enable again and save)

**Comment by paddatrapper** [comment] 2019-11-25 15:52
Duplicate of #916, tracking the issue there

**Closed by paddatrapper** 2019-11-25 15:52 UTC
Labels: bug
