### ISSUE TITLE
Tested Fix for Ubuntu Trusty Silan bad cue in cue out times (play length)

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#197] opened 2017-05-04 12:34 UTC
Silan Version: 0.3.2-1build1 is BROKEN. It is fixed in later versions but not for Trusty.
This fix affects Ubuntu Trusty Silan issues in Ubuntu 14.04 LTS Trusty. I guess it is similar for Debian Jessie.

**Based on Daniel James' posts in Airtime Forum.** [https://forum.sourcefabric.org/discussion/17273/bugfix-silan-packages-for-ubuntu-14-04-lts-039trusty039-now-available](url)

**Edit /etc/apt/sources.list and add:**
`deb http://apt.sourcefabric.org/ trusty main`

**Now do:**
`sudo apt-get update`
`sudo apt-get install sourcefabric-keyring`
`sudo apt-get update`
`sudo apt-get install --reinstall silan=0.3.2~trusty~sfo-1`

**To check that it is properly installed do:**
`sudo dpkg -s silan | grep Version`
It should now report: `Version: 0.3.2~trusty~sfo-1`

**_NOTE: This only changes new imports - it does not fix files that already imported._**

@hairmare  This really needs including in any Ubuntu Trusty Libretime install packages.

**Comment by hairmare** [comment] 2017-05-04 14:19
This issue is a duplicate of #177 but it doesn't describe the problem at hand in a [meaningful way](https://rfc.zeromq.org/spec:42/C4/#24-development-process). IMO the solution proposed here has some blocking problems.

I think it is very important that we replace the legacy upstream packages with something not dependent on legacy upstream (ie. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855319). More info on this is also in the old [taiga#18](https://tree.taiga.io/project/robbt-libreairwaves-airtime-fork/issue/18). I just started working on getting local builds from the NMU (info in https://github.com/LibreTime/libretime/issues/177#issuecomment-299195796).

Adding install instructions to LibreTime would lead to users being very much at the mercy of legacy upstream. I feel it is negligent to recommend installing LibreTime in this fashion considering the AGPL issues some users have experienced with legacy upstream.

**Comment by Robby262** [comment] 2017-05-04 15:14
We do not understand your attitude at all. This does provide an instant tested workaround for users on Trusty - for a problem to which you do not currently have a solution. As it is open source, License: GPL-2+, and works, it seems that you could adopt/copy/include the package into the Libretime installation pack as we suggested above.

**Closed** 2017-05-05 14:52 UTC

**Comment by smilingpeanut** [comment] 2018-01-10 22:45
@ghost How would one apply this in Xenial? When attempting to install, I get this message:

`The following packages have unmet dependencies:
 silan : 
Depends: libavcodec54 (>= 6:9.1-1) but it is not installable or
libavcodec-extra-54 (>= 6:9.16) but it is not installable
Depends: libavformat54 (>= 6:9.1-1) but it is not installable
Depends: libavutil52 (>= 6:9.1-1) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by hairmare** [comment] 2018-01-11 17:38
Hi @smilingpeanut 

@ghost is the name GitHub assigns deleted users. 

Complete instructions on replacing OS bundled versions of silan are available in [the releasenotes](https://github.com/LibreTime/libretime/releases#issues-silan-3.0.0-alpha.3).

Please create a new issue and post the exact steps you took that lead to the failure if the steps from the release notes don't work.
For general discussion/linux help you may also want to ask on our [discource](https://discourse.libretime.org).

Cheers,
Lucas

**Comment by smilingpeanut** [comment] 2018-01-11 17:41
@hairmare Oh, haha, I didn't know that about @ghost. I'll take a look at the release notes. Thank you!

**Comment by hairmare** [comment] 2018-10-06 09:58
Duplicate of #177
