### ISSUE TITLE
Libretime shows new version available but latest 3.0.0-alpha.2 release is installed

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#246] opened 2017-07-17 08:42 UTC
Libretime informs about a new version 3.0.0-alpha.2 available, after updating to that version it keeps showing the same message.

![captura de pantalla 2017-07-17 a las 10 41 08](https://user-images.githubusercontent.com/1733884/28260702-93a68a2e-6adc-11e7-917b-4c0aa5ddac66.png)
![captura de pantalla 2017-07-17 a las 10 41 21](https://user-images.githubusercontent.com/1733884/28260701-939fce5a-6adc-11e7-8b86-ab6376bb7d57.png)

**Comment by hairmare** [comment] 2017-07-17 17:55
This is a duplicate of #198. I didn't get around to fixing it for `3.0.0-alpha.2` but there are now enough releases that it makes sense to look into again. I'm hoping I'll get it fixed in `3.0.0-alpha.3`.

**Closed** 2017-10-19 16:49 UTC
