### ISSUE TITLE
Xubuntu 18.04 and Libretime Master without Gain Replay and Cue in 0

### ISSUE THREAD

**Issue by klaus13** [LibreTime/libretime#1089] opened 2020-08-28 22:47 UTC
**Describe the bug**
I made new setup of Xubuntu 18.04 without updates to be sure to get correct Libretime-Master installation. I got no problem with installation of Libretime-Master. I made 2 other setups before and the issue was the same. There is no Replay Gain value and all music files cue in is 0.0.

**To Reproduce**
1. Tracks / Pistes and than to Columns / Colonnes
2. Click on 'Replay Gain and Cue IN etc..' and place them to see them together
4. See error: There is no value in Replay Gain and and cue IN / Point d'entrée

**Expected behavior**
In older libretime-master installation with Xubuntu 16.04 it works fine, but have no Artwork and Tracktype.

**LibreTime version:**
Latest Libretime-Master

**Installation method:**
 - OS: Xubuntu 
 - OS Version [18.04)] no updates !
 - Method: [cd libretime-master, sudo`./install -fiap`
![NoReplayGain_0 0PointDEntree_Capture d’écran_2020-08-28_23-44-18](https://user-images.githubusercontent.com/20522347/91618138-e3cee580-e989-11ea-878e-4dd8bca7beae.png)
]
 - Details: [Install git and downloaded Libretime Master from https://github.com/LibreTime/libretime, download Zip file and extracted it to home/tec/ ]

**Screenshots**

**Client (please complete the following information if applicable):**
 - OS: [Xubuntu 18.04.05]
 - Browser [Firefox]
 - Version [80.0(64bits)]

**Additional context**

**Comment by klaus13** [comment] 2020-08-29 15:03
Hi,
I got some more information with crash report of Xubuntu 18.04
No RepayGain value is maybe related to Silan

Executable Path: 
/usr/bin/silan
Package: 
	silan 0.3.3-1
Problem Type: 
	Crach
Title! 
	silan assert failure:***stack smashing detected***:<unknown>
ApportVersion:
	2.20.9-0ubuntu7
Architecture
	amd64
AssertionMessage:
	***stack smashing detected***!unknown>terminated
CoreDump
CrashCounter:
	1
Date:
	Sat Aug29 15:58;56 2020
InstallationMedia:
	Xubuntu 18.04 LTS "Bionic Beaver" - Release amd64 (20180426)
JournalErrors:
PackageArchitecrure
	amd64

ProcCmcline:
silan -b -F 0.99 -fJSON -t1.0 /srv/airtime/stor/organize/Abandoned

ProcCpuinfoMinimal:
ProcEnviron:
	Lang=fr_FR.UTF-8
	Path=(costom, no user)
ProcMaps:
ProcStatus:
ProcVersionSignature:
	Ubuntu 4.15.0-112.113-generic 4.15.18
Registers:
Signals:
	6
SourcePackage:
	silan
StacktraceTop:
Tags
	bionic
TreadStacktrace
Uname:
	Linux 4.15.9-112-generic x86_64
UpgradeStatus:
	No upgrade log present (probably fresh install)
userGroups:

**Comment by klaus13** [comment] 2020-08-29 15:04
Hi,
I got some more information with crash report of Xubuntu 18.04
No RepayGain value is maybe related to Silan

Executable Path: 
/usr/bin/silan
Package: 
	silan 0.3.3-1
Problem Type: 
	Crach
Title! 
	silan assert failure:***stack smashing detected***:<unknown>
ApportVersion:
	2.20.9-0ubuntu7
Architecture
	amd64
AssertionMessage:
	***stack smashing detected***!unknown>terminated
CoreDump
CrashCounter:
	1
Date:
	Sat Aug29 15:58;56 2020
InstallationMedia:
	Xubuntu 18.04 LTS "Bionic Beaver" - Release amd64 (20180426)
JournalErrors:
PackageArchitecrure
	amd64

ProcCmcline:
silan -b -F 0.99 -fJSON -t1.0 /srv/airtime/stor/organize/Abandoned

ProcCpuinfoMinimal:
ProcEnviron:
	Lang=fr_FR.UTF-8
	Path=(costom, no user)
ProcMaps:
ProcStatus:
ProcVersionSignature:
	Ubuntu 4.15.0-112.113-generic 4.15.18
Registers:
Signals:
	6
SourcePackage:
	silan
StacktraceTop:
Tags
	bionic
TreadStacktrace
Uname:
	Linux 4.15.9-112-generic x86_64
UpgradeStatus:
	No upgrade log present (probably fresh install)
userGroups:

**Comment by klaus13** [comment] 2020-09-08 22:11
Finally I go back to Xubuntu 16.04 and most of issues are resolved.  One issue stays. The Replay Gain value is not indicated. Replay Gain tag is present in imported mp3 file.  I imported files with Replay Gain value tag ID3v2, but in track column this value stays empty. If I verify by editing this track, I see no column in edit options. So I think something was forgotten. I don't know anything in coding of Libretime. It would be wonderful if somebody can take a look. Thanks

**Comment by LordFader** [comment] 2020-09-14 20:32
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-117-generic x86_64) on a VPS fresh install today same issue don't show Replay Gain

**Comment by rjhelms** [comment] 2020-11-04 19:42
I am experiencing this as well, on a fresh install with Ubuntu 18.04.

Seems that Silan and ReplayGain issues are separate:

- the version of Silan installed by `apt` in Ubuntu 18.04 is broken. Removing it and installing version 0.4.0 manually seems to resolve the issue, per instructions [here](https://discourse.libretime.org/t/how-to-check-if-silan-is-working/256/13).
- problem with ReplayGain seems to be caused by issue #1041. The replaygain_analyzer process depends on Python 3.7, but Ubuntu 18.04 uses Python 3.6. It seems like ReplayGain is running properly, and recording the value in the file, but that information is not making it back to LibreTime.

**Comment by paddatrapper** [comment] 2020-11-05 11:49
I'm going to close this as a duplicate of #1041 then. The fix there should be straightforward (just add a condition to fix on Python >=3.6). I haven't had a chance to look into it yet though

**Closed by paddatrapper** 2020-11-05 11:49 UTC
Labels: bug
