### ISSUE TITLE
LibreTime Stable Release - 3.0-Alpha-8 has issues with Python!

### ISSUE THREAD

**Issue by samkitk** [LibreTime/libretime#1159] opened 2021-01-06 18:15 UTC
**Describe the bug**
Tried to install the e232469 release, but it has errors in dependencies

Errors - 
On a fresh server need to pre-install Python , PHP and pip

The setup is suitable for Python 2.7 but is no longer supported now. So, gives an error.

So, had to manually change the syntax of all places where `print "Hello"` was written to `print("Hello")`
But still, no luck. It has some error in syntax which I don't know how to solve - stuck here.

## Console Output
```
  File "build/bdist.linux-x86_64/egg/liquidsoap/liquidsoap_prepare_terminate.py", line 16
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/liquidsoap/liquidsoap_auth.py to liquidsoap_auth.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/liquidsoap/liquidsoap_auth.py", line 19
    print response['msg']
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(response['msg'])?

byte-compiling build/bdist.linux-x86_64/egg/liquidsoap/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidsoap/generate_liquidsoap_cfg.py to generate_liquidsoap_cfg.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/liquidsoap/generate_liquidsoap_cfg.py", line 51
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/liquidsoap/__main__.py to __main__.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/liquidsoap/__main__.py", line 13
    print "Airtime Liquidsoap"
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Airtime Liquidsoap")?

byte-compiling build/bdist.linux-x86_64/egg/pypo/pure.py to pure.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/listenerstat.py to listenerstat.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/listenerstat.py", line 149
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/pypoliquidsoap.py to pypoliquidsoap.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/eventtypes.py to eventtypes.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/pypomessagehandler.py to pypomessagehandler.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/pypomessagehandler.py", line 40
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/pypofile.py to pypofile.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/pypofile.py", line 47
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/pypopush.py to pypopush.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/pypopush.py", line 70
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/media/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/media/update/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/pypofetch.py to pypofetch.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/pypofetch.py", line 68
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/testpypoliqqueue.py to testpypoliqqueue.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/testpypoliqqueue.py", line 48
    print "Time now: %s" % datetime.utcnow()
                       ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/recorder.py to recorder.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/recorder.py", line 38
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/timeout.py to timeout.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/pypoliqqueue.py to pypoliqqueue.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/pypoliqqueue.py", line 41
    except Empty, e:
                ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pypo/__main__.py to __main__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pypo/telnetliquidsoap.py to telnetliquidsoap.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/pypo/telnetliquidsoap.py", line 142
    except Exception, e:
                    ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/airtime-playout -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/pyponotify -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/airtime-liquidsoap -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/airtime-playout to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/pyponotify to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/airtime-liquidsoap to 755
copying airtime_playout.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airtime_playout.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airtime_playout.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airtime_playout.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airtime_playout.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airtime_playout.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/airtime_playout-1.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing airtime_playout-1.0-py3.6.egg
removing '/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg
Extracting airtime_playout-1.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/__main__.py", line 13
    print "Airtime Liquidsoap"
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Airtime Liquidsoap")?

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/generate_liquidsoap_cfg.py", line 51
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/liquidsoap_auth.py", line 19
    print response['msg']
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(response['msg'])?

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/liquidsoap_prepare_terminate.py", line 16
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/listenerstat.py", line 149
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 68
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofile.py", line 47
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypoliqqueue.py", line 41
    except Empty, e:
                ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypomessagehandler.py", line 40
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypopush.py", line 70
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/recorder.py", line 38
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/telnetliquidsoap.py", line 142
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/testpypoliqqueue.py", line 48
    print "Time now: %s" % datetime.utcnow()
                       ^
SyntaxError: invalid syntax

airtime-playout 1.0 is already the active version in easy-install.pth
Installing airtime-playout script to /usr/bin
Installing pyponotify script to /usr/bin
Installing airtime-liquidsoap script to /usr/bin

Installed /usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg
Processing dependencies for airtime-playout==1.0
Searching for wsgiref
Reading https://pypi.org/simple/wsgiref/
Downloading https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip#sha256=c7e610c800957046c04c8014aab8cce8f0b9f0495c8cd349e57c1f7cabf40e79
Best match: wsgiref 0.1.2
Processing wsgiref-0.1.2.zip
Writing /tmp/easy_install-_j5_qv12/wsgiref-0.1.2/setup.cfg
Running wsgiref-0.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_j5_qv12/wsgiref-0.1.2/egg-dist-tmp-g6dm7faz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-_j5_qv12/wsgiref-0.1.2/setup.py", line 5, in <module>
    
  File "/tmp/easy_install-_j5_qv12/wsgiref-0.1.2/ez_setup/__init__.py", line 170
    print "Setuptools version",version,"or greater has been installed."
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/libretime-3.0.0-alpha.8/python_apps/pypo/setup.py", line 66, in <module>
    data_files=data_files)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 766, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 880, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 1150, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 1134, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-_j5_qv12/wsgiref-0.1.2/setup.py", line 5, in <module>
    
  File "/tmp/easy_install-_j5_qv12/wsgiref-0.1.2/ez_setup/__init__.py", line 170
    print "Setuptools version",version,"or greater has been installed."
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

```

**Expected behavior**

**Installation method:**
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt install software-properties-common`
`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10`

`wget https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.8/libretime-3.0.0-alpha.8.tar.gz`

`tar -xvf libretime-3.0.0-alpha.8.tar.gz`

`cd libretime-3.0.0-alpha.8.tar.gz`

`sudo ./install -fiap`

**Additional context**
Though there have been new updates and commits after it but it has been branded as the most stable release - so just pointing it out.

Additional Question:
Is there any other stable release/commit after this that I should try or wait for Alpha-9?

**Comment by paddatrapper** [comment] 2021-01-06 18:27
Fixed in master. Duplicate of #965

**Comment by paddatrapper** [comment] 2021-01-06 18:27
I'd recommend waiting for alpha.9

**Comment by paddatrapper** [comment] 2021-01-06 18:28
Or run master and report testing with config and logs

**Closed by paddatrapper** 2021-01-06 18:27 UTC
Labels: bug
