### ISSUE TITLE
Would not login on a new tarball install (port mismatch)

### ISSUE THREAD

**Issue by JohnnyC1951** [libretime/libretime#3004] opened 2024-04-28 19:05 UTC
### Describe the bug

Install proceeds OK to first login page. Get an 'Oops' when entering admin admin
Journal shows that many API calls that cannot complete as it wants to connect on port 80 but NGINX is configured to port 8080

### To reproduce

1 Download current LT V4 tarball and ran it as instructed in the web page documents..

### Expected behavior

To be able to log in after installation.

### Relevant log output or error messages

```shell
Apr 28 20:50:58 ukradio.online libretime-playout[406]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='ukradio.online', port=80): Max retries exceeded with url: /api/update-metadata-on-tunein?format=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff540bdc4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Apr 28 20:50:58 ukradio.online libretime-playout[406]: 2024-04-28 20:50:58,483 | WARNING  | urllib3.connectionpool:urlopen:874 - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff543f3c130>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/stream/preferences
```

### LibreTime version

Version: Stable 4.x LibreTime 4.0.0  2024-01-07.

### Installation method and OS / Environment

Operating system: Ubuntu 20.04. PHP 7.4
Method: VPS installed using Contabo's web installer.

### Installation details

All done via Remmina SSH client and Firefox.

WORKAROUND!!!!!! I changed NGINX's port to 80 from 8080 and it worked.
I had the same issue using the Docker Install so I then tried the tarball.

### Client Environment

Operating system: Ubuntu 22.04 Jammy
Browser: Firefox 123.0b3 (64-bit)

### Screenshots

We have all seen an oops page.

**Comment by ldog0121** [comment] 2024-04-28 19:08
Had same problem with docker install and manual install with latest version from Git

**Comment by jooola** [comment] 2024-05-05 21:44
This seems to be a duplicate of https://github.com/libretime/libretime/issues/2914

Closing as duplicate.

**Closed by jooola** 2024-05-05 21:44 UTC
Labels: is: bug
