### ISSUE TITLE
[Question] File ownership problems still lingering?

### ISSUE THREAD

**Issue by ahpl** [LibreTime/libretime#314] opened 2017-09-30 20:21 UTC
Hello from a new guy here!

I'm coming from an installation of Airtime 2.5.1 that works well enough for us to handle >100 hours per week on air. We're eagerly anticipating progress with LibreTime, though, due to a number of strange things.

One of them pertains to file ownership. Several uploads from admin-level users get another admin as owner. Uploads from Program Managers or DJ's also get one of the admins as owner and so the supposed owners are unable to edit their material.

Did you change any code relating to file uploads and ownership assignment? If not, did you experience the same issue in LibreTime?

**Comment by hairmare** [comment] 2017-09-30 21:01
Hi @ahpl 

Welcome to the community!

I'm afraid the whole upload process has some rather large changes compared to 2.5.1. We switched to using the new airtime_analyzer code instead of media-monitor for the whole upload process. With this also came the switch to a new RESTful API for uploading and accessing media resources. Most of this was from the latest SaaS branch from legacy upstream we could manage to find.

Under the hood the new analyzer code and the api are based on the same underpinnings as before so that doesn't reasonably explain your issues.

The code that does the actual storing of the data looks pretty much unchanged:

https://github.com/LibreTime/libretime/blob/6085a8fd279ee0d1d0bc985570bc74a52a522fd2/airtime_mvc/application/models/airtime/CcFiles.php#L149-L155

I do feel that the the weird default admin case could be tripping up somehow. I think it's a fallback to ensure that uploads from places like the podcast downloader etc. always get an owner.

https://github.com/LibreTime/libretime/blob/6085a8fd279ee0d1d0bc985570bc74a52a522fd2/airtime_mvc/application/models/airtime/CcFiles.php#L430-L444

The user service class looks quite basic for it to be the real culprit so I expect a race condition somewhere.

https://github.com/LibreTime/libretime/blob/276a69aa1bef527260efc170d7caab7d04b4ca13/airtime_mvc/application/services/UserService.php#L19-L26

Is there anything in the log file at `/var/log/airtime/zendphp,log` near the uploading of an affected file?

**Comment by Robbt** [comment] 2019-04-23 01:37
So I am going to mark this as fixed with #766 since we never confirmed there was an issue and we added the ability for admins to change the owner of a file.

**Closed by Robbt** 2019-04-23 01:37 UTC
Labels: airtime-upgrade-path, bug, database, question
