### ISSUE TITLE
Questions and oddness concerning Podcast ingest

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#422] opened 2018-01-24 18:06 UTC
I am scratching my head. Sometimes, and only sometimes, although a new pod has been downloaded, it doesn’t get auto inserted via smart block, indeed NOTHING got inserted, not even the jingle. The correct play-list is in the show auto and the check box is ticked. In this particular case, the feed is from Pacifica and is Democracy Now! although I have seen it with others. How can I debug this? I guess that Celery didn't pick up the job.

I have put the auto-generated play-list, having included a jingle at the top and another smart block below it (of filler music):  How would this be expected to work in a repeating content show with the smart block? (or not).

**Comment by Robbt** [comment] 2018-01-25 18:33
Ok, so just to confirm, the tracks are downloaded and added to your Library ?

Are the track albums being renamed to meet the Podcast name and is your smartblock setup to match this ?

If you manually drag a smartblock does it work or provide nothing ?

**Comment by JohnnyC1951** [comment] 2018-01-25 18:46
1/ the tracks are downloaded and added to your Library ? Yes
2/ Are the track albums being renamed to meet the Podcast name and is your smartblock setup to match this ? Yes
3/ If you manually drag a smartblock does it work or provide nothing ? That works fine.

The issue seems to be about the (sometimes) non-autoloading of content, an hour before showtime.#

**Comment by Robbt** [comment] 2018-01-25 18:49
Ok, and dragging a playlist w/ the Smartblock works as well ?

Is there possibly dead air or two hours of programming before the shows where this happens ? It could be the bug where the API needs to be triggered to cause the Autoplaylist to be built.

**Comment by JohnnyC1951** [comment] 2018-01-25 18:50
I am running 24/7 with no planned dead air at all

**Comment by JohnnyC1951** [comment] 2018-01-25 18:51
What event actually triggers the autoload? I am running some tracks of >2hours. Could that be the issue?

**Comment by Robbt** [comment] 2018-01-26 02:01
It is most likely the longer tracks. It is triggered by pypo playout which pushes tracks from schedule. I also think that reading the schedule via loading the website will load the API as well. The issue #129 has more details. This is most likely a duplicate of that bug, but being triggered by the case of longer files.

**Comment by Robbt** [comment] 2018-01-27 20:25
I'm going to assume that this is caused by #129 and add the details under that bug and close this out so we can try to keep the issue queue cleaner. Can you look at your logs and see if the times when autoplaylists weren't scheduled coincided with tracks longer than 1 hour being played ? If there is no connection we can re-open it and analyze the issue further.

**Closed by Robbt** 2018-01-27 20:25 UTC

**Comment by JohnnyC1951** [comment] 2018-01-28 02:09
It would appear that, indeed, each instance of the problem immediately followed a show track.
Loading the website? You mean the admin one? Would that fire on a simple page load of a not logged in user? If so I can just pull it on a cron.
