### ISSUE TITLE
bug when using mutiple criteria in smart blocks

### ISSUE THREAD

**Issue by Liberator1967** [LibreTime/libretime#458] opened 2018-03-06 07:53 UTC
When I define multiple criteria in a smart block the operand 'and' automatically appears.
That's fine, but when I edit the smart blocks, the operand 'and' changes into 'or'.
I tested the outcome with the preview-option and the subset of records is really changed.
So, it's not only a cosmetic issue but the sql-command is really different from the one I created.
This results in many more hits due to the 'or'-operand instead of the more restrictive 'and'-operand.

**Comment by Robbt** [comment] 2018-03-06 12:58
Ok, let me check this out, it is certainly possible that the form is being read incorrectly from the database as the functions here are pretty convoluted.

**Comment by Liberator1967** [comment] 2018-03-08 14:57
I found the solution for this problem (it's not a problem).
There is a difference between '+new criteria' and '+new modifier'.
If you click on '+new criteria' it will use 'AND' as an operand.
If you click on '+new modifier' it will use 'OR' as an operand.
A little bit misleading (also due to the same color of the buttons) but also very stupid of me.
Thank you Robbt for your help and sorry for wasting your time.
Hopefully others are helped with this topic.

By the way, I'm still wondering about my second issue : #459 that's really driven me crazy...

**Comment by JohnnyC1951** [comment] 2018-03-31 13:59
I think there might actually be an issue here. Consider this screenshot. 'Fringe News' was not expected to be selected. Maybe I am being stupid, but can anyone explain if/why this screen shot demonstrates the expected behaviour? It seems to ignore the middle criterion.
![smartblockfailure](https://user-images.githubusercontent.com/33095908/38163876-0492c23a-34f3-11e8-9ac7-25f4d47c1e73.png)

**Comment by Robbt** [comment] 2018-04-03 00:55
Indeed, this does appear to contradict itself. I haven't looked at the way the queries are built recently but if my memory serves me correctly, the way it's parsed, stored and unraveled is kind of convoluted and could definitely be refactored to be more legible. Just trying to add the modifications to the form via jquery to accomodate the relative date blocks was quite frustrating. To analyze this further will require stepping through the code I suspect and/or logging the SQL query before it is sent. If I get a chance I'll try to revisit this, but I suspect I won't be working a lot on Libretime until at least May.

**Comment by JohnnyC1951** [comment] 2018-04-03 01:35
My own code that updates program Name & Description from Imported Tracks (and thus from RSS) actually gets this right. If anyone wants the relevant code for that, just ask.

**Comment by JohnnyC1951** [comment] 2018-04-03 01:58
I think the issue maybe in line 15559 in /models/Block.php It seems to overwrite previous selection criteria in the loop, with that last one. Personally I think it is witchcraft and too clever for its own good.

**Comment by frecuencialibre** [comment] 2019-01-16 20:21
I can also confirm this is a bug. Really unfortunate since I was counting on being able to do this at my station. should have tested before improving our library metadata :(

My test case is trying to return tracks that do contain one value in a metadata field, but do not contain another: 

![screenshot from 2019-01-16 14-13-48](https://user-images.githubusercontent.com/36803137/51276109-6f545800-1999-11e9-8ffc-93dd06faa8d9.png)

note that every single track in our library is being returned by the preview.

**Comment by Robbt** [comment] 2019-01-17 02:40
Well now that we have a good way of defining and recreating it we should be able to fix it.

**Comment by frecuencialibre** [comment] 2019-01-19 17:59
sorry to nag, but given recent issue triage i'm going to cast my vote for prioritizing this one. i've now had to explain a few times to radio collective members that it isn't working :(. i made the mistake of assuming we would be able to apply genres broadly and then be able to filter things _out_. also i put a bunch of stuff in genre metadata since comments aren't searchable as documented in #526 . thanks!

**Comment by Robbt** [comment] 2019-01-19 20:04
Ok I think I've pin-pointed the problem. The issue is with "does not contain" - multiple criteria appear to work otherwise from what I can tell. I'll dive into the code and hopefully it will be an easy fix.

**Comment by frecuencialibre** [comment] 2019-01-19 20:10
you rock

**Comment by Robbt** [comment] 2019-01-19 20:55
Ok, I think I have pinpointed the issue - when there are multiple criteria with the same COLUMN the code merges them into an OR statement. Here is what happens when you have a COLUMN matching on GENRE with 2 does not contain statements.

```SQL (may not be complete): SELECT  FROM cc_files left join cc_subjs subj ON (cc_files.owner_id=subj.id) WHERE (((genre NOT ILIKE :p1 OR genre IS NULL ) OR genre NOT ILIKE :p2) OR genre IS NULL ) AND track_title ILIKE :p3 AND file_exists=:p4 AND hidden=:p5 ORDER BY random() ASC
```

The important part is ` (((genre NOT ILIKE :p1 OR genre IS NULL ) OR genre NOT ILIKE :p2) OR genre IS NULL )`
As per the the way the smartblock UI suggests these shouldn't be merged with an OR but instead separated with an AND. Now I have to figure out the part of the code that is merging these.

**Comment by Robbt** [comment] 2019-01-20 00:34
So based upon some preliminary coding overloading extra is not a good idea because it starts to break the jquery for datetime elements and probably confuses things further. So I'm going to create a new column for criteria called group which will keep track of the group that a criteria is added by.

**Closed** 2019-02-09 16:22 UTC
Labels: bug, release-blocker, smart blocks
