### ISSUE TITLE
problem: first setup screen displays not correctly

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#116] opened 2017-03-23 13:08 UTC
On MacOS Safari and Chrome
almost on last step it shows like this.

On Firefox everything shows correctly

![screen shot 2017-03-23 at 15 47 58](https://cloud.githubusercontent.com/assets/25418594/24249032/d11a463e-0fe2-11e7-8fa4-760a0700fbc5.png)

**Comment by hairmare** [comment] 2017-03-23 13:09
Strange I always used Chrome and never Firefox.

**Comment by korotkov13** [comment] 2017-03-23 13:10
I have MBA 13''

**Comment by Robbt** [comment] 2017-03-23 22:32
What is the screen resolution ? I will try to test it on a mac to see if I can replicate.

**Comment by korotkov13** [comment] 2017-03-23 22:43
native 1440x900

**Comment by paddatrapper** [comment] 2019-03-30 22:12
I can reproduce this in Firefox on a Thinkpad T460 running Debian. Screen resolution is 1920x1080 HiDPI with screen scaling at 1.3x

**Comment by Robbt** [comment] 2019-03-31 17:36
Cool this is one a  long standing bugs even if it is somewhat trivial @paddatrapper have you tried to play around with the CSS to see what might be causing it and how we can fix it ?

**Comment by paddatrapper** [comment] 2019-04-01 09:13
Hmm... Mine seems to be a slightly different bug - the scrolling between RabbitMQ settings and General settings goes too far. This results in part of the General Settings tab to be hidden and some of the Media settings tab to be displayed.

![Screenshot_2019-04-01 Screenshot](https://user-images.githubusercontent.com/7299909/55316662-2d529280-546f-11e9-9c64-4503ae5a3185.png)

**Comment by Robbt** [comment] 2019-04-01 12:06
Ok, weird did opening up developer tools in firefox give you any insight as to what might be causing the weirdness with the CSS ?

I suspect that this web installer UI being a one-off just has some odd edge case for the CSS code that was written. Hopefully they are related and it would be a simple fix to someone such as @frecuencialibre who pretty adept at CSS type of stuff.

**Comment by paddatrapper** [comment] 2019-04-01 13:23
It seems to be something about how it is calculating the width of the General Settings tab, but I haven't had a chance to investigate it fully yet. It seems moving the General Settings tab 100% to the left overshoots the intended stopping point and causes the Media Settings tab to come into view too early.

**Comment by Robbt** [comment] 2020-05-12 19:18
So I suspect that this is an issue with bootstrap 3 and the way we are loading all of the pages at once and using the function formSlide here.
https://github.com/LibreTime/libretime/blob/8498029cd983536a6e3016780d0b1693985a8e01/airtime_mvc/public/js/setup/setup-config.js#L76-L90

I'm not sure if this is something that we can easily fix without refactoring the whole installer or updating to a new version of bootstrap. I'm going to mark this as closed won't fix unless someone else wants to jump in and work on it.

**Closed by Robbt** 2020-05-12 19:18 UTC
Labels: bug, installer, pinned
