### ISSUE TITLE
Is there a way to direct import ?

### ISSUE THREAD

**Issue by Aeris1One** [LibreTime/libretime#1076] opened 2020-07-25 16:14 UTC
Hi,
Is there a way to import the music I already have on the server hosting LibreTime instead of having to download it then reuploading it on the panel ?

**Comment by paddatrapper** [comment] 2020-07-25 17:05
PR #908 addresses this. Until that is merged, no

**Comment by paddatrapper** [comment] 2020-10-12 13:03
Closing as duplicate of #70

**Closed by paddatrapper** 2020-10-12 13:03 UTC
