### ISSUE TITLE
Upload does not work via S3FS

### ISSUE THREAD

**Issue by whiteblue3** [LibreTime/libretime#736] opened 2019-02-13 07:43 UTC
I was setting my libretime on AWS.
applied TLSv1.2, S3FS environment

I was tested on local storage setup. it was upload ok.
and I was migrate to AWS S3 via S3FS.
mount was success. airtime_analyzer was works fine.
run_analysis in analyzer_pipeline.py is works fine.
metadata was successfully extracted.

and send_http_request in status_reporter.py does not work.
this functions request to /rest/media/:id 
but this url is not working.

so, does not insert to database metadata information.
pending retry is looping forever.

this is weird.
where can I check source code?

**LibreTime version:**
#670

**Installation method:**
 - OS: Ubuntu
 - OS Version 18.04 LTS
 - Method: sudo -H ./install --web-root=/srv/airtime --web-user=www-data

**Comment by Robbt** [comment] 2019-02-13 20:53
I suspect the issue is not with s3fs but instead with the rabbitmq hostfile. See #681 & #515 because I think that it is basically failing to chime in after the file is copied to the server and ingested via airtime-analyzer ?

What are the errors in zend-php.log or airtime_analyzer.log ?

**Comment by Robbt** [comment] 2019-04-22 20:08
I'm going to close this, feel free to open if you have more information to help us troubleshoot the issue.

**Closed by Robbt** 2019-04-22 20:08 UTC
Labels: bug
