### ISSUE TITLE
Celery can't sync to an MPEG frame downloading podcast

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#582] opened 2018-11-01 13:09 UTC
I get the following error downloading a podcast

```
2018-11-01T14:05:02+01:00 WARN (4): subdomain.example.com Celery task DbId: 783
DbTaskId: php_5bdaf9f469ee32.81256134
DbTrackReference: 783
DbName: podcast-download
DbDispatchTime: '2018-11-01 13:04:52'
DbStatus: SUCCESS
ThirdPartyTrackReferences:
  DbId: 783
  DbService: podcast
  DbForeignId: '821'
  DbFileId: null
  DbUploadTime: '2018-11-01 13:05:02'
  DbStatus: null
  CeleryTaskss:
    CeleryTasks_0: '*RECURSION*'
 episode 821 unsuccessful with message can't sync to an MPEG frame
2018-11-01T14:05:55+01:00 INFO (6): subdomain.example.com Checking autoplaylist poll
```

**Comment by frecuencialibre** [comment] 2018-11-01 15:05
duplicate of https://github.com/LibreTime/libretime/issues/519 ?

**Closed** 2018-11-01 18:47 UTC
