### ISSUE TITLE
Where can I upload files directly

### ISSUE THREAD

**Issue by marzar325** [LibreTime/libretime#1182] opened 2021-02-24 23:01 UTC
Hello, I have alot of media I need to upload, where can I go to upload the media directly?

**Comment by Robbt** [comment] 2021-02-25 00:04
There is no easy way to do this currently. It is something we have been working on and various people have implemented solutions too. I'm going to close this because it is a duplicate of #70. At our last developer meeting we talked about trying to solve this problem and integrate the solution into the code but it hasn't happened yet. Hopefully soon.

**Closed by Robbt** 2021-02-25 00:04 UTC
