### ISSUE TITLE
Import files in a batch

### ISSUE THREAD

**Issue by freemanpolys** [LibreTime/libretime#502] opened 2018-08-07 09:54 UTC
How to make airtime-import work ?
I have the output below.
```
Traceback (most recent call last):
  File "/usr/bin/airtime-import", line 13, in <module>
    from mm2.media.monitor.pure import is_file_supported
ImportError: No module named mm2.media.monitor.pure
```

**Comment by matias-tecnosoul** [comment] 2018-08-31 14:39
so just to clear up, the only way to import files is through the web interface? or is there a way to import files already on the server??
thanks for any hints

**Comment by Robbt** [comment] 2018-08-31 23:15
This is true, there is no currently functional import module. Some work has been done on finishing the work done in #111 but as far as I know nobody has put the work into actually completing this task and getting it working with the latest branch of LibreTime.

**Comment by Robbt** [comment] 2018-09-04 17:49
As a quick workaround you could write a batch script that uses the script in python_apps/airtime_analyzer/tools/ftp-upload-hook.sh - this might work, although I wasn't able to confirm this script working from my VPS because of DNS resolution and port forwarding.

I'm actively trying to come up with a solution that will enable the automatic importing of local filesystem files.

**Comment by matias-tecnosoul** [comment] 2018-09-05 10:47
great, thanks for the hint. We'll check that script and #111  ...

**Comment by Robbt** [comment] 2018-09-05 11:01
Yeah, if you put together a hacky solution or modified script feel free to share it. As I mentioned in #111 I was receiving the 400 errors every time I ran the curl portion of that script and thus needed to take it out of the until curl do loop so that it didn't import the same file repeatedly. If you can figure out why its returning a 400 error then it might be usable directly as a part of another program but my impulse is to build it as a stand-alone python service at this point that just monitors a directory, sends the files that show up in there to the web server and then deletes them.

**Comment by Robbt** [comment] 2018-11-28 13:23
So I'm going to close this because #514 should fix it (in terms of updating docs) and will likely be merged soon. If not the issue isn't a specific bug but a problem of docs referring to solutions that no longer exist and that is already covered in #376

**Closed by Robbt** 2018-11-28 13:23 UTC
Labels: documentation, duplicate
