### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by jonikane** [LibreTime/libretime#389] opened 2018-01-01 19:27 UTC
It is possible to add proxy to libretime?

**Comment by hairmare** [comment] 2018-01-01 20:49
If you want to run LibreTime in a network that mandates a forward proxy you should be able to do so by setting up the proper `HTTP_PROXY`, `HTTPS_PROXY` and, `NO_PROXY` environment variables (you might also need to configure the lowercase equivalents of those variables).

Running the LibreTime Web-UI and API behind a reverse proxy should work fine as well. It isn't recommended to put the icecast service behind a proxy for performance reasons.

In any case using forward and reverse proxies with LibreTime is untested at the moment and you will most likely need to be able to tweak some settings on the proxies for everything to work as intended. I'd advise that you get your proxy person on board early so he/she can help you get everything set up as needed. 

I'm gonna close this issue since it's not actionable from a developers point of view. Please let us know if you encounter any issues or need further pointers. To be able to assist you further we will need some more information on your setup: ie. do you need a reverse or forward proxy (from what vendor) and how does your network setup (roughly) look like.

**Closed by hairmare** 2018-01-01 20:49 UTC
