### ISSUE TITLE
PHP version mess on debian buster with packages.sury.org/php

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1256] opened 2021-06-28 17:34 UTC
**Describe the bug**

The installer install php 8 alongside php 7.3 and 7.4 on debian buster with the sury php repository.

I think it's a bad idea to use virtual packages to install php extensions. We could target the versioned one directly.

**To Reproduce**

1. Spin up a debian buster
2. Setup the packages.sury.org/php repository
3. Launch the libretime installation

**Expected behavior**
Handle php version properly.

**LibreTime version:**
master

**Installation method:**

- OS: Debian buster
- Method: `./install -fiap`

**Comment by Robbt** [comment] 2021-06-28 17:38
What is gained by using packages.sury.org/php ?
This would appear to be where the issue is introduced.

I don't disagree with the idea of having the install target the specific versioned php packages though.

**Comment by jooola** [comment] 2021-06-28 17:42
I use the sury repository to be able to install the different php versions I need, and on shared hosting it can be useful.

But I guess I will reinstall libretime without the sury repository somewhere else.

So I have my fix, but the installed should be somewhat more resilient to such situation.

**Comment by Robbt** [comment] 2021-06-28 17:43
Yeah someone would just need to go through and adjust the packages to include the version specific package name in the installer directory and it should be a relatively easy improvement.

**Comment by jooola** [comment] 2021-06-28 17:46
I already tried to tweak the package list, but it seems more complex that you suggest. Anyway, this is not today's task.

**Comment by jooola** [comment] 2021-06-28 17:48
Haha, so this is a bit unrelated, but something is borken anyway:
```
jo@libretime-auk: master …1 /opt/libretime $ sudo ./install -fiap

.____    ._____.               ___________.__                
|    |   |__\_ |_________   ___\__    ___/|__| _____   ____  
|    |   |  || __ \_  __ \_/ __ \|    |   |  |/     \_/ __ \ 
|    |___|  || \_\ \  | \/\  ___/|    |   |  |  Y Y  \  ___/ 
|_______ \__||___  /__|    \___  >____|   |__|__|_|  /\___  >
        \/       \/            \/                  \/     \/

Detecting distribution and release ...
Detected distribution id: debian
Detected distribution release id: 10
Detected distribution description: Debian GNU/Linux 10 (buster)

-----------------------------------------------------
         * Installing External Dependencies *        
-----------------------------------------------------
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 http://deb.debian.org/debian buster-backports InRelease
Reading package lists...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apache2 is already the newest version (2.4.38-3+deb10u4).
coreutils is already the newest version (8.30-3).
curl is already the newest version (7.64.0-4+deb10u2).
git is already the newest version (1:2.20.1-2+deb10u3).
lsb-release is already the newest version (10.2019051400).
lsof is already the newest version (4.91+dfsg-1).
patch is already the newest version (2.7.6-3+deb10u1).
patch set to manually installed.
python3-gi is already the newest version (3.30.4-1).
python3-gi set to manually installed.
python3 is already the newest version (3.7.3-1).
python3 set to manually installed.
systemd-sysv is already the newest version (241-7~deb10u7).
unzip is already the newest version (6.0-23+deb10u2).
zip is already the newest version (3.0-11+b1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
                  Depends: libselinux1-dev but it is not going to be installed
 php7.3-dev : Depends: libpcre2-dev (>= 10.30) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
./install: line 773: php: command not found
```

**Comment by paddatrapper** [comment] 2021-06-28 22:19
This is a duplicate of #1083

**Closed** 2021-10-05 13:52 UTC
Labels: is: bug
