### ISSUE TITLE
Problem: Can not connect to the streaming server

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#101] opened 2017-03-20 08:07 UTC
After making clean install from clone git I can't connect to icecast server. 
![screen shot 2017-03-20 at 11 02 10](https://cloud.githubusercontent.com/assets/25418594/24092039/e7804fa0-0d5c-11e7-8048-6f0874464903.png)
If i choose 

> Custom / 3rd Party Streaming
![screen shot 2017-03-20 at 11 07 47](https://cloud.githubusercontent.com/assets/25418594/24092144/7c263ba6-0d5d-11e7-9821-474a89c56c62.png)

If I install from tarball it working fine.
liquidsoap logs are empty, icecast shows no errors too. Please tell me where/how to search the bug.

**Comment by hairmare** [comment] 2017-03-20 09:51
My first stream looks like this and works like a piece of cake. Did you change any settings?

<img width="483" alt="screen shot 2017-03-20 at 10 49 15" src="https://cloud.githubusercontent.com/assets/116588/24094901/f8bfa4f2-0d5a-11e7-9d4e-c9ed54d8b66f.png">

I'm not sure about default streaming but I have a feeling that works as well.

**Comment by hairmare** [comment] 2017-03-20 10:01
Could this have been introduced with #84? I don't think so but I'm not sure.

**Comment by korotkov13** [comment] 2017-03-20 10:24
i just install the latest erlang  [package](https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_19.3-1~ubuntu~trusty_amd64.deb) 
Because if i don't, I'll catch an error with rabbitmq during libretime install.
Unfortunatly i have only ipv4 on my vps.
Very strange that it working well with tarball and don't with git.

**Comment by Robbt** [comment] 2017-03-20 13:17
What Linux Distro are you running your OS from.
What does the liquidsoap.log file contain in /var/log/airtime/pypo-liquidsoap/ls_script.log contain. Do you notice any errors causing liquidsoap to terminate.
Also what are the contents of /etc/airtime/liquidsoap.cfg ?
If you run ps -aux | grep 'liquidsoap' do you see a process running ?
Have you tried restarting liquidsoap via sudo /etc/init.d/airtime-liquidsoap start

Perhaps provide a pastebin.com link or attach the files as I'm pretty sure the contents by themselves would just be a wall of text :)

**Comment by yarik2720** [comment] 2017-03-20 17:10
I have the same, folder pypo-liquidsoap is empty.
```
$ ps -aux | grep 'liquidsoap'
www-data  4710  1.9  1.0  75104 21796 ?        Ss   20:04   0:00 /usr/bin/python /usr/bin/airtime-liquidsoap
```
icecast2 server running ok
![virtualbox_2017-03-20_20-07-03](https://cloud.githubusercontent.com/assets/1839978/24111852/db328ece-0da8-11e7-8fb3-ad160ec652f4.png)

here is /etc/airtime/liquidsoap.cfg: https://puu.sh/uRLby.conf

**Comment by hairmare** [comment] 2017-03-20 17:53
That linked file looks like a `/etc/airtime/airtime.conf` file. Maybe `/etc/airtime/liquidsoap.cfg` isn't getting properly generated. Does anything change after `sudo /etc/init.d/airtime-liquidsoap restart`? What distro exhibits this?

In the screenshot it looks like icecast is not properly reachable.

**Comment by yarik2720** [comment] 2017-03-20 19:34
Sorry, wrong file. I found that it doesn't exists
```
$ ls
airtime.conf      cloud_storage.conf  rabbitmq-analyzer.ini
airtime.conf.bak  production
```
restarting not helped
trying to connect to already working icecast server also not helped
![virtualbox_2017-03-20_22-32-43](https://cloud.githubusercontent.com/assets/1839978/24118016/606c133a-0dbd-11e7-8b5b-0a866b9a8107.png)

**Comment by hairmare** [comment] 2017-03-20 19:38
Can you connect to the icecast gui directly on port 8000 (in a browser)?

**Comment by yarik2720** [comment] 2017-03-20 19:39
Yes
![virtualbox_2017-03-20_22-39-20](https://cloud.githubusercontent.com/assets/1839978/24118244/20c7089c-0dbe-11e7-8f48-eb06ae5567bd.png)

**Comment by hairmare** [comment] 2017-03-20 19:40
That the file doesn't exist may be part of the cause, it should have been created by airtime-playout. Does `/etc/airtime` belong to the systems apache user (www-data or apache2)?

**Comment by yarik2720** [comment] 2017-03-20 19:40
Yes, owner is www-data

**Comment by hairmare** [comment] 2017-03-20 19:43
Fair enough, are you using Ubuntu or Debian?

**Comment by yarik2720** [comment] 2017-03-20 19:44
Ubuntu 14.04

**Comment by hairmare** [comment] 2017-03-20 19:47
So upstart should be taking care of restarting everything on changes. If the liquidsoap file never gets written python is probably failing to early for liquidsoap to start logging to `/var/log/airtime/pypo-liquidsoap/ls_script.log`.

Can you su into the www-data user and try running `python /usr/bin/airtime-liquidsoap` directly. Maybe it will tell us what is going on when called on the cli.

**Comment by yarik2720** [comment] 2017-03-20 19:54
```
$ sudo su - www-data -s /bin/bash -c 'python /usr/bin/airtime-liquidsoap'
Airtime Liquidsoap
Unable to connect to the Airtime server.
<urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
traceback: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/generate_liquidsoap_cfg.py", line 48, in run
    ss = ac.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 432, in get_stream_setting
    return self.services.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 144, in __call__
    f = urllib2.urlopen(req, timeout=ApiRequest.API_HTTP_REQUEST_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>


```

**Comment by hairmare** [comment] 2017-03-20 20:01
So python is acting up with TLS, why am I not surprised. What is your `base_port` in `/etc/airtime/airtime.conf`?

**Comment by yarik2720** [comment] 2017-03-20 20:03
80

**Comment by hairmare** [comment] 2017-03-20 20:07
It looks like [python_apps/api_clients/api_clients/api_client.py#L190](https://github.com/LibreTime/libretime/blob/81d3c3e2b8ebee25523e43f9952ae78cce8c8004/python_apps/api_clients/api_clients/api_client.py#L190) isn't working properly 🙁 I have to switch my local set up to ubuntu so I can try reproducing it.

**Comment by hairmare** [comment] 2017-03-20 20:17
I believe I found the issue, am re-installing completely to check the fix and will pr shortly.

**Comment by hairmare** [comment] 2017-03-20 20:45
Thanks for testing and helping me figure this one out. I'm not much of a pythonista as you might be able to tell from the fix 😟 Please re-open if the fix doesn't work once it's merged.

**Comment by korotkov13** [comment] 2017-03-20 20:48
Next time I can test it it's Wednesday :( 
I will report what I find.

**Comment by hairmare** [comment] 2017-03-20 20:49
Here's a quick workaround for installed systems:

```
sudo sed -i -e 's/https/http/' /usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py
```

**Comment by squiggleuk** [comment] 2017-03-20 20:58
Quick workaround resolved for me - hope that helps.
Can't rebuild my test server right now either though...

**Closed** 2017-03-21 03:34 UTC
Labels: bug

**Comment by hairmare** [comment] 2017-03-21 08:54
Now that it's been merged you can also re-install just the api_client after bringing your working copy up to date.

```
sudo python python_apps/api_clients/setup.py install
```

**Comment by yarik2720** [comment] 2017-03-21 16:47
Thank you! All works!

**Comment by korotkov13** [comment] 2017-04-02 22:16
I have the same issue now. 
Installed the last master build.
![screen shot 2017-04-03 at 1 12 38](https://cloud.githubusercontent.com/assets/25418594/24591494/166f99d4-180b-11e7-8476-1525d687262d.png)
after i change settings, i got this
![screen shot 2017-04-03 at 1 13 25](https://cloud.githubusercontent.com/assets/25418594/24591496/22c62ba8-180b-11e7-9892-bcb965bab016.png)

icecast2 and liquidsoap Logs are empty

**Comment by Robbt** [comment] 2017-04-03 00:37
What does your system status page show ? Does it show liquidsoap running ?

**Comment by korotkov13** [comment] 2017-04-03 05:02
Everything is running in status page.

**Comment by Robbt** [comment] 2017-04-03 15:49
What distro did you install it on ? I'll try to replicate it. Does rebooting or restarting the airtime-liquidsoap service affect the issue ?

**Comment by korotkov13** [comment] 2017-04-03 16:03
Ubuntu 14.04
restarting liquidsoap didn't affect.

**Comment by korotkov13** [comment] 2017-04-03 18:29
[:error] [pid 30988] [client test.host:61333] PHP Warning:  parse_ini_file(/etc/airtime/production/airtime.conf): failed to open stream: No such file or directory in /usr/share/airtime/php/airtime_mvc/application/configs/conf.php on line 90, referer: http://old.orokoro.ru/

**Comment by korotkov13** [comment] 2017-04-03 18:31
there is no production folder in etc/airtime

**Comment by korotkov13** [comment] 2017-04-03 18:34
edited 

> conf.php on line 90
and removed production folder from path, but nothing happens

**Comment by Robbt** [comment] 2017-04-03 20:38
ok, weird there should be a symlink from /etc/airtime/production back to /etc/airtime created by the install, but this might only happen if you are installing it for the first time, or something might of happened. This is kind of a legacy of the initial work we did working around some of the saas stuff. I'll have to see if I run into the same issue and submit a fix.

**Comment by Robbt** [comment] 2017-04-04 00:06
I think I found a fix.
 You can manually remove the include on the 8th line of /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq 
delete or comment out this # %include "library/pervasives.liq"
and see if it works.

I put in a PR to fix it.

**Comment by korotkov13** [comment] 2017-04-04 10:22
Thanks! It helped.
