### ISSUE TITLE
 does not record

### ISSUE THREAD

**Issue by mikolaj1806** [LibreTime/libretime#321] opened 2017-10-07 11:11 UTC
Hi, I added the broadcasts to the schedule with the recording option selected. When I turn on the recording, nothing burns :( I'm using ubuntu 14 Please help

**Comment by hairmare** [comment] 2017-10-07 12:41
Hi @mikolaj1806 

Welcome to the community!

Are you trying to use the record-line-in feature? In that case this is a duplicate of #42.

**Comment by mikolaj1806** [comment] 2017-10-10 17:35
Hi @hairmare , thanks for the reply ... I'm using a record-line-in, but that does not change anything. I can not find the answer to my problem in the given issues. Below is a photo and a log with my problem.
![1](https://user-images.githubusercontent.com/20423620/31400708-e6bf3d94-adf0-11e7-922c-8bbdf779be7e.png) 
[show-recorder.log](https://github.com/LibreTime/libretime/files/1372797/show-recorder.log)

**Comment by hairmare** [comment] 2017-10-11 18:16
Record Line-IN is currently broken as it has only been partially implemented. I started some work on restoring the feature so it might even have recorded something, somewhere. The state of the implementation is more or less described in #42 which reported that the the feature was missing on the saas branch from legacy upstream we based LibreTime on.

I'm hoping to find time to put some work into line-in recording but can't make any promises, anyway pull requests to work on this are more than welcome!

**Comment by hairmare** [comment] 2017-11-15 17:20
Closing since this duplicates #42.

**Closed by hairmare** 2017-11-15 17:20 UTC
