### ISSUE TITLE
ghost tracks

### ISSUE THREAD

**Issue by jmtrivial** [LibreTime/libretime#46] opened 2017-03-07 12:45 UTC
Dear Libretime developpers,

I'm using an old Airtime instance for Radio Campus Clermont-Ferrand, and it appends once every two or three months a strange configuration.

We usually create a show for each hour with a repetition during all the month, then we fill each hour by a playlist containing smart blocks. A large part of the time, this process works correctly. But sometimes, the filling of a shows goes bad: two playlists are played simultaneously. If we remove the playlist contained in the show, it still have some ghost tracks we cannot see or remove. Usually, these ghost tracks are not covering the show, and they stop after 20 or 30 minutes.

Do you know:
 * where this playlist is programmed?
 * how to remove them?

Thank you in advance.

**Comment by hairmare** [comment] 2017-03-07 13:32
Hi Jean-Marie

I think managing playlists is in [PlaylistController](https://github.com/LibreTime/libretime/blob/0f8c3b7c92496af1a59aba04b1573dacd235e0ad/airtime_mvc/application/controllers/PlaylistController.php) for the most part with assigning them to shows being in [ScheduleController](https://github.com/LibreTime/libretime/blob/0f8c3b7c92496af1a59aba04b1573dacd235e0ad/airtime_mvc/application/controllers/ScheduleController.php).

Some quick tests with master indicate that the process to assign smartblocks to playlists and those to a show might have changed a bit in LibreTime. I was able to assign a smartblock to a playlist and add that to a repeated show instance like you describe.

The 👻  tracks might need to be removed directly from the database, we also need to figure out how to not make them get written. Having the db schema somewhat documented would be nice for this. Do you know in what table the 👻 entries are? If you can't "see" them, how do you notice they are there? During playout?

Can you let us know which version of Airtime you are running on? It might be something that was fixed later on as I have not seen this issue described before.

Once #39 and #24 are finished and merged we should have an environment where you can maybe try reproducing the issue against current master (it really has alot of fixes already).

**Comment by jmtrivial** [comment] 2017-03-07 13:50
Hi Lucas

We are using Airtime 2.5.1. I didn't yet checked in which table the entries are. We noticed they were there during the playout (two songs at the same time in an FM radio, not good ^^).

I wrote here to report and to suggest that it could be interesting to have a more raw access to the scheduled titles in the interface, dedicated to the administrator, such that he'll be able to handle these specific problems.
By the way, detecting these ghost titles in the tables will be a big challenge since I'm not sure how they can be distinguished from the "normal" ones.

Thank you for your answer, it helps me to go deeper in the source code and data base...

**Comment by hairmare** [comment] 2017-03-07 14:27
Well, 2.5.1 isn't that old with regard to the low level changes.

The 👻s might be distinguishable because they lack a mapping in a table elsewhere (ie. something mapping them to a smart block that points to a deleted smart block or similar, likely needing something `OUTER JOIN`y to figure out).

I figured I would let my hardcore-admins use something akin to phpPgAdmin but that might be to low level.

Maybe the autodj feature will also fit the bill. I haven't tested it yet; if it doesn't cover your use case maybe the one on the zelnograd airtime fork does (at a quick glance it behaves somewhat similar to what airtime.pro is doing).

**Comment by Robbt** [comment] 2017-03-11 02:49
I think this is the issue that was fixed in 2.5.2, but due to the issues with a lack of debs and install only working on Ubuntu and various other issues it never was adopted by the community. I can't refer to the specific code but I do recall reading that this was most of the work done between 2.5.1 and 2.5.2. So hopefully this isn't a problem with LibreTime, let us know if you are able to test it and confirm the issue otherwise we should probably close this issue at some point and re-open it if we ever get a confirmation of it.

**Comment by jmtrivial** [comment] 2017-03-15 21:33
Just to document a bit more the problem, it seems that I have some tracks that are played even if they are outside of their show:

select count(*) from cc_schedule as s inner join cc_show_instances as si on s.instance_id = si.id where not s.starts between si.starts and si.ends and media_item_played = 't';

do not return 0 on my Airtime instance. Unfortunatly, this bug only appears once every month and is not easy to detect...

**Comment by Robbt** [comment] 2018-01-27 20:31
I'm going to close this because we haven't confirmed that this bug is occuring in LibreTime. If ghost tracks become a confirmed issue we can re-open this.

**Closed by Robbt** 2018-01-27 20:31 UTC
Labels: bug
