### ISSUE TITLE
Replaygain not working an all tracks

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#772] opened 2019-03-11 00:04 UTC
Hi,

im just trying to figure out why replaygain does just work on some tracks but not on all 
I have currently imported about 600 tracks, and just 50% of them has replaygain value.

<img width="771" alt="Screenshot 2019-03-11 at 00 42 48" src="https://user-images.githubusercontent.com/27486434/54093537-1a313300-4399-11e9-9a7d-2ca4abc758c1.png">

so i have started from scratch and converted/ripped a track from soundcloud per 
9soundclouddownloader.com
renamed to test.mp3
uploaded to libretime

<img width="1780" alt="Screenshot 2019-03-11 at 00 53 08" src="https://user-images.githubusercontent.com/27486434/54093544-2a491280-4399-11e9-8571-269ea0ef2854.png">

 the track has no replaygain value
so i run replaygain from console

`root@radyo1127:~# locate test.mp3
/srv/airtime/stor/imported/1/test.mp3
root@radyo1127:~# replaygain /srv/airtime/stor/imported/1/test.mp3
Checking for Replay Gain information ...
  /srv/airtime/stor/imported/1/test.mp3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rgain/script/replaygain.py", line 85, in do_gain
    trackdata, albumdata = formats_map.read_gain(filename)
  File "/usr/lib/python2.7/dist-packages/rgain/rgio.py", line 391, in read_gain
    return accessor.read_gain(filename)
  File "/usr/lib/python2.7/dist-packages/rgain/rgio.py", line 283, in read_gain
    rgorg_track_gain, rgorg_album_gain = self.rgorg.read_gain(filename)
  File "/usr/lib/python2.7/dist-packages/rgain/rgio.py", line 85, in read_gain
    tags = self._get_tags_object(filename)
  File "/usr/lib/python2.7/dist-packages/rgain/rgio.py", line 191, in _get_tags_object
    return self._ReplaygainEasyID3(filename)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.42.0-py2.7.egg/mutagen/easyid3.py", line 170, in __init__
    self.load(filename)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.42.0-py2.7.egg/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.42.0-py2.7.egg/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.42.0-py2.7.egg/mutagen/id3/_file.py", line 154, in load
    self._header = ID3Header(fileobj)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.42.0-py2.7.egg/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen-1.42.0-py2.7.egg/mutagen/id3/_tags.py", line 66, in __init__
    raise ID3NoHeaderError("%r doesn't start with an ID3 tag" % fn)
ID3NoHeaderError: u'/srv/airtime/stor/imported/1/test.mp3' doesn't start with an ID3 tag`

i get an error does not start with an ID3 Tag

so i run this command 
mid3v2 -C /srv/airtime/stor/imported/1/test.mp3

after that replaygain was able to analyze the file and write the tag 

`root@radyo1127:~# mid3v2 -C /srv/airtime/stor/imported/1/test.mp3
root@radyo1127:~# replaygain /srv/airtime/stor/imported/1/test.mp3
Checking for Replay Gain information ...
  /srv/airtime/stor/imported/1/test.mp3: none
Calculating Replay Gain information ...
  /srv/airtime/stor/imported/1/test.mp3: -3.52 dB
  Album gain: -3.52 dB
Writing Replay Gain information to files ...
  /srv/airtime/stor/imported/1/test.mp3: done
Done
root@radyo1127:~# replaygain --show /srv/airtime/stor/imported/1/test.mp3
/srv/airtime/stor/imported/1/test.mp3
  Reference loudness 89 dB
  Track gain -3.52 dB
  Track peak 1.00000000
  Album gain -3.52 dB
  Album peak 1.00000000
root@radyo1127:~# `

but im not able to re-scan the file to get the tag into libretime database

any ideas on that ?

logs complete
<img width="933" alt="Screenshot 2019-03-11 at 01 05 50" src="https://user-images.githubusercontent.com/27486434/54093608-ed315000-4399-11e9-98fc-e3a521b56882.png">

**Comment by Robbt** [comment] 2019-04-23 01:54
This is being marked a duplicate of #225 and we can use that bug to track fixing of this.

**Closed by Robbt** 2019-04-23 01:54 UTC
Labels: analyzer, bug
