### ISSUE TITLE
re RSS import

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#583] opened 2018-11-03 00:04 UTC
Specifically, if there are NO listeners, does LT still import?
It seems mine doesn't. Is it just me? I made a curl listener and that seems to fix it.

**Comment by Robbt** [comment] 2018-11-03 14:49
This is a duplicate or at least caused by the same issue addressed in #129 - I tapped into the same flawed triggering mechanism that requires a hit to the API which is either triggered by someone browsing the website or a track being scheduled by LT. If I don't get a fix done directly within python then setting up a cron job would be another easy way to address this. I'm going to close this just because we already have an issue. I really think the right fix is to modify the python service to periodically ping the API or to de-couple the scheduling mechanism from the API and trigger it that way but this fix is one I've been really slow to code when it can be fixed with a cron job that takes like 2 minutes to right. Either way, I'm going to close this as a duplicate and we can continue the discussion on #129.

**Closed by Robbt** 2018-11-03 14:49 UTC
Labels: duplicate

**Comment by JohnnyC1951** [comment] 2018-11-05 12:19
Yes my hourly curl cron job does fix it. It means I have one fake listener 59 mins an hour, but I don't care
Thanks
