### ISSUE TITLE
Don't work sound

### ISSUE THREAD

**Issue by Hrecha** [libretime/libretime#2367] opened 2023-02-08 06:51 UTC
### Describe the bug

i have 2 computers, one raspberry pi 4b and one common , i try to use newer version of libretime 3.0.1, but i don't have settings for ALSA
raspberry pi4b have raspberry os x64, dtpara=sound=on in /boot/firmware/usercfg.txt, alsamixer with one device
computer debian 11 with the same result, but i try ubuntu 20.04.05 playout dont start
![image](https://user-images.githubusercontent.com/37973182/217453616-b9cc34bf-9d11-4e25-8e91-c2bccee1a084.png)
like that
![image](https://user-images.githubusercontent.com/37973182/217454443-613a6204-aca8-4d25-b12b-03e9579bbf77.png)
where it can enebled?
i set it in /etc/libretime/config.yml
![image](https://user-images.githubusercontent.com/37973182/217455464-a87ac083-5a2a-41de-9665-5c3073f333e2.png)

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ...

### Expected behavior

have settings button for hardware output

### LibreTime version

3.0.1

### Installation method and OS / Environment

Operating system: debian 11
Method: Installer script

### Client Environment

Operating system:
Browser:

**Comment by Hrecha** [comment] 2023-02-08 07:33
![image](https://user-images.githubusercontent.com/37973182/217463761-c38d0528-aee3-48b9-8c5b-45fe6a3af4c6.png)

**Comment by jooola** [comment] 2023-02-08 10:47
The system/soundcard output is now configured from the configuration file. https://libretime.org/docs/admin-manual/setup/configuration/#system

You need to restart the libretime services after a configuration change to apply the configuration.

In addition, if you use the system/soundcard output, you need to add the `libretime` user to the `audio` group.

See https://libretime.org/docs/admin-manual/setup/install/#using-hardware-audio-output

**Comment by jooola** [comment] 2023-02-08 10:51
Closing as this is a question and not a bug. Feel free to reopon if you do have a bug.

**Closed by jooola** 2023-02-08 10:51 UTC
Labels: is: question

**Comment by Hrecha** [comment] 2023-02-08 11:18
it continiously spamming with this
![image](https://user-images.githubusercontent.com/37973182/217515306-59fa6ac0-3eda-42f8-b0ea-fafd05395bb8.png)

**Comment by Hrecha** [comment] 2023-02-08 11:24
root@bbv-sound:/home/ubuntu/libretime# sudo adduser libretime audio
The user libretime is already a member of audio.
on my screenshot with two windows i enabled hardware output, try change all output parameters, but it doesn't works

**Comment by jooola** [comment] 2023-02-08 11:25
If you are using pulseaudio, you might need to add the libretime user to the pulseaudio group as well.

**Comment by jooola** [comment] 2023-02-08 11:27
And you should probably test that the pulseaudio setup is working on its own, https://en.wikibooks.org/wiki/Configuring_Sound_on_Linux/Pulse_Audio/Testing

**Comment by Hrecha** [comment] 2023-02-08 11:55
i have aux cable joining to amplifier, on older versions previously there was a parameter - alsa

**Comment by jooola** [comment] 2023-02-08 12:08
Please read my comments and the documentation. **The new way of configuring the hardware output happens in the configuration file.**

You can use the alsa output by defining:
```yaml
stream:
  outputs:
    # System outputs.
    # > max items is 1
    system:
      - # Whether the output is enabled.
        # > default is false
        enabled: false
        # System output kind.
        # > must be one of (alsa, ao, oss, portaudio, pulseaudio)
        # > default is alsa
        kind: "alsa"
```

**Comment by Hrecha** [comment] 2023-02-08 22:31
i already reading the documentation, made it first
step by step
./install http://10.35.24.222
sudo adduser libretime audio
sudo -u libretime libretime-api migrate
sudo systemctl start libretime.target
sudo systemctl --all --plain | grep libretime

in config.yml
setting up

> 
    system:
      - # Whether the output is enabled.
        # > default is false
        enabled: true
        # System output kind.
        # > must be one of (alsa, ao, oss, portaudio, pulseaudio)
        # > default is alsa
        kind: "alsa"

we have 8 raspberry pi already playing music in another cities
ubuntu 18 with libretime 2019-2021 years takes from git folder, not release version
all of this have alsa audio output

i trying to install libretime with complects of os and libretime version:
>
1 on nettop
LibreTime 3.0.0 alpha 12
Ubuntu 20.04.05
mute after one hour, doesn't have function automute
repairing action: set in global parameters at site another output device and back alsa
in logs liquidsoap restarted, sound start playing
> 
2 on nettop, 3 tries with full reinstall
LibreTime 3.0.1
Ubuntu 20.04.05
dont start playout services and site
>
3 on nettop
LibreTime 3.0.1
Debian Bullseye 11
all started, but don't work sound output(I sended photo with setting "enabled" and "alsa")
>
4 on raspberry pi
LibreTime 3.0.1
Raspberri pi os
same result with 3


i send screenshot with spamming error service liquidsoap, restarting every minute
you didn't say anything about it

with all due respect, I ask you to consider this issue, I have been having a problem for 2 weeks, I have no goal to bother you, I turned to you for support because I have run out of solutions

**Comment by paddatrapper** [comment] 2023-02-09 06:43
The logs say that Liquidsoap cannot connect to PulseAudio. Is pulseaudio running and working as expected?

> And you should probably test that the pulseaudio setup is working on its own, https://en.wikibooks.org/wiki/Configuring_Sound_on_Linux/Pulse_Audio/Testing

**Comment by Hrecha** [comment] 2023-02-09 11:23
sorry for confusing you, pulseaudio was like one of the options to understand why the sound is not working, the screenshot was taken with it.
The project uses only ALSA, when checking the sound through "aplay" command, it works.
now I will reinstall again for a clean setup, most likely I will record a video.
