### ISSUE TITLE
Libretime tries to play icecast HTTPS

### ISSUE THREAD

**Issue by AnonymousWebHacker** [LibreTime/libretime#1128] opened 2020-12-09 06:44 UTC
If I enter the icecast page, I get that there is a transmission, I even get to connect to it through a music player.

However, the libretime page, I also get that there is a transmission, but nevertheless, I cannot reproduce it from that same page.

When I check the source code of the page, I realize that it is trying to find an icecast but with HTTPS, when the one that is transmitting is in HTTP

I mean, I don't understand, if libretime is configured to broadcast at HTTP://icecast.example.com:8000, why is the libretime page trying to play from HTTPS://icecast.example.com?
![2020-12-09_062034](https://user-images.githubusercontent.com/43164089/101593779-2440f500-39b6-11eb-9a06-1c32197a39a9.png)

**Comment by paddatrapper** [comment] 2020-12-09 16:13
Duplicate of #1102

**Closed by paddatrapper** 2020-12-09 16:13 UTC
Labels: bug

**Comment by AnonymousWebHacker** [comment] 2020-12-10 03:31
@paddatrapper Thank you very much, I found the solution in that post
