### ISSUE TITLE
Problem: Installer might not be saving non-default rabbitmq passwords

### ISSUE THREAD

**Issue by superking82** [LibreTime/libretime#493] opened 2018-06-26 02:27 UTC
![2018-06-25 21_23_09-an error has occurred - opera](https://user-images.githubusercontent.com/40586060/41885640-6f0e4850-78be-11e8-9bb0-c24a32cad18c.png)

This happens any time I change anything in Settings and hit Save.  Running Ubuntu 14.04 and Libretime 

I also get errors trying to upload or do anything else.  This is a fresh install using the install script.

**Comment by Robbt** [comment] 2018-06-27 11:49
You will need to check the logs under /var/log/airtime/zend-php.log to provide more information.

**Comment by JohnnyC1951** [comment] 2018-06-27 11:58
I would start with checking folder permissions. Seems like it can't write to tmp and elsewhere.

**Comment by superking82** [comment] 2018-06-28 02:53
So, I fixed it by either doing one of two things:
I reloaded the server, then before running the install script i did `apt-get update` and `apt-get upgrade`
Another thing, is I left the default password for the _airtime_ user for _RabbitMQ_
 .
Now, the thing is if I change the password for the _airtime_ user to anything else, I start getting that same error again.  I'm looking everywhere but can't find a way to change it.  Any ideas please?

**Comment by Robbt** [comment] 2018-06-28 17:20
I think the config is under /etc/airtime/airtime.conf where you need to change it after the fact. I don't recall it being hardcoded but rabbitmq failing sounds like a good reason for all of this stuff to not be working.

**Comment by superking82** [comment] 2018-07-01 16:53
Well, I changed the password using this
`sudo rabbitmqctl change_password airtime mynewpassword`

Then I changed it in _/etc/airtime/airtime.conf_
then it broke again.  when I changed it back to the default generic password it worked again.

Do I need to change it in psql as well?  Is there something else missing?  I know the installer advises that we change the default login password, but seems to break it every time I do.  Thanks again.

**Comment by Robbt** [comment] 2018-07-01 18:54
Hmm, this is odd and unexpected. I'm not sure what the cause of this is without testing it further myself. I remember setting something other than the default value and having it work but perhaps there has been a change that broke this.

**Comment by Robbt** [comment] 2018-10-21 20:53
So in order to close this we need to test and confirm whether using a non-default rabbitmq password will work. If it doesn't then there is an issue with the installer that needs to be addressed. If it does then something went wrong on this instance that we should either try to reproduce or close until we have it occur again.

**Comment by Robbt** [comment] 2018-10-31 11:38
Ok, so I tested this and it is currently working. I think the issue was that the user above ran into was that they were attempting to manually edit the /etc/airtime/airtime.conf which was overwritten by the installer. This is expected as writing /etc/airtime/airtime.conf shouldn't be done by hand.

**Closed by Robbt** 2018-10-31 11:38 UTC
Labels: bug, installer
