### ISSUE TITLE
Playlist showing more than 20000 pages

### ISSUE THREAD

**Issue by arifuddin2007** [LibreTime/libretime#743] opened 2019-02-18 18:24 UTC
The playlist section in dashboard is showing more than 22,000 pages with 100 records in each page. Refer the attached screenshot.

This is making is very difficult to load and manage playlists. 

<img width="576" alt="screenshot 2019-02-18 at 23 50 40" src="https://user-images.githubusercontent.com/18372992/52970009-601d5b80-33d8-11e9-8e8b-f8d8c21b9351.png">

**Comment by Robbt** [comment] 2019-02-18 18:26
Ok, this is annoying and a bug we have seen before but haven't been able to pinpoint the cause.
You can see #411 for an example of the sql command that can delete all of these. 
What I'd really like to do is figure out the cause so we can prevent this from happening. This is in essence a duplicate of #411 so I'm going to close this issue and we can continue discussion there to attempt to find a fix.

**Closed by Robbt** 2019-02-18 18:26 UTC
