### ISSUE TITLE
[Ubuntu 16.04.2] Tracks on upload aren't get saved

### ISSUE THREAD

**Issue by Lapotor** [LibreTime/libretime#175] opened 2017-04-20 17:35 UTC
When i Upload any track it show that it is Uploaded:
![libretime 16 04](https://cloud.githubusercontent.com/assets/17144397/25244273/49a3423a-2600-11e7-9087-6ac40f3559c0.png)
But they aren't get saved on the Server:
![libretime 16 04 v2](https://cloud.githubusercontent.com/assets/17144397/25244299/63bd50fc-2600-11e7-835a-b97b94af68d8.png)
_(I look on the server too.)_

**Comment by hairmare** [comment] 2017-04-20 18:06
This is weird, I'm pretty sure I saw this working and listened to some uploads in my tests. The uploads should show up in the Recent uploads (the right part of your first screenshot) as either imported or failed.

Is there anything suspicious in `/var/log/airtime/zendphp.log` or in the output of `sudo journalctl -u airtime_analyzer`?

**Comment by Lapotor** [comment] 2017-04-20 18:13
No nothing suspicious in `/var/log/airtime/zendphp.log` only that it changed one time from .net to .de and after that never again.
And here the output from `sudo journalctl -u airtime_analyzer`:
```
root@libretime:/home/libretime# sudo journalctl -u airtime_analyzer
-- Logs begin at Do 2017-04-20 18:11:12 CEST, end at Do 2017-04-20 20:08:47 CEST. --
Apr 20 18:31:31 libretime systemd[1]: Starting LSB: Manage airtime_analyzer daemon...
Apr 20 18:31:31 libretime airtime_analyzer[28681]: Starting airtime_analyzer: Done.
Apr 20 18:31:31 libretime systemd[1]: Started LSB: Manage airtime_analyzer daemon.
root@libretime:/home/libretime#
```

**Comment by hairmare** [comment] 2017-04-20 18:26
Looks like you'll have to start analyzer manually to get some real logs 😞 

```
sudo -u www-data airtime_analyzer
```

**Comment by Lapotor** [comment] 2017-04-20 18:54
then i only get this:
```
root@libretime:~# sudo -u www-data airtime_analyzer
Airtime Analyzer 1.0
2017-04-20 20:42:47,234 [message_listener] [INFO ]   Listening for messages...
```

**Comment by hairmare** [comment] 2017-04-21 01:13
That adds up :/ It should output more info when you upload something. Did you stop any existing analyzer process before running `sudo -u www-data airtime_analyzer`?

**Comment by Lapotor** [comment] 2017-04-22 14:33
Yeah no analyzer process is there anymore and it have the same when i upload an file.

**Comment by semihs** [comment] 2017-05-01 08:49
+1

**Comment by hairmare** [comment] 2017-05-26 12:36
I'm not sure if anyone still has this issue. Maybe you could try checking if `base_url` and `base_port` from `/etc/airtime/airtime.conf` are reachable from the command line using curl or wget.

**Comment by hairmare** [comment] 2017-05-27 12:16
I can reproduce this on Ubuntu Xenial/16 deployed to [dply.co](https://dply.co) using the following cloud-init:

```bash
#!/bin/sh
export DEBIAN_FRONTEND=noninteractive;
# The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
export COMPOSER_HOME=/tmp

# update system
apt-get update;
apt-get -y upgrade;
apt-get install unzip;

# change to /tmp and download libretime
cd /tmp;
curl -O -L https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.1/libretime-3.0.0-alpha.1.tar.gz;
tar xvf libretime-3.0.0-alpha.1.tar.gz;
cd libretime-3.0.0-alpha.1/;

# install libretime
./install -fiap;
```

Among other issues the directories `/src/airtime/stor/organize` and `/srv/airtime/stor/imported` do not seem to get created on those boxes. I'm going to try a git install next to see if that makes a difference.

**Comment by hairmare** [comment] 2017-05-27 12:48
I updated the example above to install from master and am still able to (finally) reproduce this. For some weird reason the MediaControllers indexAction is getting called instead of the postAction. This could be something incompatible with php 7.0 but I need to dig a bit further to figure it out.

**Comment by hairmare** [comment] 2017-05-27 15:47
I can confirm that this is a php7 issue, is didn't figure out why exactly it's failing on php7.

For the time being Xenial users can downgrade to php5. At least a quick and dirty https://dply.co deploy using the following cloud-init seems to work with regards to uploads and playout.

```bash
#!/bin/sh
export DEBIAN_FRONTEND=noninteractive;
# The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
export COMPOSER_HOME=/tmp

# update system
apt-get update;
apt-get -y upgrade;
apt-get install -y unzip git software-properties-common;

# enable ppa with php5.6
add-apt-repository -y ppa:ondrej/php;
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C;

# change to /tmp and download libretime
cd /tmp;
git clone --depth=1 -b master --single-branch https://github.com/LibreTime/libretime.git;
cd libretime/;

# downgrade php version in installer and skip modules that are not available
sed -i -e 's/php7.0/php5.6/' -e 's/php-/php5.6-/' -e 's/php5.6-apcu//' -e 's/php5.6-pear//' installer/lib/requirements-ubuntu-xenial.apt;
sed -i -e 's/7.0/5.6/' install;

# install libretime
./install -fiap;
```

I'll do some more testing with a local vagrant setup and try figuring out where the php parts are failing with php 7.0. I'll probably downgrade to php 5.6 in the installer since php 5.6 is still getting security patches for more than a year. We'll still have plenty of time to port everything to php 7.

**Comment by Robby262** [comment] 2017-05-27 15:58
Is it possible to run just LT in 5.6? Else lots of Xenial stuff will stop working.

**Comment by hairmare** [comment] 2017-05-28 11:04
> Is it possible to run just LT in 5.6? Else lots of Xenial stuff will stop working.

Not out of the box. 

Maybe fcgi works as described [in this stackoverflow answer](https://askubuntu.com/a/250187) but running LibreTime under fcgi is completely untested. 

Running LibreTime in a virtual machine and proxying from the host apache is another way around this. Using a docker or lxc container for the web parts is a similar strategy.

A dedicated box is the recommended way to go, doing otherwise comes with some manual configuration and installation overhead but generally gives more control over the system. Once LibreTime plays nice with php 7 coexisting with other apps will be easier. It's hard to tell when that will be ready. Debian 9 will certainly also be a factor in supporting php 7.

**Comment by Robby262** [comment] 2017-05-28 11:36
Repacking a plain vanilla working LT install as an ISO image - ie a Libretime Distro - might save lots of trouble downline and could be simply loaded into droplets/whatever - especially if added to the tasksel list. I did a repo repack some years ago. It seemed quite easy to do at the time.

**Comment by Lapotor** [comment] 2017-05-28 13:25
you can install php5.6 with an ppa

**Comment by hairmare** [comment] 2017-05-28 14:35
Exactly, I'm preparing to add the following to the installer so LibreTime finally works on Xenial.

```bash
add-apt-repository -y ppa:ondrej/php;
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C;
```

**Comment by hairmare** [comment] 2017-06-12 18:43
@Lapotor This should be fixed for PHP7 on Xenial with #226!

**Comment by hairmare** [comment] 2017-07-17 19:34
Ubuntu Xenial support (with php7 out of the box) was fixed in the now released `3.0.0-alpha.2`.

**Closed by hairmare** 2017-07-17 19:34 UTC

**Comment by xabispacebiker** [comment] 2017-07-20 16:44
Same problem here, current show will seem to be playing but the stream is silence.

`cat /var/log/airtime/pypo-liquidsoap/ls_script.log `

```
2017/07/20 18:40:11 >>> LOG START
2017/07/20 18:40:10 [protocols.external:3] Found "/usr/bin/wget".
2017/07/20 18:40:10 [main:3] Liquidsoap 1.1.1
2017/07/20 18:40:10 [main:3] Using: graphics=[distributed with Ocaml] pcre=7.0.4 dtools=0.3.1 duppy=0.5.1 duppy.syntax=0.5.1 cry=0.2.2 mm=0.2.1 xmlplaylist=0.1.3 lastfm=0.3.0 ogg=0.4.5 vorbis=0.6.1 opus=0.1.0 speex=0.2.0 mad=0.4.4 flac=0.1.1 flac.ogg=0.1.1 dynlink=[distributed with Ocaml] lame=0.3.2 shine=0.2.0 gstreamer=0.2.0 frei0r=0.1.0 voaacenc=0.1.0 theora=0.3.0 schroedinger=0.1.0 gavl=0.1.5 bjack=0.1.4 alsa=0.2.1 ao=0.2.0 samplerate=0.1.2 taglib=0.3.1 magic=0.7.3 camomile=0.8.4 inotify=1.0 faad=0.3.2 soundtouch=0.1.7 portaudio=0.2.0 pulseaudio=0.1.2 ladspa=0.1.4 dssi=0.1.1 sdl=0.9.1 camlimages=4.0.0 lo=0.1.0 yojson=1.1.8 gd=1.0a5
2017/07/20 18:40:10 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2017/07/20 18:40:10 [dynamic.loader:3] Could not find dynamic module for aacplus encoder.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/lame.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/faad.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/ogg.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/vorbis.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/pulseaudio.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/cry.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/voaacenc.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/mad.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac_ogg.cmxs.
2017/07/20 18:40:10 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/taglib.cmxs.
2017/07/20 18:40:11 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2017/07/20 18:40:11 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2017/07/20 18:40:11 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2017/07/20 18:40:11 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2017/07/20 18:40:11 [lang:3] timeout --signal=KILL 45 pyponotify --liquidsoap-started &
2017/07/20 18:40:11 [threads:3] Created thread "generic queue #1".
2017/07/20 18:40:11 [threads:3] Created thread "generic queue #2".
2017/07/20 18:40:11 [threads:3] Created thread "non-blocking queue #1".
2017/07/20 18:40:11 [threads:3] Created thread "non-blocking queue #2".
2017/07/20 18:40:11 [harbor:3] Adding mountpoint '/master' on port 8001
2017/07/20 18:40:11 [harbor:3] Adding mountpoint '/show' on port 8002
2017/07/20 18:40:11 [threads:3] Created thread "http polling" (1 total).
2017/07/20 18:40:11 [sonicbunker(dot)ogg:3] Connecting mount sonicbunker.ogg for source@airean.info...
2017/07/20 18:40:11 [sonicbunker(dot)ogg:3] Connection setup was successful.
2017/07/20 18:40:11 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=1 --time=1500568811.1 &
2017/07/20 18:40:11 [sonicbunker(dot)mp3:3] Connecting mount sonicbunker.mp3 for source@airean.info...
2017/07/20 18:40:11 [sonicbunker(dot)mp3:3] Connection setup was successful.
2017/07/20 18:40:11 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=2 --time=1500568811.1 &
2017/07/20 18:40:11 [threads:3] Created thread "wallclock_main" (2 total).
2017/07/20 18:40:11 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2017/07/20 18:40:11 [dummy:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:11 [dummy(dot)1:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:11 [dummy(dot)2:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:11 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:11 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:11 [map_metadata_5350:3] Inserting missing metadata.
2017/07/20 18:40:11 [master_show_schedule_noise_switch:3] Switch to show_schedule_noise_switch.
2017/07/20 18:40:11 [show_schedule_noise_switch:3] Switch to schedule_noise_switch.
2017/07/20 18:40:11 [schedule_noise_switch:3] Switch to map_metadata_5350.
2017/07/20 18:40:15 [server:3] New client: localhost.
2017/07/20 18:40:15 [server:3] Client localhost disconnected.
2017/07/20 18:40:15 [server:3] New client: localhost.
2017/07/20 18:40:15 [lang:3] queues.s8_skip
2017/07/20 18:40:15 [lang:3] queues.s8_skip
2017/07/20 18:40:15 [lang:3] queues.s8_skip
2017/07/20 18:40:15 [lang:3] queues.s8_skip
2017/07/20 18:40:15 [lang:3] queues.s8_skip
2017/07/20 18:40:15 [server:3] Client localhost disconnected.
2017/07/20 18:40:15 [switch_5341:3] Switch to insert_metadata_5327.
2017/07/20 18:40:15 [cross_5275:3] No next track ready yet.
2017/07/20 18:40:15 [cross_5260:3] No next track ready yet.
2017/07/20 18:40:15 [cross_5245:3] No next track ready yet.
2017/07/20 18:40:15 [cross_5230:3] No next track ready yet.
2017/07/20 18:40:15 [cross_5215:3] No next track ready yet.
2017/07/20 18:40:15 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:16 [server:3] New client: localhost.
2017/07/20 18:40:16 [lang:3] streams.scheduled_play_start
2017/07/20 18:40:16 [lang:3] streams.live_dj_stop
2017/07/20 18:40:16 [lang:3] streams.master_dj_stop
2017/07/20 18:40:16 [lang:3] vars.stream_metadata_type
2017/07/20 18:40:16 [lang:3] vars.station_name
2017/07/20 18:40:16 [lang:3] vars.default_dj_fade
2017/07/20 18:40:16 [server:3] Client localhost disconnected.
2017/07/20 18:40:16 [server:3] New client: localhost.
2017/07/20 18:40:16 [lang:3] queues.s8_skip
2017/07/20 18:40:16 [lang:3] queues.s8_skip
2017/07/20 18:40:16 [lang:3] queues.s8_skip
2017/07/20 18:40:16 [lang:3] queues.s8_skip
2017/07/20 18:40:16 [lang:3] queues.s8_skip
2017/07/20 18:40:16 [server:3] Client localhost disconnected.
2017/07/20 18:40:16 [schedule_noise_switch:3] Switch to map_metadata_5343 with transition.
2017/07/20 18:40:16 [lang:3] transition called...
2017/07/20 18:40:16 [switch_5341:3] Switch to insert_metadata_5327.
2017/07/20 18:40:16 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:16 [schedule_noise_switch:3] Switch to map_metadata_5350 with forgetful transition.
2017/07/20 18:40:16 [lang:3] transition called...
2017/07/20 18:40:19 [server:3] New client: localhost.
2017/07/20 18:40:19 [decoder:3] Method "MAD" accepted "/var/tmp/airtime/pypo/cache/scheduler/3.mp3".
2017/07/20 18:40:19 [lang:3] vars.show_name
2017/07/20 18:40:19 [server:3] Client localhost disconnected.
2017/07/20 18:40:19 [server:3] New client: localhost.
2017/07/20 18:40:19 [lang:3] dynamic_source.get_id
2017/07/20 18:40:19 [decoder:2] Decoder "MAD" betrayed us on "/var/tmp/airtime/pypo/cache/scheduler/3.mp3"!
2017/07/20 18:40:19 [s4:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/3.mp3" (RID 0).
2017/07/20 18:40:19 [s4:3] Finished with "/var/tmp/airtime/pypo/cache/scheduler/3.mp3".
2017/07/20 18:40:19 [cue_cut_5268:3] Cueing in...
2017/07/20 18:40:19 [cue_cut_5268:2] Could not seek to cue point!
2017/07/20 18:40:19 [cue_cut_5268:3] End of track before cue-out point.
2017/07/20 18:40:19 [amplify_5272:3] Overriding amplification: 1.000000.
2017/07/20 18:40:19 [amplify_5272:3] End of the current overriding.
2017/07/20 18:40:19 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=18 &
2017/07/20 18:40:19 [server:3] Client localhost disconnected.
2017/07/20 18:40:19 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:23 [server:3] New client: localhost.
2017/07/20 18:40:23 [decoder:3] Method "MAD" accepted "/var/tmp/airtime/pypo/cache/scheduler/3.mp3".
2017/07/20 18:40:23 [lang:3] vars.show_name
2017/07/20 18:40:23 [server:3] Client localhost disconnected.
2017/07/20 18:40:23 [decoder:2] Decoder "MAD" betrayed us on "/var/tmp/airtime/pypo/cache/scheduler/3.mp3"!
2017/07/20 18:40:23 [s4:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/3.mp3" (RID 1).
2017/07/20 18:40:23 [s4:3] Finished with "/var/tmp/airtime/pypo/cache/scheduler/3.mp3".
2017/07/20 18:40:23 [cue_cut_5268:3] End of track before cue-out point.
2017/07/20 18:40:23 [amplify_5272:3] Overriding amplification: 1.000000.
2017/07/20 18:40:23 [amplify_5272:3] End of the current overriding.
2017/07/20 18:40:23 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=19 &
2017/07/20 18:40:23 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2017/07/20 18:40:55 [server:3] New client: localhost.
2017/07/20 18:40:55 [lang:3] dynamic_source.get_id
2017/07/20 18:40:55 [server:3] Client localhost disconnected.
```

On Air button gets red. Settings status shows all services up and running (green checkmark).

When connecting to the stream url, it connects as if the radio were offline.

**Comment by hairmare** [comment] 2017-07-20 17:18
@xabispacebiker This is about uploading on Ubuntu 16 and the fix for it also helped with Debian 9. Your issue looks more like #213 or #140.

**Comment by xabispacebiker** [comment] 2017-07-20 20:52
Well, I do not think is much related to #213 as my system is not failing at all. Everything looks like if it were working, is just that I do not get the audio output. VLC connects to the streaming too, but it shows the offline message, although there is running show with content. Uploads work as well... so just to be unserstood... Everything works but it finally streams silence (as when in offline mode). 
But I read the issue until the end and I followed some of the instructions there, I could finally find something that is suspicious:

[pypofile] [ERROR]  http://airtime.sonicbunker.com:443/rest/media/8/download

I see that pypo is trying to access http in port 443.  The relevant parts of the log below:

```
2017-07-20 22:43:29,216 [recorder] [INFO ]  Bootstrap complete: got initial copy of the schedule
2017-07-20 22:43:29,388 [pypoliquidsoap] [INFO ]  Need to add items to Liquidsoap *now*: set([31])
2017-07-20 22:43:29,388 [pypofile] [INFO ]  copying from https://airtime.sonicbunker.com//rest/media/8 to local cache /var/tmp/airtime/pypo/cache/scheduler/8.mp3
2017-07-20 22:43:29,388 [pypofile] [ERROR]  http://airtime.sonicbunker.com:443/rest/media/8/download
2017-07-20 22:43:29,396 [connectionpool] [INFO ]  Starting new HTTP connection (1): airtime.sonicbunker.com
2017-07-20 22:43:29,402 [pypofile] [ERROR]  <Response [400]>
2017-07-20 22:43:29,402 [pypofile] [ERROR]  Could not copy from https://airtime.sonicbunker.com//rest/media/8 to /var/tmp/airtime/pypo/cache/scheduler/8.mp3
2017-07-20 22:43:29,402 [pypofile] [ERROR]  400 - Error occurred downloading file
2017-07-20 22:43:29,457 [pypofetch] [INFO ]  File '/var/tmp/airtime/pypo/cache/scheduler/9.mp3' removed
2017-07-20 22:43:29,457 [pypofetch] [INFO ]  Bootstrap schedule received: {u'media': {u'2017-07-20-21-35-00'.... []
```

**Comment by xabispacebiker** [comment] 2017-07-20 21:09
Definitely, the problem is PYPO and 443 port, I configured apache now at port 80 and works like a charm. But this is not the final solution, I want to keep 443 port, so what setting should I change to let PYPO now we are working over https ?
