### ISSUE TITLE
Error message uploading files

### ISSUE THREAD

**Issue by leonardpg** [LibreTime/libretime#396] opened 2018-01-02 01:31 UTC
One of my show programmers just sent me the attached screen grabs when she attempted to upload a playlist from iTunes. She also tried uploading a single file from Finder and got the same error. She's using the Chrome browser. I tried recreating the error in Chrome and did not see the error.
<img width="641" alt="screen shot 2018-01-01 at 7 58 54 pm" src="https://user-images.githubusercontent.com/9553791/34472537-8705bf4e-ef32-11e7-8e51-8b4e5b62687a.png">
<img width="649" alt="screen shot 2018-01-01 at 7 59 02 pm" src="https://user-images.githubusercontent.com/9553791/34472538-871a815e-ef32-11e7-88cd-dc356de7dfb2.png">
<img width="641" alt="screen shot 2018-01-01 at 7 59 09 pm" src="https://user-images.githubusercontent.com/9553791/34472539-8728bd32-ef32-11e7-9ef7-da7fbf536865.png">
<img width="647" alt="screen shot 2018-01-01 at 8 12 11 pm" src="https://user-images.githubusercontent.com/9553791/34472540-87369cae-ef32-11e7-88e8-216776b3cbbe.png">

The producer just tried the same thing using Firefox and got the same error:
"With FF, tried uploading 1 and all was well. Then tried uploading 4 more at once and the first was ok, but got the same error on the other 3."

**Comment by hairmare** [comment] 2018-01-02 09:37
It looks like you session is timing out before the actual upload. I was able to reproduce this by killing my cookie in Developer Tools and then uploading a file.

Can you confirm that you are logged out if you reload after running into this? It should work right after logging in but then fail if your session times out.

We should most likely make the error message look better and also tell the user to reload. We should also make sure setting the cookie timeout is either exposed in the ui or well documented. I'm not sure if the latter is a php setting or in code (it could be both).

**Comment by hairmare** [comment] 2018-01-02 10:00
After some further digging I assume that you are seeing this issue after 24 minutes of no activity. These 24 minutes are governed by PHPs session garbage collector. The relevant setting to tweak is [`session.gc_maxlifetime`](http://php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime) (it defaults to 1440 seconds => 24 minutes).

**Comment by leonardpg** [comment] 2018-01-02 14:02
I've never encountered the problem, and the user in question also complains about occasionally being logged out when she's in the middle of tasks on the site, so I'm thinking it's a client-side issue with session cookies...I had her try a different browser and the problem persisted.

**Comment by hairmare** [comment] 2018-01-02 14:12
Could also be a clock issue, is ntp configured properly on the client machine?

**Comment by leonardpg** [comment] 2018-01-02 14:17
Don't know...I just messaged the user and asked that she try using a different computer. I suspect that she's using her work laptop, which possibly has system-wide policies that could affect session length, cookies, etc.

**Comment by Robbt** [comment] 2018-01-27 21:18
It appears that this problem was likely caused by on the client's browser vs. the LT server. So I'm going to close this unless there is further information added.

**Closed by Robbt** 2018-01-27 21:18 UTC
