### ISSUE TITLE
Error during upload new tracks

### ISSUE THREAD

**Issue by cybicz** [libretime/libretime#1554] opened 2022-02-02 10:30 UTC
Hi guys, after long time I need to upload new tracks to my LibreTime, but I'm getting error....

**Steps:**
1. Click on upload
2. Draging mp3 file (44100, 320 kbps cbr) to upload window
3. An error occurred while processing your upload. Please try again in a few minutes. pops out

**LibreTime version:**
3.0.0 alpha 10, 3.0.0 alpha 9

**Installation method:**
- OS: Debian 10 Buster
- Method: downloading libretime-3.0.0-alpha.10.tar.gz, then bash install -fiap

**Client**
- OS: Windows 10 (PC1), OSX (NTB)
- Browser: Chrome on PC1, Chrome and Safari on NTB

**Additional context**
When I'm trying open status page (/systemstatus), I'm getting ,,Oops! Something went wrong!''

**Comment by jooola** [comment] 2022-02-02 10:32
Could you post the analyzer and zendphp log files please ?

**Comment by paddatrapper** [comment] 2022-02-02 12:11
Have you set the rabbitMQ password or changed the password in the config file? Looks like the various components can't communicate to RabbitMQ

**Comment by cybicz** [comment] 2022-02-02 12:28
Nope, I'm using the same password for this instance of LibreTime all the time.. 

[rabbitmq]
host = 127.0.0.1
port = 5672
user = airtime
password = dnbtv******
vhost = /airtime

**Comment by cybicz** [comment] 2022-02-07 11:30
Any other tips? Thanks

**Comment by paddatrapper** [comment] 2022-02-07 11:31
Try upgrade your system, though do note the BREAKING CHANGE notices in the commit messages. There has been work to replace rgain3 and silan with ffmpeg

**Comment by cybicz** [comment] 2022-03-16 11:19
Hi, I did fresh install to a new VPS with Ubuntu 20.04.4 and problem still occured.... Any tips? Thanks

**Comment by esbobkov** [comment] 2022-05-21 10:14
I have same issue in alpha12 when upload 1 hour long mp3 files. Short standart track uploaded successfully.

**Comment by esbobkov** [comment] 2022-09-20 06:59
Сan not reproduce after upgrade to [3.0.0-beta.0](https://github.com/libretime/libretime/releases/tag/3.0.0-beta.0)

**Comment by jooola** [comment] 2022-09-21 09:50
Closing as outdated, @cybicz please let us know if this still happens on the latest version of LibreTime, we can then reopen.

**Closed by jooola** 2022-09-21 09:50 UTC
Labels: is: bug
