### ISSUE TITLE
Intertwined schedule

### ISSUE THREAD

**Issue by Guillarda** [libretime/libretime#2208] opened 2022-10-05 18:02 UTC
### Is your feature request related to a problem?

I want to create a show that start in same time that another block (example in the pictures)
The goal is to have a fully functionnal radio that play music 24 hours a day and 7 days a week and where i can decide to put show without having to adapt all my schedule (like intertwined schedules/show)
![example](https://user-images.githubusercontent.com/65513597/194129403-295d866c-1c7e-4ada-af76-418d2535ce3a.png)

### Describe the solution you'd like

Create an intertwined show system for the schedule

### Describe alternatives you've considered

Any alternative that help us to add a show into a complete music schedule without having that hard to do it

### Additional context

Example of what we search :
![example](https://user-images.githubusercontent.com/65513597/194129801-cf936d9b-faaf-4e75-a286-3bbf6721fe2e.png)

**Comment by jooola** [comment] 2022-10-05 18:03
Related and probbaly duplicate of #1222

**Closed** 2022-10-05 18:04 UTC
Labels: is: feature-request
