### ISSUE TITLE
Debian 8.7 - airtime-liquidsoap status / apache config error

### ISSUE THREAD

**Issue by celiandu61** [LibreTime/libretime#140] opened 2017-04-03 17:18 UTC
Hey, i discovered libretime 2 days go ( so happy to found a fork of airtime :) ). But i have a problem to install it. 

I install it with `./install` like the docs. But after installation i got 2 different issue : 

**With digital ocean server (dply) :** 
That worked only the first time, i have retry it later ( new install of debian ) and i got a problem on the last page of settings. 

Every service are detected up except of airtime-liquidsoap. I retried to restart it manually ( and same for all others services ) but same issue. If i execute `service airtime-liquidsoap status` the service is up... 

![capture du 2017-04-02 23-15-31](https://cloud.githubusercontent.com/assets/6912744/24621418/ad25fe86-18a1-11e7-86a3-72a26e6d6127.png)

**With OVH VPS ( VPS 1 ) :** It's the same issue but sometimes i got the default page of apache. 

All my tests are try with a clear install of debian.

These servers are on debian 8.7 with the 3.16.39-1 kernel on KVM.

Thx to read my issue ;)

**Comment by Lapotor** [comment] 2017-04-03 19:39
Hey we got the same issue if we start/restart liquidsoap with `service airtime-liquidsoap start/restart` it return nothing but if we do `service airtime-liquidsoap status` we get:
```
● airtime-liquidsoap.service - LSB: Manage airtime-liquidsoap daemon
   Loaded: loaded (/etc/init.d/airtime-liquidsoap)
   Active: active (exited) since Mo 2017-04-03 21:21:55 CEST; 5s ago
  Process: 6286 ExecStop=/etc/init.d/airtime-liquidsoap stop (code=exited, status=0/SUCCESS)
  Process: 6294 ExecStart=/etc/init.d/airtime-liquidsoap start (code=exited, status=0/SUCCESS)

Apr 03 21:21:55 airtime systemd[1]: Starting LSB: Manage airtime-liquidsoap daemon...
Apr 03 21:21:55 airtime airtime-liquidsoap[6294]: Starting airtime-liquidsoap: Done.
Apr 03 21:21:55 airtime systemd[1]: Started LSB: Manage airtime-liquidsoap daemon.
```
But on the status and /?config page it say the same as @celiandu61 

```
$ uname -a
Linux airtime 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
$ cat /etc/debian_version
8.7
```
Server is an KVM with 2Cores and 3GB RAM

If you need something tell me.

Good luck

**Comment by Robbt** [comment] 2017-04-03 22:34
I think this is related to our unbundling of liquidsoap #131 
I duplicated it and I got Line 8, char 34: cannot %include, file "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/library/pervasives.liq" doesn't exist.

**Comment by Robbt** [comment] 2017-04-04 00:04
You can manually remove the include on the 8th line of /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq 
delete or comment out this # %include "library/pervasives.liq"
and see if it works.

**Comment by Lapotor** [comment] 2017-04-06 16:33
This doesn't help us it still tell us that:
```heck that the airtime-liquidsoap service is installed correctly in /etc/init, and ensure that it's running with
initctl list | grep airtime-liquidsoap
If not, try
sudo service airtime-liquidsoap restart```

**Comment by hairmare** [comment] 2017-04-06 17:37
Is it logging anything in `/var/log/airtime/pypo-liquidsoap/ls_script.log` that might help?

**Comment by Lapotor** [comment] 2017-04-06 17:41
Here the LOG:

**Comment by hairmare** [comment] 2017-04-06 17:47
I think I've seen this one before, the `Source failed (no more tracks) stopping output...` line in the output looks very much like #113. Are you using a different location than `/srv/airtime` for the music dir? If so I'll seriously need to test that and figure out why it doesn't work.

**Comment by Lapotor** [comment] 2017-04-06 17:48
No i use the Default location

**Comment by hairmare** [comment] 2017-04-06 17:58
Are there any files in pypos cache at `/var/tmp/airtime/pypo/cache/scheduler`? I've also seen the error when pypo doesn't have the rights to write to the dir.

**Comment by Lapotor** [comment] 2017-04-06 18:05
No there are no files in there does the www-data need the rights or which User ? ATm the www-data user have the rights.

**Comment by hairmare** [comment] 2017-04-06 18:35
www-data is right so that isn't the issue. Is there any more output (and maybe a useful error) when you try to run it directly using `sudo -u www-data airtime-playout`?

**Comment by Lapotor** [comment] 2017-04-06 18:38
It say that Liquidsoap may not running:
```
root@airtime:~# sudo -u www-data airtime-playout
2017-04-06 20:37:54,326 [__main__] [INFO ]  New locale set to: de_DE.UTF-8
2017-04-06 20:37:54,347 [__main__] [INFO ]  ###########################################
2017-04-06 20:37:54,348 [__main__] [INFO ]  #             *** pypo  ***               #
2017-04-06 20:37:54,350 [__main__] [INFO ]  #   Liquidsoap Scheduled Playout System   #
2017-04-06 20:37:54,351 [__main__] [INFO ]  ###########################################
2017-04-06 20:37:54,352 [__main__] [INFO ]  Timezone: ('CET', 'CEST')
2017-04-06 20:37:54,352 [__main__] [INFO ]  UTC time: 2017-04-06 18:37:54.352383
2017-04-06 20:37:54,459 [api_client] [INFO ]  Airtime API version found: 1.1
2017-04-06 20:37:54,459 [api_client] [INFO ]  pypo is only compatible with API version: 1.1
2017-04-06 20:37:54,506 [__main__] [ERROR]  [Errno 111] Verbindungsaufbau abgelehnt
2017-04-06 20:37:54,506 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
2017-04-06 20:37:55,508 [__main__] [ERROR]  [Errno 111] Verbindungsaufbau abgelehnt
2017-04-06 20:37:55,509 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
2017-04-06 20:37:56,511 [__main__] [ERROR]  [Errno 111] Verbindungsaufbau abgelehnt
2017-04-06 20:37:56,512 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
2017-04-06 20:37:57,514 [__main__] [ERROR]  [Errno 111] Verbindungsaufbau abgelehnt
2017-04-06 20:37:57,515 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
2017-04-06 20:37:58,517 [__main__] [ERROR]  [Errno 111] Verbindungsaufbau abgelehnt
2017-04-06 20:37:58,518 [__main__] [WARNI]  Liquidsoap doesn't appear to be running!, Sleeping and trying again
```

**Comment by hairmare** [comment] 2017-04-06 18:50
Can you check if the ls_port from the `[pypo]` section of `/etc/airtime/airtime.conf` uses a free port? The default port it uses is 1234. Does that show up in `netstat -alntp | grep 1234`?

**Comment by Lapotor** [comment] 2017-04-06 19:20
I changed the Port to an free port but it not show up on netstat. i used 12595

**Comment by hairmare** [comment] 2017-04-06 19:28
I'm not sure if changing the port really works. Do you see what is using the port now?

**Comment by Lapotor** [comment] 2017-04-07 21:42
OK wired now it works i but it can't connect to the stream.

**Comment by Robbt** [comment] 2017-04-08 00:59
In which way can you not connect to the stream ? Does the stream show up when you go to the icecast page at http://hostname:8000 ? Or do you mean connecting to it via master or show login ?

**Comment by Lapotor** [comment] 2017-04-08 22:32
Today i reinstalled LibreTime to the newest version on **GITHUB**.
After i installed it unter `?config` it showed that everything works fine, but after i logged in and started to deactivate the Default Stream to the local Icecast after that i looked to the status Page and to `/?config` and there it saied that liquidsoap not running correctly.
We tried after we saw that on the status page to connect to an 3rd Party Stream but it doesn't work it only say `Getting information from the server...`.
Here is the log of `/var/log/airtime/pypo-liquidsoap/ls_script.log`:
```
2017/04/09 00:05:23 >>> LOG START
2017/04/09 00:05:22 [protocols.external:3] Found "/usr/bin/wget".
2017/04/09 00:05:23 [main:3] Liquidsoap 1.1.1
2017/04/09 00:05:23 [main:3] Using: graphics=[distributed with Ocaml] pcre=7.0.4 dtools=0.3.1 duppy=0.5.1 duppy.syntax=0.5.1 cry=0.2.2 mm=0.2.1 xmlplaylist=0.1.3 lastfm=0.3.0 ogg=0.4.5 vorbis=0.6.1 opus=0.1.0 speex=0.2.0 mad=0.4.4 flac=0.1.1 flac.ogg=0.1.1 dynlink=[distributed with Ocaml] lame=0.3.2 shine=0.2.0 gstreamer=0.2.0 frei0r=0.1.0 voaacenc=0.1.0 theora=0.3.0 schroedinger=0.1.0 gavl=0.1.5 bjack=0.1.4 alsa=0.2.1 ao=0.2.0 samplerate=0.1.2 taglib=0.3.1 magic=0.7.3 camomile=0.8.4 inotify=1.0 faad=0.3.2 soundtouch=0.1.7 portaudio=0.2.0 pulseaudio=0.1.2 ladspa=0.1.4 dssi=0.1.1 sdl=0.9.1 camlimages=4.0.0 lo=0.1.0 yojson=1.1.8 gd=1.0a5
2017/04/09 00:05:23 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2017/04/09 00:05:23 [dynamic.loader:3] Could not find dynamic module for aacplus encoder.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/pulseaudio.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/mad.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/ogg.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/taglib.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/faad.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac_ogg.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/lame.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/voaacenc.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/cry.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs.
2017/04/09 00:05:23 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/vorbis.cmxs.
2017/04/09 00:05:23 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2017/04/09 00:05:23 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2017/04/09 00:05:23 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2017/04/09 00:05:23 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2017/04/09 00:05:23 [lang:3] timeout --signal=KILL 45 pyponotify --liquidsoap-started &
2017/04/09 00:05:23 [threads:3] Created thread "generic queue #1".
2017/04/09 00:05:23 [threads:3] Created thread "generic queue #2".
2017/04/09 00:05:23 [threads:3] Created thread "non-blocking queue #1".
2017/04/09 00:05:23 [threads:3] Created thread "non-blocking queue #2".
2017/04/09 00:05:23 [harbor:3] Adding mountpoint '/master' on port 8001
2017/04/09 00:05:23 [harbor:3] Adding mountpoint '/show' on port 8002
2017/04/09 00:05:23 [threads:3] Created thread "http polling" (1 total).
2017/04/09 00:05:23 [airtime_128:3] Connecting mount airtime_128 for source@127.0.0.1...
2017/04/09 00:05:23 [airtime_128:3] Connection setup was successful.
2017/04/09 00:05:23 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=1 --time=1491689123.18 &
2017/04/09 00:05:23 [threads:3] Created thread "wallclock_main" (2 total).
2017/04/09 00:05:23 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2017/04/09 00:05:23 [dummy:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:23 [dummy(dot)1:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:23 [dummy(dot)2:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:23 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:23 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:23 [map_metadata_5350:3] Inserting missing metadata.
2017/04/09 00:05:23 [master_show_schedule_noise_switch:3] Switch to show_schedule_noise_switch.
2017/04/09 00:05:23 [show_schedule_noise_switch:3] Switch to schedule_noise_switch.
2017/04/09 00:05:23 [schedule_noise_switch:3] Switch to map_metadata_5350.
2017/04/09 00:05:23 [server:3] New client: localhost.
2017/04/09 00:05:23 [server:3] Client localhost disconnected.
2017/04/09 00:05:24 [server:3] New client: localhost.
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [server:3] Client localhost disconnected.
2017/04/09 00:05:24 [cross_5275:3] No next track ready yet.
2017/04/09 00:05:24 [cross_5260:3] No next track ready yet.
2017/04/09 00:05:24 [cross_5245:3] No next track ready yet.
2017/04/09 00:05:24 [cross_5230:3] No next track ready yet.
2017/04/09 00:05:24 [cross_5215:3] No next track ready yet.
2017/04/09 00:05:24 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:24 [server:3] New client: localhost.
2017/04/09 00:05:24 [lang:3] streams.scheduled_play_start
2017/04/09 00:05:24 [lang:3] streams.live_dj_stop
2017/04/09 00:05:24 [lang:3] streams.master_dj_stop
2017/04/09 00:05:24 [lang:3] vars.stream_metadata_type
2017/04/09 00:05:24 [lang:3] vars.station_name
2017/04/09 00:05:24 [lang:3] vars.default_dj_fade
2017/04/09 00:05:24 [server:3] Client localhost disconnected.
2017/04/09 00:05:24 [server:3] New client: localhost.
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [lang:3] queues.s8_skip
2017/04/09 00:05:24 [server:3] Client localhost disconnected.
2017/04/09 00:05:24 [schedule_noise_switch:3] Switch to map_metadata_5343 with transition.
2017/04/09 00:05:24 [lang:3] transition called...
2017/04/09 00:05:24 [switch_5341:3] Switch to insert_metadata_5327.
2017/04/09 00:05:24 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:24 [schedule_noise_switch:3] Switch to map_metadata_5350 with forgetful transition.
2017/04/09 00:05:24 [lang:3] transition called...
2017/04/09 00:05:24 [server:3] New client: localhost.
2017/04/09 00:05:24 [lang:3] dynamic_source.get_id
2017/04/09 00:05:24 [server:3] Client localhost disconnected.
2017/04/09 00:05:25 [server:3] New client: localhost.
2017/04/09 00:05:25 [lang:3] streams.scheduled_play_start
2017/04/09 00:05:25 [lang:3] streams.live_dj_stop
2017/04/09 00:05:25 [lang:3] streams.master_dj_stop
2017/04/09 00:05:25 [lang:3] vars.stream_metadata_type
2017/04/09 00:05:25 [lang:3] vars.station_name
2017/04/09 00:05:25 [lang:3] vars.default_dj_fade
2017/04/09 00:05:25 [server:3] Client localhost disconnected.
2017/04/09 00:05:25 [server:3] New client: localhost.
2017/04/09 00:05:25 [lang:3] queues.s8_skip
2017/04/09 00:05:25 [lang:3] queues.s8_skip
2017/04/09 00:05:25 [lang:3] queues.s8_skip
2017/04/09 00:05:25 [lang:3] queues.s8_skip
2017/04/09 00:05:25 [lang:3] queues.s8_skip
2017/04/09 00:05:25 [server:3] Client localhost disconnected.
2017/04/09 00:05:25 [server:3] New client: localhost.
2017/04/09 00:05:25 [lang:3] dynamic_source.get_id
2017/04/09 00:05:25 [server:3] Client localhost disconnected.
2017/04/09 00:05:25 [schedule_noise_switch:3] Switch to map_metadata_5343 with transition.
2017/04/09 00:05:25 [lang:3] transition called...
2017/04/09 00:05:25 [switch_5341:3] Switch to insert_metadata_5327.
2017/04/09 00:05:25 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/04/09 00:05:25 [schedule_noise_switch:3] Switch to map_metadata_5350 with forgetful transition.
2017/04/09 00:05:25 [lang:3] transition called...
2017/04/09 00:07:55 [server:3] New client: localhost.
2017/04/09 00:07:55 [lang:3] vars.station_name
2017/04/09 00:07:55 [server:3] Client localhost disconnected.
2017/04/09 00:08:29 [server:3] New client: localhost.
2017/04/09 00:08:29 [lang:3] vars.stream_metadata_type
2017/04/09 00:08:29 [server:3] Client localhost disconnected.
2017/04/09 00:08:30 [server:3] New client: localhost.
2017/04/09 00:08:30 [lang:3] vars.default_dj_fade
2017/04/09 00:08:30 [server:3] Client localhost disconnected.
```

**Comment by Robbt** [comment] 2017-04-08 23:05
Ok, thanks for documenting the steps you took. Airtime-liquidsoap will fail if you don't have correct information in the stream etc. So when you disabled the default stream it makes sense that it was failing.
Now getting it to connect to external ice or shoutcast servers isn't something I've fully tested yet. Let me test and see if I can get the liquidsoap to connect to a 3rd party streaming provider.

**Comment by Lapotor** [comment] 2017-04-08 23:36
ok after that waht you said i tried to let it connect to stream, so i put in data for an 3rd Party Stream and restarted liquidsoap now it say me it is connected to the stream .. it should send silence, but it don't do it.
And on the sttus page it say that it is not working too.
Here the log:
```
2017/04/09 01:24:32 >>> LOG START
2017/04/09 01:24:32 [protocols.external:3] Found "/usr/bin/wget".
2017/04/09 01:24:32 [main:3] Liquidsoap 1.1.1
2017/04/09 01:24:32 [main:3] Using: graphics=[distributed with Ocaml] pcre=7.0.4 dtools=0.3.1 duppy=0.5.1 duppy.syntax=0.5.1 cry=0.2.2 mm=0.2.1 xmlplaylist=0.1.3 lastfm=0.3.0 ogg=0.4.5 vorbis=0.6.1 opus=0.1.0 speex=0.2.0 mad=0.4.4 flac=0.1.1 flac.ogg=0.1.1 dynlink=[distributed with Ocaml] lame=0.3.2 shine=0.2.0 gstreamer=0.2.0 frei0r=0.1.0 voaacenc=0.1.0 theora=0.3.0 schroedinger=0.1.0 gavl=0.1.5 bjack=0.1.4 alsa=0.2.1 ao=0.2.0 samplerate=0.1.2 taglib=0.3.1 magic=0.7.3 camomile=0.8.4 inotify=1.0 faad=0.3.2 soundtouch=0.1.7 portaudio=0.2.0 pulseaudio=0.1.2 ladspa=0.1.4 dssi=0.1.1 sdl=0.9.1 camlimages=4.0.0 lo=0.1.0 yojson=1.1.8 gd=1.0a5
2017/04/09 01:24:32 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2017/04/09 01:24:32 [dynamic.loader:3] Could not find dynamic module for aacplus encoder.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/pulseaudio.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/mad.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/ogg.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/taglib.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/faad.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac_ogg.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/lame.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/voaacenc.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/cry.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs.
2017/04/09 01:24:32 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/vorbis.cmxs.
2017/04/09 01:24:32 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2017/04/09 01:24:32 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2017/04/09 01:24:32 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2017/04/09 01:24:32 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2017/04/09 01:24:32 [lang:3] timeout --signal=KILL 45 pyponotify --liquidsoap-started &
2017/04/09 01:24:32 [threads:3] Created thread "generic queue #1".
2017/04/09 01:24:32 [threads:3] Created thread "generic queue #2".
2017/04/09 01:24:32 [threads:3] Created thread "non-blocking queue #1".
2017/04/09 01:24:32 [threads:3] Created thread "non-blocking queue #2".
2017/04/09 01:24:32 [harbor:3] Adding mountpoint '/master' on port 8001
2017/04/09 01:24:32 [harbor:3] Adding mountpoint '/show' on port 8002
2017/04/09 01:24:32 [threads:3] Created thread "http polling" (1 total).
2017/04/09 01:24:32 [hitmix(dot)live:3] Connecting mount hitmix.live for source@live.laut.fm...
2017/04/09 01:24:33 [hitmix(dot)live:3] Connection setup was successful.
2017/04/09 01:24:33 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=2 --time=1491693872.9 &
2017/04/09 01:24:33 [threads:3] Created thread "wallclock_main" (2 total).
2017/04/09 01:24:33 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2017/04/09 01:24:33 [dummy:3] Source failed (no more tracks) stopping output...
2017/04/09 01:24:33 [dummy(dot)1:3] Source failed (no more tracks) stopping output...
2017/04/09 01:24:33 [dummy(dot)2:3] Source failed (no more tracks) stopping output...
2017/04/09 01:24:33 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2017/04/09 01:24:33 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2017/04/09 01:24:33 [map_metadata_5350:3] Inserting missing metadata.
2017/04/09 01:24:33 [master_show_schedule_noise_switch:3] Switch to show_schedule_noise_switch.
2017/04/09 01:24:33 [show_schedule_noise_switch:3] Switch to schedule_noise_switch.
2017/04/09 01:24:33 [schedule_noise_switch:3] Switch to map_metadata_5350.
2017/04/09 01:24:33 [server:3] New client: localhost.
2017/04/09 01:24:33 [server:3] Client localhost disconnected.
2017/04/09 01:24:33 [server:3] New client: localhost.
2017/04/09 01:24:33 [lang:3] vars.bootup_time
2017/04/09 01:24:33 [lang:3] streams.connection_status
2017/04/09 01:24:33 [server:3] Client localhost disconnected.
2017/04/09 01:24:33 [server:3] New client: localhost.
2017/04/09 01:24:33 [lang:3] vars.stream_metadata_type
2017/04/09 01:24:33 [server:3] Client localhost disconnected.
2017/04/09 01:24:33 [server:3] New client: localhost.
2017/04/09 01:24:33 [lang:3] vars.default_dj_fade
2017/04/09 01:24:33 [server:3] Client localhost disconnected.
```

**Comment by Robbt** [comment] 2017-04-08 23:54
I guess the next question is when it says it is connected does the icecast stream show up on the icecast page (assuming you are using icecast) ? This is generally port :8000. It also might not be streaming because you aren't broadcasting anything, ie it doesn't connect to stream silence.

**Comment by Lapotor** [comment] 2017-04-09 00:04
I think that it is not showing up:
![grafik](https://cloud.githubusercontent.com/assets/17144397/24833447/c7b65c98-1cc8-11e7-8b4c-36cfa2f1f242.png)
![grafik](https://cloud.githubusercontent.com/assets/17144397/24833448/d6f062a8-1cc8-11e7-8b27-bb641b2f3c52.png)

**Comment by Robbt** [comment] 2017-04-09 00:21
I will play around with this when I get a chance and look at the code if I can recreate the issue. Did you try scheduling tracks to see if that made any difference ?

**Comment by Lapotor** [comment] 2017-04-09 00:24
i can't see #145

**Comment by Lapotor** [comment] 2017-04-10 10:20
so #145 is solved yet we can work here

**Comment by Lapotor** [comment] 2017-04-11 14:30
ok on install on Ubuntu 16.04 and Debian 8.7 i get when i started liquidsoap this with status:
```
root@libretime:~/libretime# service airtime-liquidsoap start
airtime-liquidsoap start/running, process 27692
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/running, process 27704
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27717
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27717
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27717
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/running, process 27742
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27758
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27758
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27758
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/running, process 27783
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27796
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27796
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27796
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27796
root@libretime:~/libretime# service airtime-liquidsoap status
airtime-liquidsoap start/post-stop, process 27835
```

**Comment by Robbt** [comment] 2017-04-11 17:33
hmm, it looks like it should be working. I was trying to replicate and ran into some issues.
If you type `sudo -u www-data airtime-liquidsoap `
into the terminal while sshed into the machine what happens ?

**Comment by Lapotor** [comment] 2017-04-11 21:33
This appers:
```
root@libretime:~# sudo -u www-data airtime-liquidsoap
Airtime Liquidsoap
Unable to connect to the Airtime server.
<urlopen error [Errno 111] Connection refused>
traceback: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liq                                                                                                                                                             uidsoap/generate_liquidsoap_cfg.py", line 48, in run
    ss = ac.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_cli                                                                                                                                                             ents/api_client.py", line 470, in get_stream_setting
    return self.services.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_cli                                                                                                                                                             ents/api_client.py", line 145, in __call__
    f = urllib2.urlopen(req, timeout=ApiRequest.API_HTTP_REQUEST_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
...
```

**Comment by Robbt** [comment] 2017-04-12 02:15
This looks like it is the root cause. I wonder what is happening with the URL that it can't access it,

**Comment by hairmare** [comment] 2017-04-15 21:38
I have an idea where this might be coming form. Can you access the URL directly on the box?

It should look something like `http://<host-from-conf>:<port-from-conf>/api/get-stream-setting/format/json/api_key/<api_key-from-conf>`. 

Can you access that it without errors using `curl -vvv` or something similar on the boxes CLI? If you can't access it maybe your host is not allowing internal access to your external ip. A split DNS hack with `127.0.0.1 <host-from-conf>` in `/etc/resolv.conf` might allow resolving it in that case.

**Comment by Lapotor** [comment] 2017-04-15 23:22
Will test on Tuesday.

**Comment by Lapotor** [comment] 2017-04-20 16:07
Will update on Ubuntu 16.04 now.

**Comment by Lapotor** [comment] 2017-04-20 16:48
OK on 16.04 liquidsoap working fine

**Closed** 2017-04-20 16:58 UTC

**Comment by Lapotor** [comment] 2017-04-20 17:01
only stopping when disabling source
