### ISSUE TITLE
Option to add local media folder?

### ISSUE THREAD

**Issue by KipourosV** [LibreTime/libretime#457] opened 2018-03-04 20:30 UTC
Been reading the watch folder feature has been removed.
Any news on this?

**Comment by tuktukvlad** [comment] 2018-03-05 18:37
To mount from different partitions I use https://romanrm.net/mhddfs
Maybe this will help you

**Comment by KipourosV** [comment] 2018-03-05 20:45
I know the tool but it's not helpfull in my case.

I 'm running Libretime in an LXC container on a Proxmox host,
with ZFS underlying storage and a bind mount on the container.
I have a 4T music library already on that storage, and I want to access
that library in Libretime without having to "upload it" (duplicate).

"airtime-import copy" (which is referenced in docs, is nowhere to be found in Libretime. No?)
would potentially help. I would just copy the library to Libretime and then delete the source
files but then again I have a nicely sorted collection that I wouldn't mess-up...

The upload is ok as a feature, but local library folders are a must (i think. No?)
What happens with people that need to change host? Or redeploy because of failure?
Do they need to reupload all the content?

**Comment by hairmare** [comment] 2018-03-06 19:55
Duplicates #70 

The watched folder feature was already missing when we took over.

Sadly we don't have any news on re-implementing the watched folder. It's still on the agenda as it's a killer feature for a lot of legacy upstream users.

Some initial work was done in #111 so you might want to look there if you want to take the torch and help re-implement the feature.

**Comment by Robbt** [comment] 2018-09-08 15:42
So I'm working on implementing #111 and the issue is that automatic import of files in a folder is a somewhat different feature than linking to existing files/folders like the original watch feature did. 

It should be relatively straight forward to implement automatic importing of files using the existing rest/media API (I've already written the code on a branch) but it will take a little bit more time to implement a watched folder functionality because of the need to alter or duplicate the current media import process to sideload content.

**Comment by Robbt** [comment] 2018-12-04 10:44
I'm going to close this as a duplicate of #70 
It brings up the valid point that people have well-organized folders of music that they don't want to duplicate to include LibreTime but also could be solved by an import/export functionality for tracks.

**Closed by Robbt** 2018-12-04 10:44 UTC
Labels: feature-request
