### ISSUE TITLE
Problem: Apache error 500 in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by solohtml** [LibreTime/libretime#634] opened 2018-12-11 09:10 UTC
Hi folks, after installing LibreTime git version in my Virtualbox VM, I could access to final configuration, and all services seems to be working ok... So strange at first time in my earlier installs (16.04, Debian 9, ...)
BUT, then... Error 500 in my Apache server. and no log accesible...
Holly molly... Maybe my Apache is broken? I don't know...
Previous to the git installation I reviewed wiki pages and add PHP ppa's but triying without it error is the same...
what am I doing bad?

**Comment by JohnnyC1951** [comment] 2018-12-11 09:38
Is there nothing in /varlog/apache2/error.log at all?
It sounds like you may have an apache module missing

**Comment by Robbt** [comment] 2018-12-11 11:01
I'd suggest using 16.04 as we can't support 18.04 (see #580). Type php --version from the command line and see if you are using Php 7.0 or 7.1. The advice JohnnyC provides is good but since this is a support request for an unsupported version of Ubuntu I'm going to suggest that we close this issue and follow up on any conversation on the forum.

**Comment by solohtml** [comment] 2018-12-11 11:46
Oh dear! At least now i have a logfile... Not corrected 500 error but maybe a million of errors at the same point. 
![image](https://user-images.githubusercontent.com/3239523/49798502-4d343e00-fd3a-11e8-8167-ff5f62c0e7cf.png)
I don't know... Better I wayback to 16.04 OS...

**Comment by JohnnyC1951** [comment] 2018-12-11 11:48
Rerunning the install just might work

**Comment by solohtml** [comment] 2018-12-11 11:50
> Rerunning the install just might work

I doubt it, it reinstalls PHP 7.2 ... Better 16.04 i think...

**Comment by Robbt** [comment] 2018-12-11 13:17
Yeah good point, we can modify the install for 18.04 to include PHP 7.0 vs. 7.2. And if you want to run 18.04 you can manually uninstall 7.3 and install 7.0 If you do this it should work but I can't provide exact steps. 

If you use the command `dpkg -l | grep 'php' ` and then `sudo apt remove PACKAGENAME` for every php7.2 or php7.3 version installed and then `sudo apt install libapache2-mod-php7.0 php7.0 php-pear php7.0-gd php7.0-bcmath php7.0-mbstring php7.0-pgsql php7.0-curl php7.0-apcu` it should work. My guess is that even though you installed the alternate php version it still had the older ones.

If you want to work on a PR for the install script specific to 18.04 we could help people who go down this route in the future avoid the same problem. Otherwise it'll have to wait until someone has the time. 

It might also be important to do something like a PIN for version php7.0 to avoid upgrades in the future although I'm not sure. If it isn't too much trouble using 16.04 is probably a better idea until we do a transition to a new MVC but that could be a way off.

**Comment by Robbt** [comment] 2018-12-12 21:42
Closing this as it's a duplicate of #580

**Closed by Robbt** 2018-12-12 21:42 UTC
