### ISSUE TITLE
Fix documentation broken links

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1265] opened 2021-07-07 11:14 UTC
Since the documentation has been rewritten, many links are broken, and doesn't redirect to the proper new guide or alternative.

Additionally it seems some guides have been lost in the process.

Not really a problem, but should be noted, all these broken links are a big problem concerning SEO, since google will rank the website as broken with that many 404 on previous indexed links.

I propose to build a list of page from the previous documentation and try to map to the new documentation. This will let us redirect user to the new pages automatically.

**Comment by paddatrapper** [comment] 2021-07-07 14:17
Duplicate of #1220

**Closed by paddatrapper** 2021-07-07 14:17 UTC
Labels: bug
