### ISSUE TITLE
Flac preview doesn't work

### ISSUE THREAD

**Issue by ToneLune** [libretime/libretime#2867] opened 2024-01-02 22:25 UTC
### Describe the bug

Hello,

Audio files with .flac extension doesn't load in admin panel.

### To reproduce

1. Go to Tracks
2. Click on the headphones to preview a .flac files
3. Click on play
4. Nothing

### Expected behavior

It must play audio tracks !

.mp3 working like expected, and IceCast can play .flac audio files during a show.

### LibreTime version

3.1.0

### Installation method and OS / Environment

Operating system: Debian Bullseye
Method: Installer script

### Client Environment

Operating system: Windows 10
Browser: Firefox 121

**Comment by jooola** [comment] 2024-01-07 15:19
Duplicate of https://github.com/libretime/libretime/issues/509

**Closed by jooola** 2024-01-07 15:19 UTC
Labels: is: bug
