### ISSUE TITLE
[Ubuntu 16.04.2] Don't Connect to 3rd Party Ic2 Stream

### ISSUE THREAD

**Issue by Lapotor** [LibreTime/libretime#176] opened 2017-04-20 18:07 UTC
I tried to connect LibreTime to an 3rd Party Stream (done that with an Liquidsoap restart) but it show it get connected but it isn't connected.

---
_error.log_:
```
[2017-04-20  18:23:52] INFO main/main Icecast 2.4.2 server started
[2017-04-20  18:23:52] INFO connection/get_ssl_certificate No SSL capability
[2017-04-20  18:23:52] INFO stats/_stats_thread stats thread started
[2017-04-20  18:23:52] INFO yp/yp_update_thread YP update thread started
[2017-04-20  18:31:19] INFO connection/_handle_source_request Source logging in at mountpoint "/airtime_128" from 127.0.0.1
[2017-04-20  18:31:19] INFO format-vorbis/initial_vorbis_page seen initial vorbis header
[2017-04-20  18:31:19] INFO source/source_main listener count on /airtime_128 now 0
[2017-04-20  18:31:20] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:33:20] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:35:20] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:37:21] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:39:21] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:41:21] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:43:21] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:45:21] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:47:21] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:49:22] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:51:22] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:53:22] INFO admin/admin_handle_request Bad or missing password on admin command request (command: stats.xml)
[2017-04-20  18:55:05] INFO source/get_next_buffer End of Stream /airtime_128
[2017-04-20  18:55:05] INFO source/source_shutdown Source from 127.0.0.1 at "/airtime_128" exiting
[2017-04-20  19:18:01] INFO sighandler/_sig_die Caught signal 15, shutting down...
[2017-04-20  19:18:01] INFO main/main Shutting down
[2017-04-20  19:18:01] INFO fserve/fserve_shutdown file serving stopped
[2017-04-20  19:18:01] INFO slave/_slave_thread shutting down current relays
[2017-04-20  19:18:01] INFO slave/_slave_thread Slave thread shutdown complete
[2017-04-20  19:18:01] INFO auth/auth_shutdown Auth shutdown
[2017-04-20  19:18:01] INFO yp/yp_shutdown YP thread down
[2017-04-20  19:18:02] INFO stats/stats_shutdown stats thread finished
[2017-04-20  19:18:02] INFO main/main Icecast 2.4.2 server started
[2017-04-20  19:18:02] INFO yp/yp_update_thread YP update thread started
[2017-04-20  19:18:02] INFO connection/get_ssl_certificate No SSL capability
[2017-04-20  19:19:14] INFO connection/_handle_source_request Source logging in at mountpoint "/master" from ***MY-IP***
[2017-04-20  19:19:14] INFO connection/_handle_source_request Source (/master) attempted to login with invalid or missing password
[2017-04-20  19:19:15] INFO connection/_handle_source_request Source logging in at mountpoint "/master" from ***MY-IP***
[2017-04-20  19:19:15] WARN format/format_get_type Unsupported or legacy stream type: "audio/mpeg". Falling back to generic minimal handler for best effort.
[2017-04-20  19:19:16] INFO source/source_main listener count on /master now 0
[2017-04-20  19:25:46] INFO fserve/fserve_client_create checking for file /style.css (/usr/share/icecast2/web/style.css)
[2017-04-20  19:25:46] INFO fserve/fserve_client_create checking for file /icecast.png (/usr/share/icecast2/web/icecast.png)
[2017-04-20  19:25:46] INFO fserve/fserve_client_create checking for file /tunein.png (/usr/share/icecast2/web/tunein.png)
[2017-04-20  19:25:46] INFO fserve/fserve_client_create checking for file /favicon.ico (/usr/share/icecast2/web/favicon.ico)
[2017-04-20  19:25:46] WARN fserve/fserve_client_create req for file "/usr/share/icecast2/web/favicon.ico" No such file or directory
[2017-04-20  19:25:46] INFO fserve/fserve_client_create checking for file /favicon.ico (/usr/share/icecast2/web/favicon.ico)
[2017-04-20  19:25:46] WARN fserve/fserve_client_create req for file "/usr/share/icecast2/web/favicon.ico" No such file or directory
[2017-04-20  19:25:53] INFO admin/admin_handle_request Bad or missing password on admin command request (command: )
[2017-04-20  19:26:00] INFO fserve/fserve_client_create checking for file /style.css (/usr/share/icecast2/web/style.css)
[2017-04-20  19:26:00] INFO fserve/fserve_client_create checking for file /tunein.png (/usr/share/icecast2/web/tunein.png)
[2017-04-20  19:27:03] INFO source/get_next_buffer End of Stream /master
[2017-04-20  19:27:03] INFO source/source_shutdown Source from ***MY-IP*** at "/master" exiting
[2017-04-20  19:28:21] INFO connection/_handle_source_request Source logging in at mountpoint "/master" from ***MY-IP***
[2017-04-20  19:28:21] WARN format/format_get_type Unsupported or legacy stream type: "audio/mpeg". Falling back to generic minimal handler for best effort.
[2017-04-20  19:28:21] INFO source/source_main listener count on /master now 0
[2017-04-20  19:28:53] INFO source/get_next_buffer End of Stream /master
[2017-04-20  19:28:53] INFO source/source_shutdown Source from ***MY-IP*** at "/master" exiting
[2017-04-20  19:29:22] INFO fserve/fserve_client_create checking for file /style.css (/usr/share/icecast2/web/style.css)
```
_access.log_:
```
127.0.0.1 - - [20/Apr/2017:18:31:20 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:33:20 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:35:20 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:37:21 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:39:21 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:41:21 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:43:21 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:45:21 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:47:21 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:49:22 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:51:22 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:53:22 +0200] "GET /admin/stats.xml HTTP/1.1" 401 331 "-" "Python-urllib/2.7" 0
127.0.0.1 - - [20/Apr/2017:18:55:05 +0200] "SOURCE /airtime_128 HTTP/1.0" 200 19 "-" "Liquidsoap/1.1.1 (Unix; OCaml 4.02.3)" 1426
***MY-IP*** - - [20/Apr/2017:19:19:14 +0200] "SOURCE /master HTTP/1.0" 401 331 "-" "libshout/2.4.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:46 +0200] "GET / HTTP/1.1" 200 2470 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:46 +0200] "GET /style.css HTTP/1.1" 200 4141 "http://sub.domain.net:8001/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:46 +0200] "GET /icecast.png HTTP/1.1" 200 4245 "http://sub.domain.net:8001/style.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:46 +0200] "GET /tunein.png HTTP/1.1" 200 1934 "http://sub.domain.net:8001/style.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:46 +0200] "GET /favicon.ico HTTP/1.1" 404 365 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:46 +0200] "GET /favicon.ico HTTP/1.1" 404 365 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:25:53 +0200] "GET /admin/ HTTP/1.1" 401 331 "http://sub.domain.net:8001/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 2
***MY-IP*** - - [20/Apr/2017:19:26:00 +0200] "GET /admin/ HTTP/1.1" 200 6227 "http://sub.domain.net:8001/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:26:00 +0200] "GET /style.css HTTP/1.1" 200 4141 "http://sub.domain.net:8001/admin/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:26:00 +0200] "GET /tunein.png HTTP/1.1" 200 1934 "http://sub.domain.net:8001/style.css" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
***MY-IP*** - - [20/Apr/2017:19:27:03 +0200] "SOURCE /master HTTP/1.0" 200 19 "-" "libshout/2.4.0" 468
***MY-IP*** - - [20/Apr/2017:19:28:53 +0200] "SOURCE /master HTTP/1.0" 200 19 "-" "libshout/2.4.0" 33
***MY-IP*** - - [20/Apr/2017:19:29:22 +0200] "GET /admin/stats.xsl HTTP/1.1" 200 3080 "http://sub.domain.net:8001/admin/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 1
***MY-IP*** - - [20/Apr/2017:19:29:22 +0200] "GET /style.css HTTP/1.1" 200 4141 "http://sub.domain.net:8001/admin/stats.xsl" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0" 0
```
---
Did not autofill the 'Live Broadcasting' section.

**Comment by hairmare** [comment] 2017-04-20 18:23
Could you check if airtime-liquidsoap tells us more? The following should output lots of info. 

```bash
systemctl stop airtime-liquidsoap
sudo -u www-data airtime-liquidsoap --debug
```

**Comment by Lapotor** [comment] 2017-04-20 18:38
Sure: https://pastebin.com/p8DyG1hK

**Comment by hairmare** [comment] 2017-04-21 01:11
That looks like a liquidsoap log. Is there any output from python itself?

I see one `Error when starting dummy: Address already in use in bind()!` line in the output. Can you check that the airtime-liquidsoap process isn'r running before you `sudo -u www-data airtime-liquidsoap --debug `.

**Comment by Lapotor** [comment] 2017-04-22 14:31
[liquidsoap debug.txt](https://github.com/LibreTime/libretime/files/949033/liquidsoap.debug.txt)

No process started and that is the output.

**Comment by hairmare** [comment] 2017-04-22 14:40
I see, the pastebin link seems to have the same output the txt has at a different position but looks like it is the same.

The `WARN format/format_get_type Unsupported or legacy stream type: "audio/mpeg". Falling back to generic minimal handler for best effort.` warning in the icecast log looks quite weird. I'll have to do some testing to see if I can figure out if I can reproduce it and where it is from. 

The 401 header from the `SOURCE /master` requests seems to indicate a username/password problem. You might need to set this up in icecast's config. If none is set in icecast it could make sense to specify `source` as the username.

**Comment by Lapotor** [comment] 2017-04-28 08:58
rgr will test report back when need something from my side ?

**Comment by hairmare** [comment] 2017-10-07 13:04
Are you by any chance using butt to stream if so this might be the same issue as in #160.

**Comment by Robbt** [comment] 2018-10-21 20:46
I'm going to close this because it is more of a support request, there are no steps to reproduce it and the original poster doesn't appear have posted any more information regarding the status. As far as I know 3rd party streaming with Icecast is working for most installs.

**Closed by Robbt** 2018-10-21 20:46 UTC
Labels: liquidsoap
