### ISSUE TITLE
libretime + nginx (ssl) - player (internal +home page) don't work

### ISSUE THREAD

**Issue by chicco64** [LibreTime/libretime#1316] opened 2021-08-31 15:17 UTC
I set up a proxy (nginx) for web port (80) and icecast port (8000).
Libretime features are all satisfied, except the audio players (monitor and the welcome page), I think because they are trying to play the original stream "http" (not compatible in to https website).
I ask you if you can manually change the configuration of the two players indicated, or remove "http" in "https".
Thank you.
<img width="312" alt="Capture1" src="https://user-images.githubusercontent.com/59960414/131529581-33d075ee-7bff-4c33-94a5-c457bae996d4.PNG">
<img width="625" alt="Capture2" src="https://user-images.githubusercontent.com/59960414/131529593-786981f1-f9e5-4a41-9f7f-6f14e7e6066f.PNG">

**Comment by jooola** [comment] 2021-08-31 15:39
If I understand your question, the URL of the streams can be set in the settings page.
But we might need more details to give your a proper answer

**Comment by chicco64** [comment] 2021-08-31 17:45
Hi !
from the control panel it is not possible to change the nature of the stream (from http to https) or to insert both
<img width="840" alt="Capture8" src="https://user-images.githubusercontent.com/59960414/131550923-f24f73aa-eac3-429b-b47a-c0a71c2cf0ee.PNG">

**Comment by jooola** [comment] 2021-09-01 13:16
Duplicate of #513

**Closed** 2021-09-01 13:26 UTC
Labels: bug
