### ISSUE TITLE
Problem: When opening Calendar i got empty page

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#127] opened 2017-03-26 09:52 UTC
I got this issue for a long time, but maybe there is a way to fix it?
If i push on left/right arrows it is showing well. So unless i push on arrows it is not showing.
![screen shot 2017-03-26 at 12 49 46](https://cloud.githubusercontent.com/assets/25418594/24330256/21f5b4f2-1223-11e7-9889-45cb6d667405.png)

**Comment by hairmare** [comment] 2017-03-26 10:08
This is weird. 

Is an error getting logged in the browsers developer console (<kbd>Cmd+Alt+I</kbd> on OSX Chrome)?

**Comment by korotkov13** [comment] 2017-03-26 13:43
Unfortunately I do not see any suspicious errors there, more precisely there is a lot of data, but what exactly are connected with this error I can not say.

**Comment by korotkov13** [comment] 2017-03-26 13:44
Is it just in my case? Or more global problem?

**Comment by hairmare** [comment] 2017-03-26 14:24
I can't reproduce it. FWIW the Console tab in my Developer Tools is empty when I load the calendar:

![screen shot 2017-03-26 at 16 23 28](https://cloud.githubusercontent.com/assets/116588/24332079/9d5863ca-1240-11e7-8e1d-21814ddbb8fd.png)


Maybe there is something hiding in the output.

**Comment by korotkov13** [comment] 2017-03-26 14:47
![screen shot 2017-03-26 at 17 46 19](https://cloud.githubusercontent.com/assets/25418594/24332265/3cd4877a-124c-11e7-9a65-50babe3ccc55.png)
It's empty too.

**Comment by korotkov13** [comment] 2017-03-26 16:34
Also want to add, that It happens in all browsers, windows/mac. 
Actually I think it can be something on server side. (php/apache configs). I'm not sure. If anyone has the same issue, we can find what causing it, but if it only on my system(vps, ubuntu 14.04). then better ignore it.

**Comment by hairmare** [comment] 2017-03-28 10:37
Let's try another round of github roundtrip debugging 😛 

When you switch to the network tab in the developer console and reload the page it should log all the requests that are made to the backend.

![screen shot 2017-03-28 at 12 33 07](https://cloud.githubusercontent.com/assets/116588/24401049/0ded36ce-13b3-11e7-912f-7b9ff3082b95.png)


Are there any requests in the output that have a number in the status column starting with either 4 or 5? If there are any, you can right click them and "Open in New Tab". Maybe the error will show up in the new tab.

**Comment by korotkov13** [comment] 2017-03-28 11:05
Hmmm! I think it was my system bug. I restarted today my macbook and everything is fine now.
But the strange thing is that i tried to open that page in parallels windows vm it has the same bug.
It's ok now.
I will report if it will happen again.
Thanks for helping!:)

**Comment by hairmare** [comment] 2017-03-28 11:31
Could also have been a cache issue. I'm closing for now.

**Closed by hairmare** 2017-03-28 11:31 UTC
Labels: bug
