### ISSUE TITLE
Problem: Changing the admin's password causes the auto playlist function to fail.

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#103] opened 2017-03-20 20:23 UTC
I found bug. If I change admin's password, the autoplaylist stops working and refers to an access permission error.

PHP Fatal error: Call to a member function canSchedule () on a non-object in /usr/share/airtime/php/airtime_mvc/application/models/Scheduler.php on line 142 , referer: http://mysite.domain/schedule
Found a link to errors in Apache2 logs

zendpho.log shows

[Logging.php:166 - loggingShutdownCallback()] - Call to a member function canSchedule() on a non-object at /usr/share/airtime/php/airtime_mvc/application/models/Scheduler.php:142
array (
'type' => 1,
'message' => 'Call to a member function canSchedule() on a non-object',
'file' => '/usr/share/airtime/php/airtime_mvc/application/models/Scheduler.php',
'line' => 142,

After changing password back to admin, it's working again

created new admin user and it works

**Comment by korotkov13** [comment] 2017-03-20 20:25
sorry for off-top, but I also found that silan doesn't work properly on ubuntu 14.04.

**Comment by hairmare** [comment] 2017-03-20 20:37
silan was fixed in 0.3.3 as described here: https://github.com/x42/silan/issues/3#issuecomment-279985845, this bug report tracks getting the bump into debian [debian#855319](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855319).

I wasn't sure that the hardcoded password was really being used as such, I'll try getting rid of it, maybe the dj can use the api_key or I can figure out how to let it run w/o a session.

**Comment by squiggleuk** [comment] 2017-03-20 20:37
I can also confirm this one...Ubuntu 14.04.5 LTS
Was from a git clone and ./install (after an apt-get update && apt-get upgrade)

Let me know if I can provide useful logs etc

**Comment by Robbt** [comment] 2017-03-21 16:21
Ohh wow, yeah it turns out the way I coded this was really hacky. It definitely needs to be refactored. Thanks for finding this bug. Evidently the issue is with the     public static function loginUser() function.

**Comment by Robbt** [comment] 2017-03-21 18:03
Actually I think the build_playlist has a unused parameter to checkUserPermissions that I set to false. If we implement this checkparameter I think it will bypass the authentication requirement.

**Comment by Robbt** [comment] 2017-03-21 19:12
Ok, I think this PR fixes the issue, at least on my test environment.

**Comment by korotkov13** [comment] 2017-03-21 19:14
How can I check it?

**Comment by Robbt** [comment] 2017-03-21 19:17
If you type in these commands in your github cloned libretime directory it should pull the PR and apply it
git checkout -b Robbt-fix/auto-playlist-validation master
git pull https://github.com/Robbt/libretime.git fix/auto-playlist-validation

Not sure how you have it set-up, but that should work instantly if you are using vagrant, or if you copy the files into your installed airtime_mvc directory.

**Comment by korotkov13** [comment] 2017-03-21 19:18
@Robbt Thanks

**Closed** 2017-03-23 09:59 UTC
