### ISSUE TITLE
Please help - track song at half of its total time

### ISSUE THREAD

**Issue by monomusika** [LibreTime/libretime#927] opened 2019-12-13 03:17 UTC
Hello Word!
today finally after several days struggling install libretime in a vps instance in Google cloud.  the system has been running but when it comes to uploading the music tracks, I upload them to half the time value of what each track should sound ... that is, if a music track has a total duration of 02:50 minutes  leave at 01:25 or less.  I don't really know how to solve this.  I do not find much support in Spanish so I have been solving as I could, in addition to being quite novice in Linux so installing everything has taken me a long time.

could someone help me solve this problem?  I leave photos of the example

1 ando 2nd photo 
You see the problem of cutting my music tracks in half or less.

3rd picture can be seen above indicated what the song lasts when I give the option "view" (0:02:15) and below how the song appears with duration of 01: 05.5

![aviary-image-1576206070035](https://user-images.githubusercontent.com/58057788/70766602-272ee880-1d56-11ea-9f11-085eb5af1393.jpeg)
![aviary-image-1576205933466](https://user-images.githubusercontent.com/58057788/70766604-27c77f00-1d56-11ea-92d0-cec73f6b593d.jpeg)
![aviary-image-1576205986004](https://user-images.githubusercontent.com/58057788/70766605-27c77f00-1d56-11ea-986d-8768593a4a05.jpeg)

**Comment by Robbt** [comment] 2019-12-14 13:03
I suspect you are running into the outdated silan issue - see https://github.com/LibreTime/libretime/releases#issues-silan-3.0.0-alpha.9 and see if that fixes it.

**Comment by monomusika** [comment] 2019-12-19 17:51
> I suspect you are running into the outdated silan issue - see https://github.com/LibreTime/libretime/releases#issues-silan-3.0.0-alpha.9 and see if that fixes it.
and how to fix it?
Thanks u

**Comment by Robbt** [comment] 2019-12-28 14:15
@monomusika You need to install a updated version of silan and then reimport the tracks. I think that someone wrote a script to automate this but I couldn't find it. I'm going to close this as a duplicate of #552 - feel free to follow up there or on the forum if you need more help implementing the fix.

**Closed by Robbt** 2019-12-28 14:15 UTC
Labels: bug
