### ISSUE TITLE
Install failed due to mutagen 1.44 requiring Python3

### ISSUE THREAD

**Issue by pgodel** [LibreTime/libretime#983] opened 2020-03-21 20:32 UTC
Hi,

I just went through the install for aplha8 and had to edit python_apps/airtime_analyzer/setup.py and set mutagen==1.43.0 as 1.44 does not support python2 anymore.

Hope this helps someone.

**Comment by paddatrapper** [comment] 2020-03-23 08:07
Duplicate of #959, fixed in #960

**Closed by paddatrapper** 2020-03-23 08:07 UTC
