### ISSUE TITLE
Login Git 10/11/19: OOPS something went wrong

### ISSUE THREAD

**Issue by OliCat** [LibreTime/libretime#914] opened 2019-11-13 13:38 UTC
**Bug description:**

After clean install, login with default user & pass (admin) results in "OOPS something went wrong" page.

**To Reproduce**

    Clean OS install, fully upgraded, clone from github, install with ./install,
    Open server URL in Chrome browser, see generic page,
    Click "login" (top-right),
    Enter username & password --> error page.

**LibreTime version:**
GIT clone (10/11/19)
Installation method:

    OS: Debian Stretch
    Method: ./install after clone from github
    Details:

    OS: MacOS 10.13
    Browser: Firefox / Safari / Chrome Last version

**Additional context**
Libretime was installed on LXC behind Nginx

On front page: Nginx Log (reverse proxy):
```
xx.xx.xx.xx - - [13/Nov/2019:13:31:36 +0100] "GET /api/live-info?callback=jQuery1102028811697630703637_1573648042287&type=interval&limit=5&_=1573648042288 HTTP/1.1" 500 410 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
xx.xx.xx.xx - - [13/Nov/2019:13:31:39 +0100] "GET /api/live-info?callback=jQuery1102028811697630703637_1573648042289&type=interval&limit=5&_=1573648042290 HTTP/1.1" 500 410 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
xx.xx.xx.xx - - [13/Nov/2019:13:31:42 +0100] "GET /api/live-info?callback=jQuery1102028811697630703637_1573648042291&type=interval&limit=5&_=1573648042292 HTTP/1.1" 500 410 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
```
On front page zendphp.log :
```
2019-11-13T12:27:52+00:00 ERR (3): libretime.libratoi.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: ErrorException: Undefined index: id in /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php:308
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(308): exception_error_handler(8, 'Undefined index...', '/usr/share/airt...', 308, Array)
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): ApiController->liveInfoAction()
#2 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('liveInfoAction')
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
```

Login POST: Nginx Log (reverse proxy):
```
xx.xx.xx.xx - - [13/Nov/2019:13:26:40 +0100] "POST /login HTTP/1.1" 500 521 "https://libretime.libratoi.org/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
```
Login POST :zendphp Log:
```
2019-11-13T12:26:40+00:00 ERR (3): libretime.libratoi.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Action_Exception: Forbidden in /usr/share/airtime/php/airtime_mvc/application/common/CORSHelper.php:15
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zf1s/zend-application/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
```
**Apache Logs (Airtime)**:

API REQUESTS WITH ERROR 500:
```
**192.168.10.1** - - [13/Nov/2019:13:48:41 +0000] "GET /api/live-info?callback=jQuery110206821063012419207_1573652879070&type=interval&limit=5&_=1573652879071 HTTP/1.0" 500 644 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
**192.168.10.1** - - [13/Nov/2019:13:48:44 +0000] "GET /api/live-info?callback=jQuery110206821063012419207_1573652879072&type=interval&limit=5&_=1573652879073 HTTP/1.0" 500 644 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
**192.168.10.1** - - [13/Nov/2019:13:48:47 +0000] "GET /api/live-info?callback=jQuery110206821063012419207_1573652879074&type=interval&limit=5&_=1573652879075 HTTP/1.0" 500 644 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
```
Login POST:
```
**192.168.10.1** - - [13/Nov/2019:13:28:40 +0000] "POST /login HTTP/1.0" 500 865 "https://libretime.libratoi.org/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"
```
API REQUEST WITH RETURN 200:
```
127.0.0.1 - - [13/Nov/2019:13:28:50 +0000] "GET /api/get-stream-parameters/api_key/K2URX29CG0R1Q8TBKZB7/format/json HTTP/1.1" 200 1315 "-" "Python-urllib/2.7"
127.0.0.1 - - [13/Nov/2019:13:28:50 +0000] "POST /api/update-stream-setting-table/api_key/K2URX29CG0R1Q8TBKZB7/format/json HTTP/1.1" 200 160 "-" "Python-urllib/2.7"
127.0.0.1 - - [13/Nov/2019:13:29:57 +0000] "GET /api/schedule/api_key/K2URX29CG0R1Q8TBKZB7 HTTP/1.1" 200 171 "-" "Python-urllib/2.7"
127.0.0.1 - - [13/Nov/2019:13:30:06 +0000] "GET /api/update-metadata-on-tunein/api_key/K2URX29CG0R1Q8TBKZB7 HTTP/1.1" 200 161 "-" "Python-urllib/2.7"
127.0.0.1 - - [13/Nov/2019:13:30:50 +0000] "GET /api/get-stream-parameters/api_key/K2URX29CG0R1Q8TBKZB7/format/json HTTP/1.1" 200 1315 "-" "Python-urllib/2.7"
127.0.0.1 - - [13/Nov/2019:13:30:50 +0000] "POST /api/update-stream-setting-table/api_key/K2URX29CG0R1Q8TBKZB7/format/json HTTP/1.1" 200 160 "-" "Python-urllib/2.7

**192.168.10.1** - - [13/Nov/2019:13:48:49 +0000] "GET /locale/general-translation-table?5ef9c9da9 HTTP/1.0" 200 5535 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
```

**Comment by OliCat** [comment] 2019-11-13 15:24
NB: On same environnement, API request are OK with Libretime v3.0.0-alpha.8 :

libretime.libratoi.org:80 192.168.10.1 - - [13/Nov/2019:15:15:33 +0000] "GET /api/live-info?callback=jQuery11020037138379944856026_1573658122008&type=interval&limit=5&_=1573658122010 HTTP/1.0" 200 436 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"

Login still NOK.

**Comment by paddatrapper** [comment] 2019-11-13 20:42
I did some edits just to help formatting.

Your issue is here (from Zend log post login):
```
2019-11-13T12:26:40+00:00 ERR (3): libretime.libratoi.org [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Action_Exception: Forbidden in /usr/share/airtime/php/airtime_mvc/application/common/CORSHelper.php:15
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
```
This suggests that there is an issue with Nginx proxy making some parts of LibreTime appear as if they are from a different site. Can you post your Nginx config?

**Comment by OliCat** [comment] 2019-11-13 21:25
Thanks for the edit :)
Login is now ok. I added manually authorized urls in CORSHelper.php
```
libretime.libratoi.org:80 192.168.10.1 - - [13/Nov/2019:21:02:05 +0000] "GET /api/live-info?callback=jQuery11020033841236629793436_1573678834905&type=interval&limit=5&_=1573678834906 HTTP/1.0" 500 834 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
libretime.libratoi.org:80 192.168.10.1 - - [13/Nov/2019:21:02:08 +0000] "GET /api/live-info?callback=jQuery11020033841236629793436_1573678834907&type=interval&limit=5&_=1573678834908 HTTP/1.0" 500 834 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
libretime.libratoi.org:80 192.168.10.1 - - [13/Nov/2019:21:02:11 +0000] "GET /api/live-info?callback=jQuery11020033841236629793436_1573678834909&type=interval&limit=5&_=1573678834910 HTTP/1.0" 500 834 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:70.0) Gecko/20100101 Firefox/70.0"
```
This is my vhost config:

```
server {
    listen 443 ssl;
    server_name libretime.libratoi.org;
	error_log  /var/log/nginx/libretime.error.log;
	access_log /var/log/nginx/libretime.access.log;
    location / {
        proxy_pass http://192.168.10.10:80/;
        proxy_redirect	off;
        proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Host $host;
        add_header Content-Security-Policy upgrade-insecure-requests;
     }
    
    ssl_certificate /etc/letsencrypt/live/libretime.libratoi.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/libretime.libratoi.org/privkey.pem;
    #include /etc/letsencrypt/options-ssl-nginx.conf;

    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
  # Recommended security settings from https://wiki.mozilla.org/Security  /Server_Side_TLS
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_prefer_server_ciphers on;
    ssl_ecdh_curve secp384r1;
    ssl_session_timeout 5m;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
    set_real_ip_from 192.168.10.1;
    real_ip_header X-Forwarded-For;
  
}
server {
    server_name libretime.libratoi.org ;
    return 301 https://libretime.libratoi.org$request_uri;
}
```

**Comment by paddatrapper** [comment] 2019-11-13 21:26
I seem to remember running into this issue before... Let me do some digging. I seem to remember a way of doing this that doesn't require changing the code...

**Comment by paddatrapper** [comment] 2019-11-13 21:35
Found it: https://github.com/LibreTime/libretime/issues/822#issuecomment-546609291. This is a duplicate of #822. I am going to close it and have opened #917 to track the documentation issue

**Closed** 2019-11-13 21:36 UTC
Labels: feedback-needed, question
