### ISSUE TITLE
Ubuntu Server 22.04 Installation fails

### ISSUE THREAD

**Issue by maxtimbo** [libretime/libretime#1857] opened 2022-05-25 03:01 UTC
**Describe the bug**
Installing LibreTime on a fresh install of Ubuntu 22.04 Jammy fails in a few different places.
I modified the install script to include Ubuntu Jammy, but php wasn't installed by the script, and zip and unzip were also not installed (which I understand that, why wasn't this installed by default by the OS?)

```
$ diff install libretime/install
662d661
< is_ubuntu_jammy=false
674,678d672
<   ubuntu-22.04)
<     code="jammy"
<     us_ubuntu_dist=true
<     is_ubuntu_jammy=true
<     ;;
1055c1049
< if $is_debian_bullseye || $is_ubuntu_focal || $is_ubuntu_jammy; then
---
> if $is_debian_bullseye || $is_ubuntu_focal; then
```

**To Reproduce**
Fresh install Ubuntu 22.04 -> attempt to install libretime from github

**LibreTime version:**
Version from the upgrade popup if you can reach it.

**Screenshots**
```
Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
make -C locale clean build
make[2]: Entering directory '/home/maxtim/libretime/legacy/locale'
msgfmt cs_CZ/LC_MESSAGES/libretime.po -o cs_CZ/LC_MESSAGES/libretime.mo
bash: line 1: msgfmt: command not found
make[2]: *** [Makefile:36: cs_CZ/LC_MESSAGES/libretime.mo] Error 127
make[2]: Leaving directory '/home/maxtim/libretime/legacy/locale'
make[1]: *** [Makefile:13: locale-build] Error 2
make[1]: Leaving directory '/home/maxtim/libretime/legacy'
make: *** [Makefile:32: build] Error 2
make: Leaving directory '/home/maxtim/libretime/legacy'

```

**Comment by paddatrapper** [comment] 2022-05-25 05:20
Duplicate of #1845

**Closed by paddatrapper** 2022-05-25 05:20 UTC
Labels: is: bug
