### ISSUE TITLE
`file-magic` newest release

### ISSUE THREAD

**Issue by CGenie** [LibreTime/libretime#717] opened 2019-01-23 05:35 UTC
**Describe the bug**
With `file-magic` 0.4.0 which went out live on 1st of Jan 2019
https://pypi.org/project/file-magic/#history
there is an issue that the `airtime_analyzer` no longer works properly:
```
2019-01-23 05:28:42,251 [analyzer_pipeline] [ERROR]  'module' object has no attribute 'open'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 66, in run_analysis
    metadata = MetadataAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/metadata_analyzer.py", line 44, in analyze
    ms = magic.open(magic.MIME_TYPE
```

**To Reproduce**
Install `file-magic == 0.4.0`.

**Expected behavior**
No error should happen or fix `file-magic == 0.3.0` in the `requirements.txt` file.

**LibreTime version:**
`8dd55e2`

**Comment by paddatrapper** [comment] 2019-01-23 07:36
So I'm busy playing with this. Mutagen seems to handle wav files fine now, so I think we should drop file-magic completely. I'm still testing it though

**Comment by paddatrapper** [comment] 2019-01-23 08:49
Parsing with mutagen works. I run into other errors due to https://github.com/savonet/liquidsoap/issues/436, but that should be fixed with liquidsoap 1.3.3 in Buster (#683). I'll open a PR with the fix

**Comment by hairmare** [comment] 2019-01-25 09:16
I can't seem to reproduce this using file-magic==0.4.0 from Pypi. Are you sure that you didn't install the wrong magic from Pypi or something broken from a Debian package? 

What distro are you using? 

Can you do a quick check to figure out what magic you are importing?
This example should print some help text if you are importing [python-magic](https://pypi.org/project/python-magic/)
```
printf "import magic\nhelp(magic.open_from_file)" | python -
```
This should print help if [file-magic](https://pypi.org/project/file-magic/) is available:
```
printf "import magic\nhelp(magic.open)" | python - 
```
Please let us know which one prints an error and which one works.

I've added some docker based examples to show how I tried to reproduce this on various python flavours and even Debian testing below:
<details>
  <summary>Expand for docker file-magic tests and output </summary>
<h3> python:2 </h3>
<pre>
$ docker run --rm -ti python:2 bash
root@0a35c358501f:/# pip install file-magic==0.4.0
Collecting file-magic==0.4.0
  Downloading https://files.pythonhosted.org/packages/bc/e5/818e16cc2100898a5ab313e6a468a04390e6157fed539c98deab40015454/file-magic-0.4.0.tar.gz
Building wheels for collected packages: file-magic
  Running setup.py bdist_wheel for file-magic ... done
  Stored in directory: /root/.cache/pip/wheels/25/aa/78/7765742361ec907e75826b129b8b628f973f91deef71cbebdb
Successfully built file-magic
Installing collected packages: file-magic
Successfully installed file-magic-0.4.0
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@0a35c358501f:/# python
Python 2.7.15 (default, Jan 23 2019, 03:48:04) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> ms=magic.open(magic.MIME_TYPE)
>>> ms
&lt;magic.Magic object at 0x7f98484cf0d0&gt;
</pre>
<h3> python:3 </h3>
<pre>
 $ docker run --rm -ti python:3 bash
root@9ed42134f814:/# pip install file-magic==0.4.0
Collecting file-magic==0.4.0
  Downloading https://files.pythonhosted.org/packages/bb/7e/b256e53a6558afd348387c3119dc4a1e3003d36030584a427168c8d72a7a/file_magic-0.4.0-py3-none-any.whl
Installing collected packages: file-magic
Successfully installed file-magic-0.4.0
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@9ed42134f814:/# python
Python 3.7.2 (default, Jan 23 2019, 02:31:57) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> ms=magic.open(magic.MIME_TYPE)
>>> ms
&lt;magic.Magic object at 0x7fb9ee354438&gt;
</pre>
<h3>debian:testing</h3>
<pre>
$ docker run --rm -ti debian:testing bash
root@392d74b1e1f0:/# apt update
Get:1 http://cdn-fastly.deb.debian.org/debian testing InRelease [159 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian testing/main amd64 Packages [7924 kB]
Fetched 8083 kB in 5s (1773 kB/s)   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@392d74b1e1f0:/# apt install python-magic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  bzip2 file libexpat1 libmagic-mgc libmagic1 libpython-stdlib libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libreadline7 libsqlite3-0 libssl1.1 mime-support python python-minimal python2 python2-minimal python2.7
  python2.7-minimal readline-common xz-utils
Suggested packages:
  bzip2-doc python-doc python-tk python2-doc python2.7-doc binutils binfmt-support readline-doc
The following NEW packages will be installed:
  bzip2 file libexpat1 libmagic-mgc libmagic1 libpython-stdlib libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libreadline7 libsqlite3-0 libssl1.1 mime-support python python-magic python-minimal python2 python2-minimal
  python2.7 python2.7-minimal readline-common xz-utils
0 upgraded, 22 newly installed, 0 to remove and 3 not upgraded.
Need to get 7409 kB of archives.
After this operation, 29.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libpython2.7-minimal amd64 2.7.15-5 [394 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python2.7-minimal amd64 2.7.15-5 [1365 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python2-minimal amd64 2.7.15-4 [41.4 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python-minimal amd64 2.7.15-4 [21.0 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian testing/main amd64 mime-support all 3.61 [37.1 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libexpat1 amd64 2.2.6-1 [105 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian testing/main amd64 readline-common all 7.0-5 [70.6 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libreadline7 amd64 7.0-5 [151 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libsqlite3-0 amd64 3.26.0+fossilbc891ac6b-1 [634 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libssl1.1 amd64 1.1.1a-1 [1527 kB]
Get:11 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libpython2.7-stdlib amd64 2.7.15-5 [1909 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python2.7 amd64 2.7.15-5 [299 kB]
Get:13 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libpython2-stdlib amd64 2.7.15-4 [20.8 kB]
Get:14 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libpython-stdlib amd64 2.7.15-4 [20.8 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python2 amd64 2.7.15-4 [41.6 kB]
Get:16 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python amd64 2.7.15-4 [22.8 kB]
Get:17 http://cdn-fastly.deb.debian.org/debian testing/main amd64 bzip2 amd64 1.0.6-9 [48.3 kB]
Get:18 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libmagic-mgc amd64 1:5.35-2 [242 kB]
Get:19 http://cdn-fastly.deb.debian.org/debian testing/main amd64 libmagic1 amd64 1:5.35-2 [117 kB]
Get:20 http://cdn-fastly.deb.debian.org/debian testing/main amd64 file amd64 1:5.35-2 [66.1 kB]
Get:21 http://cdn-fastly.deb.debian.org/debian testing/main amd64 xz-utils amd64 5.2.2-1.3 [266 kB]
Get:22 http://cdn-fastly.deb.debian.org/debian testing/main amd64 python-magic all 2:0.4.15-2 [9196 B]
Fetched 7409 kB in 4s (1801 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libpython2.7-minimal:amd64.
(Reading database ... 6577 files and directories currently installed.)
Preparing to unpack .../00-libpython2.7-minimal_2.7.15-5_amd64.deb ...
Unpacking libpython2.7-minimal:amd64 (2.7.15-5) ...
Selecting previously unselected package python2.7-minimal.
Preparing to unpack .../01-python2.7-minimal_2.7.15-5_amd64.deb ...
Unpacking python2.7-minimal (2.7.15-5) ...
Selecting previously unselected package python2-minimal.
Preparing to unpack .../02-python2-minimal_2.7.15-4_amd64.deb ...
Unpacking python2-minimal (2.7.15-4) ...
Selecting previously unselected package python-minimal.
Preparing to unpack .../03-python-minimal_2.7.15-4_amd64.deb ...
Unpacking python-minimal (2.7.15-4) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../04-mime-support_3.61_all.deb ...
Unpacking mime-support (3.61) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../05-libexpat1_2.2.6-1_amd64.deb ...
Unpacking libexpat1:amd64 (2.2.6-1) ...
Selecting previously unselected package readline-common.
Preparing to unpack .../06-readline-common_7.0-5_all.deb ...
Unpacking readline-common (7.0-5) ...
Selecting previously unselected package libreadline7:amd64.
Preparing to unpack .../07-libreadline7_7.0-5_amd64.deb ...
Unpacking libreadline7:amd64 (7.0-5) ...
Selecting previously unselected package libsqlite3-0:amd64.
Preparing to unpack .../08-libsqlite3-0_3.26.0+fossilbc891ac6b-1_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.26.0+fossilbc891ac6b-1) ...
Selecting previously unselected package libssl1.1:amd64.
Preparing to unpack .../09-libssl1.1_1.1.1a-1_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1a-1) ...
Selecting previously unselected package libpython2.7-stdlib:amd64.
Preparing to unpack .../10-libpython2.7-stdlib_2.7.15-5_amd64.deb ...
Unpacking libpython2.7-stdlib:amd64 (2.7.15-5) ...
Selecting previously unselected package python2.7.
Preparing to unpack .../11-python2.7_2.7.15-5_amd64.deb ...
Unpacking python2.7 (2.7.15-5) ...
Selecting previously unselected package libpython2-stdlib:amd64.
Preparing to unpack .../12-libpython2-stdlib_2.7.15-4_amd64.deb ...
Unpacking libpython2-stdlib:amd64 (2.7.15-4) ...
Selecting previously unselected package libpython-stdlib:amd64.
Preparing to unpack .../13-libpython-stdlib_2.7.15-4_amd64.deb ...
Unpacking libpython-stdlib:amd64 (2.7.15-4) ...
Setting up libpython2.7-minimal:amd64 (2.7.15-5) ...
Setting up python2.7-minimal (2.7.15-5) ...
Linking and byte-compiling packages for runtime python2.7...
Setting up python2-minimal (2.7.15-4) ...
Selecting previously unselected package python2.
(Reading database ... 7414 files and directories currently installed.)
Preparing to unpack .../python2_2.7.15-4_amd64.deb ...
Unpacking python2 (2.7.15-4) ...
Setting up python-minimal (2.7.15-4) ...
Selecting previously unselected package python.
(Reading database ... 7447 files and directories currently installed.)
Preparing to unpack .../0-python_2.7.15-4_amd64.deb ...
Unpacking python (2.7.15-4) ...
Selecting previously unselected package bzip2.
Preparing to unpack .../1-bzip2_1.0.6-9_amd64.deb ...
Unpacking bzip2 (1.0.6-9) ...
Selecting previously unselected package libmagic-mgc.
Preparing to unpack .../2-libmagic-mgc_1%3a5.35-2_amd64.deb ...
Unpacking libmagic-mgc (1:5.35-2) ...
Selecting previously unselected package libmagic1:amd64.
Preparing to unpack .../3-libmagic1_1%3a5.35-2_amd64.deb ...
Unpacking libmagic1:amd64 (1:5.35-2) ...
Selecting previously unselected package file.
Preparing to unpack .../4-file_1%3a5.35-2_amd64.deb ...
Unpacking file (1:5.35-2) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../5-xz-utils_5.2.2-1.3_amd64.deb ...
Unpacking xz-utils (5.2.2-1.3) ...
Selecting previously unselected package python-magic.
Preparing to unpack .../6-python-magic_2%3a0.4.15-2_all.deb ...
Unpacking python-magic (2:0.4.15-2) ...
Setting up readline-common (7.0-5) ...
Setting up libexpat1:amd64 (2.2.6-1) ...
Setting up mime-support (3.61) ...
Setting up libreadline7:amd64 (7.0-5) ...
Setting up libmagic-mgc (1:5.35-2) ...
Setting up bzip2 (1.0.6-9) ...
Setting up libmagic1:amd64 (1:5.35-2) ...
Processing triggers for libc-bin (2.28-5) ...
Setting up libssl1.1:amd64 (1.1.1a-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up xz-utils (5.2.2-1.3) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
Setting up libsqlite3-0:amd64 (3.26.0+fossilbc891ac6b-1) ...
Setting up libpython2.7-stdlib:amd64 (2.7.15-5) ...
Setting up python2.7 (2.7.15-5) ...
Setting up file (1:5.35-2) ...
Setting up libpython2-stdlib:amd64 (2.7.15-4) ...
Setting up python2 (2.7.15-4) ...
Setting up libpython-stdlib:amd64 (2.7.15-4) ...
Setting up python (2.7.15-4) ...
Setting up python-magic (2:0.4.15-2) ...
Processing triggers for libc-bin (2.28-5) ...
root@392d74b1e1f0:/# python 
Python 2.7.15+ (default, Nov 28 2018, 16:27:22) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> ms=magic.open(magic.MIME_TYPE)
>>> ms
&lt;magic.compat.Magic object at 0x7f8f7d3b20d0&gt;
</pre>
It looks like Debian did one of their "compat" moves by supplying `magic.compat.Magic` instead of `magic.Magic`.
</details>

**Comment by jooola** [comment] 2021-05-29 22:27
Mutagen supports WAVE with version 1.45, see https://mutagen.readthedocs.io/en/latest/changelog.html#release-1-45-0

But Mutagen seem 1.45 is not shipped on most of the supported distributions.

[![Debian Stable package](https://repology.org/badge/version-for-repo/debian_stable/mutagen.svg)](https://repology.org/project/mutagen/versions)
[![Debian Testing package](https://repology.org/badge/version-for-repo/debian_testing/mutagen.svg)](https://repology.org/project/mutagen/versions)
[![Ubuntu 16.04 package](https://repology.org/badge/version-for-repo/ubuntu_16_04/mutagen.svg)](https://repology.org/project/mutagen/versions)
[![Ubuntu 18.04 package](https://repology.org/badge/version-for-repo/ubuntu_18_04/mutagen.svg)](https://repology.org/project/mutagen/versions)
[![Ubuntu 20.04 package](https://repology.org/badge/version-for-repo/ubuntu_20_04/mutagen.svg)](https://repology.org/project/mutagen/versions)
[![Ubuntu 21.04 package](https://repology.org/badge/version-for-repo/ubuntu_21_04/mutagen.svg)](https://repology.org/project/mutagen/versions)

**Closed** 2022-02-16 08:13 UTC
Labels: is: bug, status: feedback needed, status: pinned
