### ISSUE TITLE
schedule starting with wrong month-day and showing the day after that's schedule

### ISSUE THREAD

**Issue by leonardpg** [libretime/libretime#401] opened 2018-01-03 02:21 UTC
It's Tuesday January 2 where I am, but Libretime is starting the seven day schedule with Tuesday, January 3. Also, it's displaying the programs that are set to play on Wednesday January 3, not Tuesday January 2. My system time appears to be correct. Has anyone encountered this problem before?
<img width="774" alt="screen shot 2018-01-02 at 9 15 16 pm" src="https://user-images.githubusercontent.com/9553791/34507318-ced69782-f002-11e7-9238-801b91f82e23.png">

**Comment by Robbt** [comment] 2018-01-03 02:28
Hmm, weird. I'd check the timezone under settings.

**Comment by leonardpg** [comment] 2018-01-03 14:48
Weird...I went in to settings and timezone was correct, but the language was "English Canada". So I changed that to English US and saved the settings. Then suddenly I'm back to the correct day/date.

**Comment by Robbt** [comment] 2018-01-03 15:16
Hmm, I just looked at our LibreTime page and it was correct without the modification. My suspicion is based upon checking the date is that it was the 3rd for UTC but Tuesday the 2nd for the rest of us and thus it was saying Tuesday the 3rd. To diagnose further will require looking at the underlying code. 

After 8pm EST it should have the wrong date again if my hunch is right and then fix itself at midnight.

**Comment by leonardpg** [comment] 2018-01-03 15:32
Maybe it's because I installed libretime before setting the system timezone?

**Comment by Robbt** [comment] 2018-01-03 15:36
If I had to guess it is probably just a bug in the Radio Page implementation, there is a lot of hastily written code and minor bugs lurking around from the branch we forked off of, many of which were subsequently fixed in Airtime.pro.

**Comment by hairmare** [comment] 2018-01-03 17:06
I only looked into this today so I didn't see the error. I'm assuming it would have been on production instance as well had I looked on the 2nd. I concur with the assumption that this is most likely due to a front-end bug on the radio page and not the actual data being wrong.

**Comment by adamburnsuk** [comment] 2018-01-24 02:30
This is also happening to me.  It effects both the radio page and the widget.  Just to give more info.

**Comment by adamburnsuk** [comment] 2018-04-25 15:30
Has anyone had a chance to look at this?  I noticed there's also another issue where a guy created a NEW schedule widget.  Would this new widget solve this problem?  I'm having other wierd issues with my schedule as well, where it says "**Looks like there are no shows scheduled on this day.**" But, I have a repeating schedule...there are no empty days.  This only started happening maybe a month ago.  If I could solve both of these schedule related issues with one fix, that would be great.

**Comment by JohnnyC1951** [comment] 2018-04-29 11:00
OK I will have a look today. It will just be a non-conversion to local time that got missed.
Also, It got the winter to summer time change-over wrong, but not the summer to winter.

**Comment by JohnnyC1951** [comment] 2018-04-29 12:42
> Weird...I went in to settings and timezone was correct, but the language was "English Canada". So I changed that to English US and saved the settings. Then suddenly I'm back to the correct day/date.

That is an import clue.

**Comment by JohnnyC1951** [comment] 2018-05-07 22:35
`<img style="width:100%" src='http://deprogrammedradio.com/images/lt.jpg'>`

**Comment by JohnnyC1951** [comment] 2018-05-07 22:53
This is a 100% reworked code. The LT/ATPRO has limitations, hard coded, in what it returns for the scheduled widget. Basically, 'station midnight' is 'station midnigh't & that is that. So I rewrote the widget from zero using witchcraft, and the best quality smoke & mirrors. Basically I am getting the user's timezone, reading all the json from the server and refactoring it into the correct timezone for the user and slicing & dicing a 'new midnight' which is correct for the user.. Rather surprisingly, it is fast. It doesn't use or load any external libraries at all, so, you lose a bit on the extra server processing but gain back from not having to use/load angular.js & jquery on the client side.
See it working here: [https://x-pedia.org/](url)

**Comment by JohnnyC1951** [comment] 2018-05-08 23:39
Latest time corrected weekly schedule widget http://deprogrammedradio.com/images/schedule.jpg
<img style="width:100%" src='http://deprogrammedradio.com/images/schedule.jpg'>

**Comment by adamburnsuk** [comment] 2018-05-09 20:04
Based on the screen shots it looks great.  I'm excited to try it out.  If it works for everyone, maybe you could do a pull request to add it to the main branch.  Since the current widget doesn't work, seems it would be a good replacement.

**Comment by JohnnyC1951** [comment] 2018-05-09 20:37
Its can be used 2 ways: copy it over the LT original or put in ../public/whatever (recommended by me) or even both
I am just stripping out the debug code. You can also add your own external background and external css if you want.

**Comment by JohnnyC1951** [comment] 2018-05-09 21:16
Come find me on FB

**Comment by Robbt** [comment] 2018-05-09 21:37
@JohnnyC1951 is is possible for you to put together a PR for this code or update the previous one you did ? I know I haven't merged your previous PR but that is mainly because I haven't sat down and done this. I don't think it's very helpful to post screenshots of code that isn't going to be made freely available as part of the project. You could even just create your own github fork and create the branch and link to that if you don't want it to be merged with LT for now.

**Comment by adamburnsuk** [comment] 2018-05-09 21:42
Just my two cents, but I would love it to be merged into LT because I know there are several facing issues with the schedule widget.  But I would prefer to stay on main branch of LT and not a fork.  :)

**Comment by Robbt** [comment] 2018-05-09 21:44
@adamburnsuk - indeed this is probably the best route, it looks like a superior widget in a lot of ways.

**Comment by JohnnyC1951** [comment] 2018-05-09 21:46
er.. we have been here before.
But you are very welcome.

**Comment by JohnnyC1951** [comment] 2018-05-09 21:52
My add-ins have never been forks, to date. They never ever impinged upon the core code. I was even criticized for that ;\
Some of us have urgent needs to just 'get stuff working NOW. Which is why have made some useful add-ins. I do not expect them to be blessed by the Pope or even adopted officially, just to help some other poor folks while the team sort out stuff long term.
"I don't want it RIGHT, I want TUESDAY" Sam Goldwyn

**Comment by JohnnyC1951** [comment] 2018-05-09 23:29
Here is an Alpha. Live site here [http://www.deprogrammedradio.com/](http://www.deprogrammedradio.com/) and here [https://x-pedia.org/new-widget/weekly-program.phtml](https://x-pedia.org/new-widget/weekly-program.phtml) and here [https://x-pedia.org/](https://x-pedia.org/) Note every one is a bit different, I am expecting bug reports so expect it to limp but if so we can fix it, Read.me inside.
[http://deprogrammedradio.com//downloads/new-widget.tar.gz](http://deprogrammedradio.com//downloads/new-widget.tar.gz)

**Comment by jooola** [comment] 2022-09-20 18:06
Closing as I could not reproduce this issue. If it is still occurring please open a new issue and fill out the issue form to provide as much data as possible so we can reproduce the bug.

**Closed by jooola** 2022-09-20 18:06 UTC
Labels: is: bug, php
