### ISSUE TITLE
autoloading playlist in scheduled shows

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#1517] opened 2022-01-15 11:49 UTC
hi,
on latest main commit

i have smart blocks added to playlist, and playlists are autoloading in shows,
this does not work, also editing existing playlist does not work.

creating a new playlist adding tracks manually and saving does work, but if if you try to add a smart block to playlist, the playlist gets destroyed and needs deleted.

this was fine before the upgrade

**Comment by paddatrapper** [comment] 2022-01-15 13:53
Please post relevant parts of your log files under /var/log/airtime and /var/log/libretime and details of your setup (OS, etc). In future please use the issue template provided when opening a new issue

**Comment by maydo** [comment] 2022-01-15 14:24
@paddatrapper ok will do that.

**Describe the bug**
playlists not editable if smart blocks added.

**To Reproduce**
create a new playist
drop a smart block to playlist
playlist becomes undefined and cannot be saved

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**LibreTime version:**
4443528cf
latest commit 8b4260d


**Installation method:**
git clone
bash install -fiap

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Screenshots**
<img width="1667" alt="Screenshot 2022-01-15 at 15 22 54" src="https://user-images.githubusercontent.com/27486434/149625083-3bf4dddc-29f6-4a7e-9230-deaabc316b86.png">


**Client (please complete the following information if applicable):**

- OS: Mac OS Monterey
- Browser chrome


**Additional context**
this was fine before the upgrade

**Comment by jooola** [comment] 2022-01-15 14:31
Seem like a duplicate off #1448

**Comment by jooola** [comment] 2022-01-15 14:32
#1512 Could improve the situation, but I cannot say if it fixes it.

**Comment by maydo** [comment] 2022-01-15 14:46
@joola, i can try this on my test system, but i dont know how to pull the other to test

its installed with standard procedure

git clone https://github.com/LibreTime/libretime.git
cd libretime
sudo bash install -fiap

**Comment by jooola** [comment] 2022-01-15 14:53
Here you go (haven't tested this though):
```sh
git clone https://github.com/LibreTime/libretime.git
cd libretime
git remote add jooola https://github.com/jooola/libretime.git
git fetch jooola
git checkout deps/upgrade_propel
sudo bash install -fiap
```

**Comment by maydo** [comment] 2022-01-15 15:11
just tested, its same behaviour

can create a new playlist, add manually tracks and save, this works
but once adding a smart block, it damages the playlist and needs to be deleted.

how can i revert to main branch ?

**Comment by jooola** [comment] 2022-01-15 15:37
```
git checkout main
```

**Comment by maydo** [comment] 2022-01-15 22:38
<img width="648" alt="Screenshot 2022-01-15 at 23 33 51" src="https://user-images.githubusercontent.com/27486434/149639747-9428b34a-c851-4b2c-9222-c18961050f47.png">

`/usr/share/airtime/php/legacy/application/models/Playlist.php`
it seems like 
`$fades = $this->getFadeInfo($row['position']);`
not getting array result from db
as workaround i have added these two lines
```
$fades[0] =0.5;
$fades[1] =5;
```

**Comment by jooola** [comment] 2022-01-16 00:03
This workaround has already been proposed in #1448

**Comment by jooola** [comment] 2022-01-16 00:04
Closing as duplicate of #1448

**Closed** 2022-01-16 00:03 UTC
Labels: is: bug
