### ISSUE TITLE
Airtime_analyzer fails to process new uploads

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#884] opened 2019-10-04 05:22 UTC
**Describe the bug**
The UI tells me that all my uploads are still pending, and when i check the airtime_analyzer logs I see that it gets a 400 bad request.

**To Reproduce**
1. Upload a file and see what happens in airtime_analyzer.log file

**Expected behavior**
Airtime analyzer should process the uploaded file.

**LibreTime version:**
Current master @ commit 4e99021d7

**Installation method:**
 - OS: Debian Buster
 - Method: install script + apt install silan
 - Details: Script came from master in the git repo

**Additional context**
Analyzer logs :
```
2019-10-04 06:58:08,342 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/srv\/airtime\/stor\/organize\/02 - Jamie Xx - Sleep Sound.mp3","storage_backend":"file","import_directory":"\/srv\/airtime\/stor\/\/imported\/1","original_filename":"02 - Jamie Xx - Sleep Sound.mp3","callback_url":"http:\/\/schedule.radio.org\/\/rest\/media\/15","api_key":"BNHU3TJB7JS8Z4MDLEWU","file_prefix":""}' on routing_key ''
2019-10-04 06:58:17,001 [status_reporter] [ERROR]  HTTP request failed. Exception was: 400 Client Error: Bad Request for url: https://schedule.radio.org//rest/media/15
```

Zend logs:
```
2019-10-04T07:26:17+02:00 INFO (6): schedule.radio.org Moving file /tmp/phprR7lHY to /srv/airtime/stor/organize/02 - Jamie Xx - Sleep Sound.mp3
2019-10-04T07:26:22+02:00 ERR (3): schedule.radio.org [MediaController.php:190 - putAction()] - array_key_exists() expects parameter 2 to be array, null given
```

**Comment by Robbt** [comment] 2019-10-05 22:17
I haven't ran into this before, I am guessing that the issue is here- https://github.com/LibreTime/libretime/blob/4e99021d70e71dfaa8a8584cd718e024d5a0e744/airtime_mvc/application/modules/rest/controllers/MediaController.php#L174 which is resulting in the array_key_exists error. 

Is it failing for all scripts ? I think that Debian Buster uses LiquidSoap 1.3 by default and I'm pretty sure we haven't gotten everything working under Buster yet because of this. @paddatrapper - have you tested a install of LibreTime on Vanilla Buster ?

**Comment by paddatrapper** [comment] 2019-10-07 18:41
@jooola have you applied the Liquidsoap >=1.3 patch? With that patch, it runs fine on a buster vagrant instance last I tested it.

**Comment by jooola** [comment] 2019-10-08 00:37
Haven't had time to dive into this, will try any time soon.

**Comment by jooola** [comment] 2019-10-08 22:46
Could you tell me more about this patch ? Where is it ?

**Comment by Robbt** [comment] 2019-10-08 22:54
Check out - https://github.com/LibreTime/libretime/issues/192

**Comment by paddatrapper** [comment] 2020-01-08 12:13
@jooola do you still get this error?

**Comment by jooola** [comment] 2020-01-08 15:07
I left the Libretime installation task to someone else, so I haven't worked on this since then. Also haven't tested the patch Robbt proposed.

I might come back to this in some time. Is it ok if we leave it open ? Or close it I'll reopen if I stumble on this again in the future.

**Comment by paddatrapper** [comment] 2020-01-08 15:26
OK, I'll close it for now and re-open if you run into it again

**Comment by paddatrapper** [comment] 2020-05-07 15:26
I'm running into this issue at the moment

**Closed** 2020-05-07 15:30 UTC
Labels: bug, feedback-needed

**Comment by paddatrapper** [comment] 2020-05-07 16:11
This seems to be the same issue as #957
