### ISSUE TITLE
Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.

### ISSUE THREAD

**Issue by MortezaBashsiz** [libretime/libretime#1175] opened 2021-02-13 13:09 UTC
**Describe the bug**
After setting a new calendar for live event, when I push on play buttom the error appears

Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.

**LibreTime version:**
Final version from git

**Installation method:**
 - OS: Ubuntu
 - OS Version : 18.04
 - Method: ./install` script
 - Details:  from github

**Screenshots**
![image](https://user-images.githubusercontent.com/19620677/107850689-80425280-6e19-11eb-85fa-a35c8b393a25.png)

**Client (please complete the following information if applicable):**
 - OS: Arch
 - Browser: Chrome, Firefox
 - Version: 88.0.43, 85.0.2

**Comment by jsx150** [comment] 2021-02-28 07:57
Open invitation come in fr

**Comment by jooola** [comment] 2022-09-26 22:31
Duplicate of #1027

**Closed by jooola** 2022-09-26 22:31 UTC
Labels: is: bug, status: stalled
