### ISSUE TITLE
Help with stream settings

### ISSUE THREAD

**Issue by csurulyal** [LibreTime/libretime#723] opened 2019-01-28 09:31 UTC
Ubuntu Xenial - libretime 3.0.0 beta 6

In the webIf i'm unable to set the mount point of the output streams

Please help

**Comment by hairmare** [comment] 2019-01-28 09:35
Did you switch to "Custom / 3rd Party Streaming"?

![image](https://user-images.githubusercontent.com/116588/51826849-56786a80-22e8-11e9-90a9-76232cfe2342.png)

**Comment by csurulyal** [comment] 2019-01-28 09:37
I did not, 'couse it's my own local icecast stream from within the libretime package.

**Comment by hairmare** [comment] 2019-01-28 15:14
If you want to change the mountpoint from `/_a` to something of your own choosing you need to activate "Custom / 3rd Party Streaming". Is it displaying an error message?

**Comment by csurulyal** [comment] 2019-01-28 17:38
Yeapp. The solution you gave me, it worked all right. Thank you for your time, patience and promptness. No error message, everithing is ok. It just confused me the 3rd Party.

**Comment by hairmare** [comment] 2019-01-28 19:04
Yeah, the default vs. 3rd party thing is confusing, I realized there is already #236 to track fixing it.

Duplicate of #236

**Closed by hairmare** 2019-01-28 19:04 UTC
Labels: bug
