### ISSUE TITLE
Stream going offline on either next track or randomly

### ISSUE THREAD

**Issue by samkitk** [libretime/libretime#1666] opened 2022-03-06 06:29 UTC
**Describe the bug**
Output stream goes offline randomly at frequent intervals

**To Reproduce**
Schedule a show; I scheduled 2-4 hours long show
Check after 1-2 hours, the stream would be offline
It usually happens when the track changes
I have to manually go to settings > streams > save (to restart the icecast stream connectivity)

**Expected behavior**
Should play normally 

**LibreTime version:**
3.0.0-alpha.10

**Installation method:**

- OS: 18.04 Ubuntu
- Method: as detailed on libretime.org

**Issue**
Stream goes offline and I have to restart the STREAM (through settings>streams>save) (no changes in settings, just click on save again) -- are you sure you want to restart? yes.

**Log Files**
[apache-error.log](https://github.com/libretime/libretime/files/8192050/apache-error.log)
[api.log](https://github.com/libretime/libretime/files/8192051/api.log)
[icecast-error.log](https://github.com/libretime/libretime/files/8192052/icecast-error.log)
[journalctl-u-libretime-playout.log](https://github.com/libretime/libretime/files/8192053/journalctl-u-libretime-playout.log)
[ls_script.log](https://github.com/libretime/libretime/files/8192054/ls_script.log)
[notify.log](https://github.com/libretime/libretime/files/8192055/notify.log)
[pypo.log](https://github.com/libretime/libretime/files/8192056/pypo.log)
[zendphp.log](https://github.com/libretime/libretime/files/8192057/zendphp.log)

**Additional context**
The red light of ON AIR goes grey when changing track.
Whenever the next track comes in it turns for 3-4 seconds and then goes grey
It happens randomly sometimes it plays normally for a long time and then sometimes even after 15 mins it goes offline

Maybe related to #1172 , a couple of things are similar

**Comment by samkitk** [comment] 2022-03-06 06:32
5:48 UTC 6th Match 2022; at this time I know for sure that it failed here

**Comment by jooola** [comment] 2022-03-06 13:25
Duplicate of #1658 and #1453, closed by #1663

**Comment by jooola** [comment] 2022-03-06 13:27
Pleae, ignore my previous messages.

**Comment by jooola** [comment] 2022-03-07 11:39
From the pypo and api logs, it seems like the api is having some trouble. Have you tried running possible missing migrations ?

`libretime-api migrate`

I would try to work around the API to find your issue.

The django API is partially responsible for serving the playout schedule to play. The initial schedule is pushed via another communication channel hence why it works at first and stops once playout need to fetch the schedule via the API.

**Comment by samkitk** [comment] 2022-03-07 11:50
Thank for getting back!

I applied it, it says no migrations to apply

```
root@localhost:~# libretime-api migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

```

**Comment by jooola** [comment] 2022-03-07 11:53
Did you by any chance deleted somes files supposed to be played ?

**Comment by jooola** [comment] 2022-03-07 12:00
From what I might understand from the api logs, is that the schedule is referring to a file row in the database that doesn't exists anymore. I am still new to django so I am not completely sure of this assumptions.

So I think this is maybe due to some wonky data in the DB, but could be a bug also, I've never faced this.

Also I saw some weird access logs, have you changes the apache configuration file ?

**Comment by samkitk** [comment] 2022-03-07 12:05
No and no for 

> Did you by any chance deleted somes files supposed to be played ?

Nope, 0 changes to any of the file.



> From what I might understand from the api logs, is that the schedule is referring to a file row in the database that doesn't exists anymore. I am still new to django so I am not completely sure of this assumptions.
> 
> So I think this is maybe due to some wonky data in the DB, but could be a bug also, I've never faced this.
> 
> Also I saw some weird access logs, have you changed the apache configuration file ?

Nope  fresh 2GB ram VM, strictly followed what the website instructed and no changes to any configuration file of any kind.

**Comment by samkitk** [comment] 2022-03-07 12:09
By the way, I have tried completely wiping off the server and reinstalling, I am able to reproduce this bug every time with 3.0.0-alpha10

**Comment by matias-tecnosoul** [comment] 2022-04-19 09:24
Any news about this? Something like described here happened yesterday in a fresh debian 11 install with backed up db and store. Latest git as april 18th.
Any hints where to ďig? 
Thanks!

**Comment by jooola** [comment] 2022-04-19 09:35
@matias-tecnosoul Please open a new issue if you are experiencing an issue. We have plenty of bug related to "stream goes offline" while each one often requires a different fix or is a totally different scenario. In addition the version 3.0.0-alpha.12 contains a few fixes for previous problem like this one, please upgrade first.

**Comment by matias-tecnosoul** [comment] 2022-04-19 09:43
@jooola thanks. It is a git install pulled april the 18th.
Will do more testing today.

**Comment by jooola** [comment] 2022-04-19 09:45
@matias-tecnosoul Aah my bad did saw the end of your comment, in any case, please open a new issue, this one is referring to 3.0.0-alpha.10.

**Comment by VladislavF** [comment] 2022-07-13 05:23
I have the exact same issue currently with alpha 12. I have tried a fresh install on a brand new Ubuntu 20.04 VM with no luck in solving the problem. It seems to become worse over time too, though this is anecdotal. It is regular for my stream to cut off once every hour or so now. And it almost always happens during track switching. I have attached two snippets of my playout and API logs which show the same error as @samkitk 's. As well as a section of my apache2 log which shows the proxy connection error. This is all with the local/default configurations for apache/airtime.conf. I apologize for the snippets, these are all I have saved off before the files got overwritten during troubleshooting.
In the meantime I have come up with a terrible cludge to make libretime at least slightly usable because otherwise it will go offline almost certainly within 2 hours or less. @samkitk 's idea of hitting the save button to reset the streams gave me the inkling for a script that automates the process. It relies on scraping the libretime offline status from the icecast page.

This script will at least bring your stream back online within a few minutes of it going out. It's gross, and probably has some redundant elements, but it works for me at least. The "TRIG" variable is to help make sure it isn't restarted during a normal pause that might happen between show end and start.

#!/bin/bash
TRIG=0
while [ 1 ]
do
  text=$(curl -sL http://localhost:8000 | grep -oP '(?<=Currently playing:</td><td class="streamstats">).*?(?=<)')
  SUB='LibreTime - offline'
  EXEC=0
  if [[ "$text" == *"$SUB"* ]] && [[ $TRIG -eq 1 ]]; then
    echo "offline timeout: restarting"
    date
    sudo service libretime-playout stop
    sudo service libretime-liquidsoap stop
    echo "apache"
    sudo service apache2 restart
    echo "time"
    sudo timedatectl set-ntp off
    sudo timedatectl set-ntp on
    echo "api"
    sudo service libretime-api restart
    echo "analyzer"
    sudo service libretime-analyzer restart
    echo "celery"
    sudo service libretime-celery restart
    echo "liquidsoap"
    sudo service libretime-liquidsoap restart
    echo "playout"
    sudo service libretime-playout restart
    echo "apache"
    sudo service apache2 restart
    TRIG=0
    EXEC=1
    sleep 200
  fi
  if [[ "$text" == *"$SUB"* ]] && [[ $EXEC -eq 0 ]]; then
    TRIG=1
    echo "LT Offline. Trigger ${TRIG}"
    sleep 30
  fi
  sleep 10
done

**Comment by jooola** [comment] 2022-07-13 10:50
@VladislavF I think you have an installation problem. The schedule is passed to playout using 2 ways, one the legacy app **pushes** to playout using the message queue (this always happen if you update the schedule or edit the stream settings), and another one where nothing changed on the legacy side and playout **pulls** the future schedules as it don't know what to play.

Since your setup fails when playout pulling from legacy, the streams will always fails unless you tweak or force a schedule push.

 You should check around the api service and the apache config.

**Comment by jooola** [comment] 2022-07-13 10:53
The `psycopg2.InterfaceError: cursor already closed` error will probably be solved in alpha.13, as we replaced uswgi which is likely to be the source of this problem.

**Comment by VladislavF** [comment] 2022-07-13 16:44
Okay, I will open a new issue later today when I can pull all the logs off the machine. Otherwise, the core issue seems to be with regard to the api service since both apache2 and liquid soap report being unable to connect to localhost:8081 and since that fails, the schedule fails to update and hence playout stops.

**Comment by jooola** [comment] 2022-07-13 16:46
> Okay, I will open a new issue later today when I can pull all the logs off the machine. Otherwise, the core issue seems to be with regard to the api service since both apache2 and liquid soap report being unable to connect to localhost:8081 and since that fails, the schedule fails to update and hence playout stops.

If you installed libretime recently, you could be facing https://github.com/libretime/libretime/issues/1891 but that's a wild guess.

**Comment by VladislavF** [comment] 2022-07-14 00:19
@jooola you're a genius, forcing pip to downgrade and re-install a lower version of django-filter as in #1891 seems to have resolved the issue of the stream going offline. At least in so far as I've seen in the last 5 or so hours.

**Comment by jooola** [comment] 2022-07-15 11:58
@samkitk Could you tell us if the newer versions of LibreTime solve you issue ?

**Closed** 2023-04-04 01:24 UTC
Labels: is: bug, status: stalled
