### ISSUE TITLE
python2 support stopped

### ISSUE THREAD

**Issue by vijaykumarchettiar** [LibreTime/libretime#965] opened 2020-03-01 15:54 UTC
The libretime uses the python 2 libraries which are outdated and no more support in Ubuntu OS versions. The installation of the libretime stops at Python2 no longer supported. please see the attachment for reference. My aws instances has Ubuntu 16.04 xenial packages with python3.x. when libretime installation starts the python2.7 automatically installed and at one point of time this error throws. please let me know, how we get the updated libretime distribution for python 3

https://pythonclock.org/
![image](https://user-images.githubusercontent.com/4214357/75628848-cb605700-5c02-11ea-8a1e-3812c4baaff5.png)

**Comment by paddatrapper** [comment] 2020-03-01 17:34
Duplicate of #257, please test #951

**Closed by paddatrapper** 2020-03-01 17:34 UTC
Labels: bug
