### ISSUE TITLE
Airtime Upgrade

### ISSUE THREAD

**Issue by petegriggs** [LibreTime/libretime#374] opened 2017-11-29 16:17 UTC
Hello,

I have read the doc's but can't see a clear way to upgrade from Airtime 2.5.1 to LibreTime. Can someone let me know?

Thanks
Pete.

**Comment by Robbt** [comment] 2017-11-29 18:10
So this isn't a fully tested process but most of us have had luck simply running the install over an existing Airtime install. This should update the database and if you kept all of the default database and file locations it should work for the most part.

The only caveat is that airtime-import doesn't have a functional version for LibreTime so if your workflow depends upon that then it won't work out of the box.

This also hasn't been fully vetted and tested with all of the different distributions it was possible to run Airtime on. Your best bet might be to backup your server onto a new one and then run the install process, at the very least back up your 2.5.1 install database and files so you can revert if LibreTime doesn't work for some reason.

**Comment by Robbt** [comment] 2017-12-01 15:12
This is a duplicate of #71 , if you have further support questions please post them on the [discourse forum](http://discourse.libretime.org)

**Closed by Robbt** 2017-12-01 15:12 UTC
