### ISSUE TITLE
No Adress showing after install

### ISSUE THREAD

**Issue by JJK1231** [LibreTime/libretime#632] opened 2018-12-04 17:04 UTC
After the installation was complete. There was not an adress where i can find Libretime. I have tried to do localhost:8080 but that wasn't working. Can u help? I work on a Raspberry PI 3b+

**Comment by JJK1231** [comment] 2018-12-04 17:34
I am not very smart at this. When i do _sudo netstat -alntp_ i get this:

PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      647/sshd        
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      475/cupsd       
tcp        0      0 127.0.0.1:32600         0.0.0.0:*               LISTEN      2837/Plex Tuner Ser
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      634/postgres    
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      1348/icecast2   
tcp        0      0 127.0.0.1:44737         0.0.0.0:*               LISTEN      10031/Plex Plug-in 
tcp        0      0 127.0.0.1:40005         0.0.0.0:*               LISTEN      10096/Plex Plug-in 
tcp        0      0 127.0.0.1:40037         0.0.0.0:*               LISTEN      1646/Plex Plug-in [
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      800/beam.smp    
tcp        0      0 127.0.0.1:43181         0.0.0.0:*               LISTEN      9991/Plex Plug-in [
tcp        0      0 0.0.0.0:1104            0.0.0.0:*               LISTEN      2833/Plex DLNA Serv
tcp        0      0 0.0.0.0:32400           0.0.0.0:*               LISTEN      1235/Plex Media Ser
tcp        0      0 127.0.0.1:45553         0.0.0.0:*               LISTEN      9914/Plex Plug-in [
tcp        0      0 127.0.0.1:32401         0.0.0.0:*               LISTEN      1235/Plex Media Ser
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      717/epmd        
tcp        0      0 127.0.0.1:40147         0.0.0.0:*               LISTEN      9962/Plex Plug-in [
tcp        0      0 127.0.0.1:5939          0.0.0.0:*               LISTEN      1322/teamviewerd
tcp        0      0 0.0.0.0:32469           0.0.0.0:*               LISTEN      2833/Plex DLNA Serv
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1103/dnsmasq    
tcp        0      0 127.0.0.1:55598         127.0.0.1:32400         TIME_WAIT   -               
tcp        0      0 127.0.0.1:54001         127.0.0.1:4369          ESTABLISHED 800/beam.smp    
tcp        0      0 127.0.0.1:5939          127.0.0.1:51618         ESTABLISHED 1322/teamviewerd
tcp        0      0 127.0.0.1:51618         127.0.0.1:5939          ESTABLISHED 1405/           
tcp        1      0 127.0.0.1:42158         127.0.0.1:40037         CLOSE_WAIT  2833/Plex DLNA Serv
tcp        0      0 127.0.0.1:4369          127.0.0.1:54001         ESTABLISHED 717/epmd        
tcp        0      0 192.168.1.16:46970      37.252.255.204:5938     ESTABLISHED 1322/teamviewerd
tcp        1      0 127.0.0.1:42156         127.0.0.1:40037         CLOSE_WAIT  2833/Plex DLNA Serv
tcp        0      0 127.0.0.1:51774         127.0.0.1:5939          ESTABLISHED 4681/TeamViewer_Des
tcp        0      0 192.168.1.16:52556      82.94.168.56:443        ESTABLISHED 1235/Plex Media Ser
tcp        0      0 127.0.1.1:4369          127.0.0.1:41447         TIME_WAIT   -               
tcp        0      0 192.168.1.16:60428      195.244.97.234:5938     ESTABLISHED 1322/teamviewerd
tcp        0      0 127.0.0.1:55596         127.0.0.1:32400         TIME_WAIT   -               
tcp        0      0 127.0.0.1:5939          127.0.0.1:51774         ESTABLISHED 1322/teamviewerd
tcp6       0      0 :::22                   :::*                    LISTEN      647/sshd        
tcp6       0      0 ::1:631                 :::*                    LISTEN      475/cupsd       
tcp6       0      0 :::5672                 :::*                    LISTEN      800/beam.smp    
tcp6       0      0 :::80                   :::*                    LISTEN      1450/apache2    
tcp6       0      0 :::4369                 :::*                    LISTEN      717/epmd

**Comment by Robbt** [comment] 2018-12-04 17:43
Have you tried http://localhost without the port ?
It appears that apache2 is only listening with tcp6.

What about sudo service httpd status ?

**Comment by JJK1231** [comment] 2018-12-04 19:13
when i type _sudo service httpd status_ i get this:

● httpd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

**Comment by Robbt** [comment] 2018-12-04 19:19
ok, sorry what about sudo service apache2 status ?

**Comment by JJK1231** [comment] 2018-12-04 19:35
I have did _systemctl daemon-reload_ and i get this:

● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: active (running) since di 2018-12-04 18:37:08 CET; 1h 57min ago
     Docs: man:systemd-sysv-generator(8)
   CGroup: /system.slice/apache2.service
           ├─1506 /usr/sbin/apache2 -k start
           ├─1544 /usr/sbin/apache2 -k start
           ├─1545 /usr/sbin/apache2 -k start
           ├─1546 /usr/sbin/apache2 -k start
           ├─1547 /usr/sbin/apache2 -k start
           └─1548 /usr/sbin/apache2 -k start

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-15/15 (END)

**Comment by Robbt** [comment] 2018-12-04 20:52
Ok, so apache2 is running. You might need to check the config file for it.
Also maybe try ./install -fiap to install without the prompts, it's possible that the apache config wasn't generated correctly.

**Comment by JJK1231** [comment] 2018-12-04 21:06
When is run  _./install -fiap_ i get this:

bash: ./install: No such file or directory

I'm so sorry but it's difficult for me.

**Comment by Robbt** [comment] 2018-12-05 09:07
Ahh ok I meant from inside of the LibreTime directory, basically rerun the install command with those flags.

**Comment by JJK1231** [comment] 2018-12-05 09:48
when i instal i get at last:
----------------------------------------------------
                * Basic Setup DONE! *                
                                                     
 To get started with Airtime, visit             
 or, if you've set up your own web configuration,    
 the Airtime webroot on your webserver               
-----------------------------------------------------

**Comment by JJK1231** [comment] 2018-12-05 09:55
But it works not

**Comment by JJK1231** [comment] 2018-12-05 13:10
I use my PI to go to the site. I have installed Ubunutu mate because Raspberry had also problems with Libretime so i thought that is was good to install ubuntu. I does'nt make sense of witch device i use to go to the site everything don´t work. I have install -fiap done but it´s stil not working. Where can i find the config file that u will see?

**Comment by JJK1231** [comment] 2018-12-05 13:35
with Raspberry i mean Raspberrian, sorry.

**Comment by Robbt** [comment] 2018-12-05 18:09
What happens when you go to http://localhost or http:/127.0.0.1. do you get a blank page an error or no response ?

**Comment by Robbt** [comment] 2018-12-05 18:11
Evidently the netstat showing apache2 running only on ipv6 is expected behavior [link](https://unix.stackexchange.com/questions/106502/apache2-does-not-run-on-ipv4-tcp-port#106578)

**Comment by JJK1231** [comment] 2018-12-05 18:14
It works! But i have now two things. When i do hostname -i i get 127.0.1.1 but that isn’t my ip? How Can i solve that? And i want to do my USB as The storage for Libretime but thats not working

**Comment by Robbt** [comment] 2018-12-05 18:53
Great. So the the USB thing can be handled easiest by making a symbolic link of /srv/airtime/stor/ to a folder on your USB. It might be possible to change the import directory via the install but this might not work. [Here](https://www.computerhope.com/unix/uln.htm)  is a description of how ln works.

 Basically in your /srv/airtime directory you will want to 'mv stor bakstor' and then 'ln -s /FOLDERONUSB /stor' you will also need to make sure that www-data owns the USB folder. That can be accomplished with chown -r www-data /USBFOLDERMOUNT although it might not be the exact right syntax.

127.0.0.1 is your loopback IP, it always points to the machine you are own. The hostname and IP stuff is beyond the scope of Airtime but would depend a lot on what your intended use of LibreTime is.

**Comment by Robbt** [comment] 2018-12-05 19:08
I think if you run ifconfig that should show you your local address but this discussion is going outside of the scope of  any LibreTime specific issues.

**Comment by Robbt** [comment] 2018-12-06 00:13
I'm going to close this for now, if you have further support questions feel free to keep communicating on here or better yet head to the forum at http://discourse.libretime.org

**Closed by Robbt** 2018-12-06 00:13 UTC
Labels: feedback-needed
