### ISSUE TITLE
Support. Maybe Off-Topic, But Important..

### ISSUE THREAD

**Issue by ghost** [LibreTime/libretime#148] opened 2017-04-08 22:06 UTC
Is there a chat, real-time and / or forum for dev/support chat?

**Comment by Lapotor** [comment] 2017-04-08 22:33
the only thing they have is taiga and github and there site
I think a freenode irc channel would be nice and a forum too or something simular

**Comment by Robbt** [comment] 2017-04-08 22:39
Yeah, we talked about using freenode, but I didn't want to create our own channel unless we had people to hang out in it. I lurked and logged the airtime channel and almost nobody ever responded to people when they would join. But there do seem to be people using this quite a bit more often. I don't know that we want to create a separate web forum yet though even if the Issue queue is getting a little bit clogged it is still good to be able to keep track of everything in one place and we can always close issues if they end up being unique issues related to peoples unique configurations and not reproducible. On the other hand if they are identified as bugs it's good to have them in one place.

**Comment by JohnnyC1951** [comment] 2017-04-08 22:40
I got no response in the Tiaga. Nor did I get a response from 'Dev Team Members wanted'. Git Hub 'Issues' is not the place for dev & support help.
If I get 5 more folks in favour and no other response, I think I will set one up.

**Comment by Lapotor** [comment] 2017-04-08 22:46
@Robbt may use Freenode with an bot which tells you a bit on knowen issues ...
I'm an IRC user so i'm for an IRC Channel

And the forum is not for issues it is more to tell wished things or simular ...

**Comment by JohnnyC1951** [comment] 2017-04-08 22:47
And for common support issues until the docs catch up.

**Comment by Lapotor** [comment] 2017-04-08 22:49
I think GitHub issues ahould be reservated for real issues not for questions how that or that works more for hey i got this error here you should fix it ...
ya'now

**Comment by JohnnyC1951** [comment] 2017-04-08 22:50
Yes.

**Comment by JohnnyC1951** [comment] 2017-04-08 22:50
Here we are using Issues as a chatbox :\

**Comment by hairmare** [comment] 2017-04-09 06:20
I think discussion on this originally started with [taiga issue 24](https://tree.taiga.io/project/robbt-libreairwaves-airtime-fork/issue/24).

At least this way everything is in one place. Most of the questions we have been fielding here are a signs of lacking documentation more than anything else. Those are just as real as are problems with the installer and the code. The install questions are symptoms of a badly broken install process and not the users fault. I'm not sure how not posting them here will help get them fixed.

Having a non maintained IRC would be even worse than what is currently here in the issues section. A user focused mailing list (aka libretime-users) is something that I have been considering. The additional load of having to lurk in any kind of chat room doesn't seem to add up for me. What I personally do not plan on implementing is the classic forum, forums are broken by design (and have been so since the late 90ies), they have a signal to noise ratio that is really bad.

@JohnnyC1951 I sent you a GitHub invite so you can tag and assign issues. I don't think we need a larger banhammer than what the code of conduct and C4 already offer. Sorry about not getting back to you on taiga, I wasn't able to find anything there and it doesn't seem to send me mail. Which "Dev Team Members wanted" thing apart from the C4 are you talking about? Also, please open an issue if you have issues with the widgets, I haven't been able to figure out what is broken with the weekly widget.

Please feel free to create any new issues you need (like this one). I'm gonna re-open this since we really need to get something set up. I do feel strongly that it shouldn't be real-time unless we have enough folks to staff it.

**Comment by JohnnyC1951** [comment] 2017-04-09 08:18
A mailing list is pretty much just a one thread forum :(

**Comment by ronstep** [comment] 2017-04-09 09:34
I also like the idea of a forum, I'm not a Dev but do dabble with virtual box and desperate to try the new libretime but scared to ask how in here, would be good to have somewhere that user/station admins can ask advice. thanks for the good work although most of it is giggly gook to me, I read every notice, just it case it says it's ready to play with.

regards

**Comment by hairmare** [comment] 2017-04-09 09:37
Email (and per extension mailing-lists) are very much multi-threaded 😕 

Jeff Atwood [makes the argument](https://blog.codinghorror.com/civilized-discourse-construction-kit/) against forums I'm trying to get across (but he doesn't like mailing lists either). Maybe we should consider his discourse.

**Comment by bburton** [comment] 2017-04-09 14:46
What about slack.com? It's primarily meant for use within an organization.

There are lots of integrations to third-party apps and sites. For instance, a couple that would be useful ...

github.com:
> This integration will post commits, pull requests, and activity on GitHub Issues to a channel in Slack.

Travis CI:
> This integration will allow your team to receive notifications in Slack for normal branch builds, and for pull requests, as well.

Unfortunately, no integration with Taiga yet.

However, with Slack, one has to request access.

**Comment by Robbt** [comment] 2017-04-09 15:35
Hmm, I think Slack is pretty popular and can be useful but it would be more of a tool for the developers to communicate with each other and for that purpose I think Github is working quite well. Setting up a discourse forum could work but it would also mean another place for people to put their attention away from the code. In my opinion we want to try to avoid the separation between users and developers that happened with the SourceFabric forum. I am really enjoying having a single point of contact to get all of the information regarding what is happening with LibreTime and to be able to respond to issues people have. 

Part of the issue it sounds like people don't feel comfortable posting a simple request for help on something that seems serious like a github issue queue, but we could also simply come up with rules like use the "support request" tag and then we simply close the issue once it is fixed. If we create a forum and people use that but the developers don't then we run into the fragmentation of attention that we saw with Airtime. I know there were a lot of other dynamics at work other than the forum with Airtime. Personally I think that using the same platform to discuss and decide as well as code is probably preferable to creating a bunch of different channels of communication and then only having a few people use them. Whatever we use it I think it would be a good idea to find something that integrates with the github repo. Discourse offers free hosting to open-source projects but they need at least 30+ contributors and 2000 starts to qualify and a clear need for discussion. We aren't quite there - https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

If we do create something like a discourse forum and make it officially tied to the product it would be good to have it hosted and moderated in conjunction with the community guidelines and hosted on libretime.org. 

Should we officially close the Taiga.io at this point or make it explicitly clear that it is no longer being used ? So that people don't come there and expect to get a response ? I did put something in the description but there are still links to taiga.io from the Airtime forum.

I think the only issue left on taiga that wasn't transferred to github was the discussion regarding e-mail hosting and mailing lists. 

There is also the question of whether to build social media accounts for LibreTime but in my opinion until we have more people taking active roles in the development and the code is release ready and being used in production this would just distract from the development.

I think there is a lot of potential for the LibreTime community to grow, let's just try to make the right decisions about how to best foster its growth.

**Comment by Lapotor** [comment] 2017-04-09 15:46
Yeah only when you pay you have an guest access on slack.
maybe Discord or simular.

**Comment by Robbt** [comment] 2017-04-09 15:52
In reading the first reply on free discourse hosting, Jeff aka CodingHorror suggests that projects that don't quite meet the requirements can send them a message and they are willing to consider projects that have a good reason for needing discussion and an average of 5 people posting a day. We might qualify considering the nature of our fork and the fact that we have a lot of people who are used to using a forum. We can send them a request if there are enough people who think this is a good idea. I looked and through the Airtime contributions we do have 30 contributors through out the whole history of the project on github. If people can chime in as to whether they think requesting a free discourse forum hosted is a good idea then we can move forward. I'm in favor of this as it removes the additional burden from the dev team of hosting a public facing web app.

**Comment by JohnnyC1951** [comment] 2017-04-09 16:09
I can put up and host a forum at the drop of a hat!
I think it would reduce noise from the GIT and it could be clearly signposted as to when to raise an issue in the GIT. Lots of Airtime's users are DJs and the like and not that techie. I know of two who are terrified of this GIT.

**Comment by Robbt** [comment] 2017-04-09 16:21
Can you host a discourse forum on the libretime.org domain ? It's kind of a question of maintaining transparency and cohesiveness of the community. @hairmare currently controls the domain name. Where would you plan on hosting this, what software would we use and how would we moderate and interlink it with LibreTime. If we want to make it semi-official we should discuss all of this before taking any actions. I do think that the community could be well supported by a more free-form discussion forum and it could serve the interest of people doing independent web radio in general beyond simply LibreTime if well supported and used.

**Comment by Lapotor** [comment] 2017-04-09 17:20
@JohnnyC1951 @Robbt if needed i have enogh server for that too (4 server) XD so if needed i can help out with some

**Comment by JohnnyC1951** [comment] 2017-04-09 18:19
I can't easily host Discourse on my hosting reseller platform, as it uses Ruby-On-Rails, which is not allowed. I can easily do one of 2 dozen others. Maybe Lapotor's server is more suitable if Discourse is required?

**Comment by Lapotor** [comment] 2017-04-09 18:46
if wanted i can set it up tomorrow morning

**Comment by JohnnyC1951** [comment] 2017-04-09 18:52
Works for me :) I suggest you also put in an 'Off Topic', 'Member Contributions [code]' and 'Listen to my Station' as well as the usual stuff.

**Comment by Robbt** [comment] 2017-04-09 19:01
I could easily set one up as well, I have a number of servers but I'd rather wait until there is a consensus on it. I'd also prefer to try to get hosting via the discourse people for free so that we can be assured of the availability and configuration. This is just if the site is going to serve as any kind of official forum for LibreTime. If someone wants to setup something independently of course they are free to do so, it should just be labelled as unofficial or whatnot. What I would propose is if there are enough people interested we contact Discourse on behalf of the project to apply for free hosting. If they accept it cool, we get hosting, if they don't think we are big enough we decide on the best hosting solution that provides stability, off-site backups and administrative access to multiple project team members.

**Comment by JohnnyC1951** [comment] 2017-04-09 21:39
We could also do the whole thing in Google's stuff for free based on Hangouts
Discourse sounds pretty expensive to do what we really need. An own-hosted one is really cheap or free, off the back of one of our servers.
Backing up the data off-site to the 'Libretime Illuminati' would mean it could be re-hosted up somewhere else in no time.
Hooking a sub-domain like forum.libretime.org means that the group maintains control but it can be hosted anywhere through the magic of DNS.

**Comment by Lapotor** [comment] 2017-04-09 21:46
Yeah sure but there is a free host possibility if you are a non-profit thing than you can ask them if they do it for free.
And I think it would be nice if someone of us host the things but if **(I don't think someone will do that)** that guy have a "bad day" or else and he delete the forum ... ya'know

**Comment by gusaus** [comment] 2017-04-09 21:46
@Robbt and @hairmare have talked about this a bit. Personally I think a combo of Discourse and Slack would be a good way to facilitate collaboration between devs and also engage the user community. Both of which are potential components for a developer portal we're gearing up to build with the [OpenCollective community](https://github.com/opencollective/opencollective). The latter could also provide a way to grow the community, sustain the project, and associated overhead such as hosting costs.

**Comment by JohnnyC1951** [comment] 2017-04-09 21:56
This is becoming a talking shop. What if the lead devs have a bad day and wiped it? Geesh. Even one of the lead Devs offered to host it. FFS will someone make a decision and do it? We could have had one up hours ago :\

**Comment by Lapotor** [comment] 2017-04-09 22:03
@gusaus yeah I think this would be the best combo.

**Comment by JohnnyC1951** [comment] 2017-04-09 22:08
Slack is a trap. Look at the costs. The free one isn't really enough and then its $6+/user/month. 10 or so devs = $60+/m= >$700/y

**Comment by JohnnyC1951** [comment] 2017-04-09 22:10
Mattersmost looks promising, open source, free and seems to do the same thing

**Comment by gusaus** [comment] 2017-04-09 22:18
Most of the OSS communities I'm part of are using the free version of Slack. Including one that has almost 3k users. For a community this size, I don't think there will be a need for the paid version.

As there at least seems to be consensus around Discourse. @Robbt possibly this is something we can help with. Let me know.

**Comment by hairmare** [comment] 2017-04-09 22:24
I see Slack as a trap as well. I've used HipChat in the past but I feel it's just as much a trap. IMO Mattermost is quite promising. OTOH IRC and jabber/xmpp have both been available for quite some time and I personally don't see much more value in an integrated solution like Slack, HipChat or Mattermost (at least not for our specifics).

**Comment by JohnnyC1951** [comment] 2017-04-09 22:40
I will leave you guys to it and butt right out. When running large projects, I have always gone for open-source, own control over hosting, solid project management, reliability and maturity (bug free) over 'coolness' and 'latest'. Have fun.

**Comment by Robbt** [comment] 2017-04-09 22:43
@hairmare If you want to apply for free hosting from Discourse feel free to take the initiative, I will not get around to it today or tomorrow at this point. I think that we could appeal that since we are a new fork we are small but we have a large community of users that are used to using a forum, and point to the Airtime forum. I definitely think we will have at least 4-5 posters per day if this discussion thread is any indication so hopefully they'd make an exception for us. On the other hand if they say no we could simply host it ourselves without too much work. I don't really care who individually hosts it as long it is backed up regularly to prevent catastrophic failures. Later.

**Comment by hairmare** [comment] 2017-04-09 22:48
I'm only hosting DNS on libretime.org (and the domain account has an email behind it that all Administrators can access). The docs are built using mkdocs from what is in `docs/` and they get published to github pages by travis-ci automatically.

@Lapotor If you would like to make a nice landing page for libretime.org, feel free to PR the changes. I think it should be possible starting from the mkdocs setup we already have and creating a distinct template for index.md. Regarding your offer for hosting, lets figure out if we can get something saas like for free before we start rolling our own infra. 

@Robbt I'll look into applying for a Discourse... That'll need to wait until tomorrow as it's getting pretty late here as well.

**Comment by hairmare** [comment] 2017-04-11 04:42
Quite frankly after half of this thread was deleted I am not very motivated to give this the priority it deserves and I'd rather focus on development.

It is very important to us that we seek consensus on such issues and we'd rather not implement anything based on rash decisions. While reaching consensus does take some time it is of utmost importance to us. This is why I reopened this issue after it was closed without waiting for any real discussion. Keep in mind that not all of us live in the same timezone.

We ask Contributors to conduct themselves in a way that is deemed appropriate in a professional setting and to to be respectful of differing viewpoints. I see the contents of the deleted posts as needlessly argumentative or hostile and am asking the offending party self-correct their behavior.

I'll keep this issue open as I plan on revisiting this as we get closer to a stable release.

**Comment by hairmare** [comment] 2017-04-11 04:53
@ronstep Sorry for not getting back to you earlier. Please don't be afraid to ask for help by creating issues if you run into problems. While I understand that most of this might be too technical for non devs, those kind of contributions really help us in figuring out where the documentation is lacking.

**Comment by JohnnyC1951** [comment] 2017-04-11 12:00
@hairmare I was simply removing the very stuff that you yourself called offensive in another thread, but even that seems to be wrong. I have removed myself from the group and it's activities and will make any code extensions  publicly available elsewhere under a GNU. Sorry for any offence.

**Comment by Tucker2015** [comment] 2017-05-26 23:43
I could create a NodeBB forum on my server if that's ok with you until you get something going ?

**Comment by Robby262** [comment] 2017-05-26 23:56
I created a full working one for everybody already. They choose not to use it

**Comment by ned-kelly** [comment] 2018-09-26 01:39
Hi guys, I think we should bring slack back into to the picture for general chat (Not so much form talk where you want a conversation history, but more so a general chat when developing, realtime support / being able to do a phone call / screen share with people etc).

I'd be happy to set this up properly for everyone based on the previous - https://libretime.slack.com/ account that was setup (could some one add/invite me as a member/team admin perhaps?)

The answer to allowing users join is quite simple -  we just run something like this on a server somewhere https://github.com/outsideris/slack-invite-automation which goes an creates the invite required for users (so we don't need to manually add/approve people).

**Comment by Robbt** [comment] 2018-09-26 17:50
I would prefer ZulipChat or mattermost. They're open source and nearly identical to slack in terms of capability. Anyone familiar with ZulipChat it offers free hosting but limits the messages to 10,000 before it starts deleting the old ones. Since any decisions we make etc should be ported over to the github and reflected as code changes then I don't think this is an issue. I think @gusaus might have set up the libretime slack but I don't think I ever logged in or got admin on it.

I'd be happy to setup a free zulipchat account for libretime if people are OK with that as an alternative to slack.

**Comment by Robbt** [comment] 2018-09-26 17:54
Actually Zulipchat offers free hosting akin to their commercial service for open source projects - https://zulipchat.com/for/open-source/

**Comment by gusaus** [comment] 2018-09-28 07:07
I completely forgot I set up https://libretime.slack.com/

Personally I think Slack would be a good choice if we want to engage both
developers and end users/community. Pretty much all the other OSS
communities/projects I'm part of/aware of are using. I'd be happy to make
other folks admin if it seems like a good idea to dust off and use.

**Comment by Robbt** [comment] 2018-10-04 18:59
Before we decide upon using slack in any official manner can we at least have a discussion about the pros and cons of it vs. Zulipchat.

Pros for slack
It's popular and familiar
Gus already setup LibreTime.slack.com

Cons for slack
It's proprietary software
It can be noisy and require constant interaction to be useful

Pros for Zulipchat
It's open-source and can be self hosted
It offers free commercial hosting for open source projects
It provides better threading of subjects than slack

Cons
It isn't as popular as slack

I am probably just biased because i have found slack to be less than optimal in my experience but I'd like some feedback from others before we officially embrace slack vs Zulipchat or another chat based platform. 

I am in favor of setting something up and if enough people prefer Slack then we can add it as an official part of LibreTime. But I'd like it to happen via a decision making process not just because Gus set it up already.

So I'm going to reopen this. Please chime in everyone who cares to.

**Comment by macbroadcast** [comment] 2018-10-04 19:16
> @gusaus, sent you a PM.

How you send a PM ? :thinking:

**Comment by gusaus** [comment] 2018-10-04 20:02
One of the reasons I proposed Slack was it was every OSS community I was part of was using. In the year or so since, the only community where noise and losing logs/conversations is an issue is Drupal (free plan / almost 10000 users). Every other OSS project has been doing perfectly fine on the free plan... most never run into these limits https://get.slack.help/hc/en-us/articles/115002422943-Message-and-storage-limits-on-the-Free-plan

Noise, getting lost in conversations, is really a non-issue. Even in Drupal there are ways that you can easily save and track important conversations. 

The other thing to remember is LibreTime already has a few options to get nonprofit status... so it should qualify for an upgrade if the community is large/active enough to justify. https://get.slack.help/hc/en-us/articles/204368833

If everybody wants to use an OSS option for development, I still think Slack would a good for on-boarding and interacting with end users, stations, and potential contributors. 

I'm good with whatever would be best for increasing activity and collaboration.

**Comment by ned-kelly** [comment] 2018-10-05 00:06
+1 for slack here

It's the best option for non-technical people, the apps and everything that comes with it just works properly on iphone, android etc -- nothing against Zulipchat but Slack is the more common of the two and I'd suggest going with it.

You'll find people that download Libretime also won't always have an active Github profile -- We can also just use (this)[https://github.com/outsideris/slack-invite-automation] to automate the access to slack (These guys here are using it like this also -- https://comma.ai/)

**Comment by frecuencialibre** [comment] 2018-10-05 00:14
just joined slack: https://join.slack.com/t/libretime/shared_invite/enQtNDQ4OTk0Nzc4NzU0LWY2MTE3ZTEwMGJlMjMxZmU2ZDRiNTgwMTM2MDllMzRkZTNjM2YzNmEwYTY1Y2ZlMDI4NmMxNTM4YjQ5YjYwNmU

**Comment by hairmare** [comment] 2018-10-06 11:44
Slack only preserves a limited amount of history in their default plans. Slack is also the less "Libre" of both options.

I'm not sure I'll be able to even come close to keeping up to date in the slack as my slack client is already completely overloaded with business slack groups. Zulip (which I had't known before) does seem to solve some of these issues nicely. I'm ok with Slack and will set the client up properly one I'm back at my main slack machine. 

I'll see is I have enough leisure time to really use Slack. It feel like it's signal to noise ratio is problematic at best. I think this is probably another communications thing where devs and non-devs usually don't agree.

**Comment by gusaus** [comment] 2018-10-06 20:56
Based on the input so far (and the fact most folks in this discussion have since joined), I'd recommend we keep using Slack for the following reasons - 

- most (all?) developers are already using 
- non-developers/community members are already using or familiar with Slack
- there are many ways to alleviate concerns about noise, not being able to track conversations, losing logs

Zulipchat looks very cool (and it could eventually be where a large, active group might want to use specifically for development), but it might not be something non-developers, end-users, community folks (already using Slack) would want to manage.

Think we can centralize on Slack for now?

**Comment by Robbt** [comment] 2018-10-07 01:37
I'm willing to go along with a semi-official slack channel if it is mainly used for coordinating support in real time and doesn't become required in any way for making official decisions etc. For example and discussions that happen on slack that relate to specific patches or proposals should be transposed onto a github issue etc.

I personally don't find Slack to be that much easier to use than the discourse forum and while I think zulipchat would be just as easy to use for non-developers I'll go along with Slack and in fact joined the instance. If for some reason we decide that we want to move to Zulipchat in the future they support importing from Slack as well. So yeah, Slack.

**Closed by Robbt** 2018-10-07 01:37 UTC
