### ISSUE TITLE
Uploading tracks, stops randomly.

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#3] opened 2017-02-20 10:08 UTC
When uploading tracks, thru uploader file process stops randomly. It can stop on first file or after upload 20 tracks and stop. Uploading can be resumed only after canceling uploading hanged file. 

Got this in zendphp.log
```
2017-02-19T13:02:12+03:00 INFO (6): ***radio****.com Checking autoplaylist poll
2017-02-19T13:02:20+03:00 ERR (3): ***radio****.com [MediaController.php:140 - postAction()] - chmod(): No such file or directory
#0 [internal function]: exception_error_handler(2, 'chmod(): No suc...', '/usr/share/airt...', 943, Array)
#1 /usr/share/airtime/application/models/StoredFile.php(943): chmod('', 420)
#2 /usr/share/airtime/application/services/MediaService.php(40): Application_Model_StoredFile::moveFileToStor('', 'Quanta - Center...', false)
#3 /usr/share/airtime/application/models/airtime/CcFiles.php(160): Application_Service_MediaService::importFileToLibrary('http://***radio****....', '', 'Quanta - Center...', 1, false)
#4 /usr/share/airtime/application/models/airtime/CcFiles.php(99): CcFiles::createAndImport(Array, '', 'Quanta - Center...')
#5 /usr/share/airtime/application/modules/rest/controllers/MediaController.php(124): CcFiles::createFromUpload(Array)
#6 /usr/share/php/libzend-framework-php/Zend/Controller/Action.php(516): Rest_MediaController->postAction()
#7 /usr/share/php/libzend-framework-php/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('postAction')
#8 /usr/share/php/libzend-framework-php/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /usr/share/php/libzend-framework-php/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /usr/share/php/libzend-framework-php/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /usr/share/airtime/application/airtime-boot.php(88): Zend_Application->run()
#12 /usr/share/airtime/public/index.php(66): require_once('/usr/share/airt...')
#13 {main}

/USR/SHARE/AIRTIME/APPLICATION/MODELS/STOREDFILE.PHP(943): CHMOD('', 420)
```

**Comment by hairmare** [comment] 2017-02-20 17:21
Original issue is in [taiga#12](https://tree.taiga.io/project/robbt-libreairwaves-airtime-fork/issue/12).

Like I said there:

> There might be a problem with using ~~~~/src~~~~/srv/temp as upload_tmp_dir 
> rather than /tmp, I'm not 100% sure that the path is not hardcoded 
> anywhere.

It looks like the permission changing code is in LibreTime at [276a69a/airtime_mvc/application/models/StoredFile.php#L943](https://github.com/LibreTime/libretime/blob/276a69aa1bef527260efc170d7caab7d04b4ca13/airtime_mvc/application/models/StoredFile.php#L943).

It seems LibreTime is trying to change the permissions on the file before uploading it.

Can you please post the results of `ls -alZ /srv/temp `? I'd like to ensure that neither SELinux is active and that /srv/temp belongs to a user who has write permission through apache.

**Comment by korotkov13** [comment] 2017-02-20 17:27
i it was /tmp but i thought that changing folder will help.

otal 17900
drwxr-xr-x 2 www-data www-data ?     4096 Feb 20 20:27 .
drwxr-xr-x 4 www-data www-data ?     4096 Feb 19 03:58 ..
-rw------- 1 www-data www-data ?  2881997 Feb 20 20:27 phpFZMR0N
-rw------- 1 www-data www-data ? 15410564 Feb 20 20:27 phpN1vmUT
-rw------- 1 www-data www-data ?       98 Feb 19 05:02 zend_cache---internal-metadatas---Zend_LocaleL_ru_day_
-rw------- 1 www-data www-data ?       98 Feb 19 05:02 zend_cache---internal-metadatas---Zend_LocaleL_ru_month_
-rw------- 1 www-data www-data ?       98 Feb 19 05:02 zend_cache---internal-metadatas---Zend_LocaleL_ru_month_gregorian_format_abbreviated
-rw------- 1 www-data www-data ?      251 Feb 19 05:02 zend_cache---Zend_LocaleL_ru_day_
-rw------- 1 www-data www-data ?      300 Feb 19 05:02 zend_cache---Zend_LocaleL_ru_month_
-rw------- 1 www-data www-data ?      246 Feb 19 05:02 zend_cache---Zend_LocaleL_ru_month_gregorian_format_abbreviated

**Comment by korotkov13** [comment] 2017-02-20 17:28
phpFZMR0N this file already hanged.

**Comment by korotkov13** [comment] 2017-02-20 17:48
I'm not sure SELinux is working. I got a cheap vps.:(

**Comment by hairmare** [comment] 2017-02-20 17:51
Weird, so you don't have SELinux active and the folder and files belong to the right user 😩 

I was hoping for an easy fix :/ Looks like I'll have to do some real debugging first.

The actual file name gets grabbed from `$_FILES` (*ugh*) in [276a69a/airtime_mvc/application/models/airtime/CcFiles.php#L95-L96](https://github.com/LibreTime/libretime/blob/276a69aa1bef527260efc170d7caab7d04b4ca13/airtime_mvc/application/models/airtime/CcFiles.php#L95-L96).

I already see some cleanup there that should be done, but will need to set up a proper LibreTime dev environment first.

Right now these are the tasks that I see a need of taking care first.
* [ ] check why `$_FILES` was used rather than either [`move_uploaded_dir()`](http://php.net/manual/en/function.move-uploaded-file.php) or [`Zend_File_Transfer`](https://framework.zend.com/manual/1.12/en/zend.file.transfer.introduction.html) 
* [ ] Switch to either `Zend_File_Transfer`, `move_uploaded_file()` or at the very least implement some code that checks for error entries in `$_FILES` as described in [POST method uploads](http://php.net/manual/en/features.file-upload.post-method.php) in the PHP manual.

From what I remember, `Zend_File_Transfer` works fine, it was probably not written at the time `$_FILES` was implemented as it was a later addition to ZF1.

**Comment by hairmare** [comment] 2017-02-20 17:58
Also, I'm not sure if the above will really fix the issue. At the very least it will give us an error message that explains why the call to `chmod()` is getting passed an empty string and we can convey a proper message before letting it fail with a stacktrace.

Does your original filename contain any UTF8 chars (ie. like ü or any cyrillic)? I'm pretty sure there are issues with those later on during ingest (at least in media-monitor, I haven't checked analyser yet). If they do you might want to try some non-UTF8 chars.

Have you seen any patterns in the files that fail? If you could post filenames of some that work and some that hang, maybe I can see something.

**Comment by korotkov13** [comment] 2017-02-20 18:02
I have EN_UTF8 encoding, but tracks i uploaded doesn't contain cyrilic or other non EN letters.

**Comment by hairmare** [comment] 2017-02-20 18:04
Since UTF8 is basically ASCII with the additional provision for multibyte chars, you should be fine there. On a byte level, your filenames are plain ASCII 😃 

Let me know if you figure out any other pattern in the filenames.

**Comment by korotkov13** [comment] 2017-02-20 18:48
The problem is not with filenames. It can be with one file, and another time this file passes well.

**Comment by hairmare** [comment] 2017-02-20 19:05
It might not be the filename, that's just a hunch. I just hope there is a pattern...

If you can't figure out one, that's ok, I'll add some patches to help debug this soonish. It'll probably take a while though (my dev box is still on `2.5.x`) and I want to test/fix this in LibreTime and not my old legacy fork (the box is also really outdated).

**Comment by paraenggu** [comment] 2017-02-20 20:15
Just a shot in the dark since `$_FILES['file']['tmp_name']` seems to be empty: What's the size of the file that fails to upload and what's your value of PHP's `upload_max_filesize` setting?

**Comment by korotkov13** [comment] 2017-02-20 20:19
php_value post_max_size 700M

**Comment by paraenggu** [comment] 2017-02-20 20:38
What about the file size and the other values? If you don't know the other PHP values, create a PHP script (for example `info.php`) within your webroot and add the following content to it:

```php
<?php
phpinfo();
?>
```

Then navigate your browser to the newly created script's URL and upload the output somewhere.

**Comment by korotkov13** [comment] 2017-02-20 20:42
https://drive.google.com/file/d/0Bw0n8K3oIt3iZ2QwcmRrUGRxSEE/view?usp=sharing

**Comment by paraenggu** [comment] 2017-02-20 21:04
OK, they all look good (unless you have very large files) - would have been too easy :-) I guess you'll have to wait until @hairmare has his dev box up and running and can properly debug this.

**Comment by korotkov13** [comment] 2017-02-20 21:05
Thanks for respond! Hope we'll find the cause.=)

**Comment by paraenggu** [comment] 2017-02-20 21:40
Last guess for tonight: After how much time does the upload fail? Is it more or less the same or randomly?

**Comment by korotkov13** [comment] 2017-02-21 07:23
It's randomly. Could be the firs track or 15th, second uploading thread could uploading as well until it hangs too. It can be after 10-15 uploads.

**Comment by paraenggu** [comment] 2017-02-21 08:09
That's understood, but after how much time in seconds or minutes? I would like to rule PHP's [max_input_time](http://docs.php.net/manual/en/features.file-upload.common-pitfalls.php) out, which is set to 60 seconds in your case.

**Comment by hairmare** [comment] 2017-02-21 19:47
As per https://github.com/LibreTime/libretime/issues/3#issuecomment-281143417 I have checked what is up with not using Zend_File_Transfer or even move_uploaded_dir().

Turns out, since LibreTime relies on the distro installing zf1 it is not available in the rather old version normally used by LibreTime.

While I was not able to reproduce the issue at hand, I was able to add some error handling based on Zend_File_Transfer that should help narrow this down.

The problem is, I'll have to update ZF1 to 1.12 before we can use this. The changes from ZF1 should not be too large, I will need to touch all controllers though.

I created a issue on the ZF1 changes https://github.com/LibreTime/libretime/issues/4.

**Comment by korotkov13** [comment] 2017-02-22 08:55
Sorry for silence. Got a lot of work.
> Use Zend_File_Transfer instead of $_FILES 
So I can change these files and check if it will work?

**Comment by hairmare** [comment] 2017-02-22 09:19
> Sorry for silence. Got a lot of work.

No worries.

> So I can change these files and check if it will work?

If you can, I'd be glad if you give them a try. If not, I'll do some more testing on my side and PR them later this week.

Most likely it won't work, I'm hoping it indicates what's wrong in the log.

**Comment by korotkov13** [comment] 2017-02-22 13:44
I don't see changes in zendphp.log
It only show this errors every 2 minutes.
017-02-22T16:16:19+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:16:19+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:16:19+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:18:22+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:18:22+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:18:22+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:20:22+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:20:22+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:20:22+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:22:22+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:22:22+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:22:22+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:24:19+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:24:19+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:24:19+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:26:22+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:26:22+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:26:22+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:28:23+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:28:23+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:28:23+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:30:23+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:30:23+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:30:23+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:32:19+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:32:19+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:32:19+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:34:23+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:34:23+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:34:23+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.
2017-02-22T16:36:23+03:00 INFO (6): orokoro.ru Checking autoplaylist poll
2017-02-22T16:36:23+03:00 INFO (6): orokoro.ru Checking to run Auto Playlist
2017-02-22T16:36:23+03:00 ERR (3): orokoro.ru [ApiController.php:34 - init()] - Session already started for an API request. Check your code because this will negatively impact performance.

**Comment by hairmare** [comment] 2017-02-22 15:03
To clarify, do you still have the `chmod(): No such file or directory` in zendphp.log or is it gone?

I think the "Session already started..." error is unrelated, it's probably just some frontend thing that's trying to poll the server. The performance argument in the message seems a bit shallow.

**Comment by korotkov13** [comment] 2017-02-28 11:57
> chmod(): No such file or directory

Yes it's gone.
Sorry for late answer. a lot of work(((

**Comment by hairmare** [comment] 2017-02-28 12:51
> Yes it's gone.

And uploading works now?

**Comment by korotkov13** [comment] 2017-02-28 13:36
Unfortunately no. It still hanging without any logical sequence.
I will try to make a clear install and check.

**Comment by Robbt** [comment] 2017-02-28 14:32
Indeed based upon the log messages I can tell this is from the branch that I put together, not the LibreTime specific fork as we haven't ported the AutoPlaylist stuff. I need to put together another commit with a few install script fixes for the install from the LibreTime branch to work. Thanks for testing.

**Comment by hairmare** [comment] 2017-03-04 10:24
Now that we have tests running and pinned the zf1 version, I opened up a PR on the debug commit.

There are still a few more issues we need to iron out before libretime@master is en par with the installed tarball, but I'll cut a release a soon as all that is sorted.

I think it's mostly id3 tagging in downloaded podcasts and Robbs autodj feature that are not already in a pr somewhere. The installer will probably also need one final cleanup pr after everything is merged.

I hope the release will fix the issues because it gets you to use the latest zf1 version that was published and is less stale than what was in ubuntu.

If you want to try this now you can do the following. Be warned that you might not have a clean upgrade path to the release if you do this.

```bash
composer require zendframework/zendframework1
web_root="/usr/share/airtime" # or what you used as --web-root
cp -R vendor ${web_root}/../
sudo apt-get purge libzend-framework-php
```

**Comment by korotkov13** [comment] 2017-03-04 12:56
do i need to type it on fresh install?
I tried on test vps and now no login page loading.

**Comment by hairmare** [comment] 2017-03-04 13:01
You might want to try these kinds of things on a local virtual machine and not your production rig.

Do you have a `/usr/share/airtime/vendor/zendframework` dir now?

You can probably get the login page back by running `sudo install libzend-framework-php`, but the new vendor would not be installed properly.

**Comment by korotkov13** [comment] 2017-03-04 13:04
It's running on test vps.
no there is no zendframework in /usr/share/airtime/vendor/ dir

**Comment by hairmare** [comment] 2017-03-04 13:06
Is there one on `vendor/`? What output did you get from running all the commands?

**Comment by korotkov13** [comment] 2017-03-04 13:07
it's my mistake. I didn't opened the right path before typed commands.
Trying now. will report soon.

**Comment by hairmare** [comment] 2017-03-04 13:08
Oh, also, I just noticed it should end up on `/usr/share/vendor` (without the `airtime` part).

**Comment by hairmare** [comment] 2017-03-04 13:10
Aaaaand, the API might also be broken afterwards :/ Lets see if uploading works and I'll see if I can help you sort the api. 😟

**Comment by korotkov13** [comment] 2017-03-04 13:21
/usr/share/vendor is present but nothing works. can't access to login page.

**Comment by korotkov13** [comment] 2017-03-04 13:21
I can reinstall and try make it on clean

**Comment by hairmare** [comment] 2017-03-04 13:26
The master branch does not have the autodj yet and the install needs the workaround from https://github.com/LibreTime/libretime/issues/24#issue-211874132.

**Comment by hairmare** [comment] 2017-03-04 13:28
The podcast download name tagger is also missing, but you get to use the support chat during sourcefabrics business hours :trollface: (please don't)

**Comment by korotkov13** [comment] 2017-03-04 14:00
Will try on clean machine later. Now have to go.
I'll report what will work)

**Comment by korotkov13** [comment] 2017-03-09 21:18
made a clean install, and now tracks don't upload at all. track is uploading and when it should go to step to analys it says 

> An error occurred while processing your upload. Please try again in a few minutes.

in zendphp.log i got

```
2017-03-09T21:39:27+02:00 NOTICE (5): Undefined index: rabbitmq
2017-03-09T21:39:27+02:00 ERR (3): radio.site [MediaController.php:160 - postAction()] - Undefined index: rabbitmq
#0 [internal function]: exception_error_handler(8, 'Undefined index...', '/usr/share/airt...', 104, Array)
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Log.php(636): call_user_func('exception_error...', 8, 'Undefined index...', '/usr/share/airt...', 104, Array)
#2 /usr/share/airtime/php/airtime_mvc/application/models/RabbitMq.php(104): Zend_Log->errorHandler(8, 'Undefined index...', '/usr/share/airt...', 104, Array)
#3 /usr/share/airtime/php/airtime_mvc/application/services/MediaService.php(46): Application_Model_RabbitMq::SendMessageToAnalyzer('/srv/airtime/st...', '/srv/airtime/st...', 'Blockhead - A N...', 'http://radio.or...', '00CJROWLAQ32C4K...', 'file', '')
#4 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(160): Application_Service_MediaService::importFileToLibrary('http://radio.or...', '/tmp/phpHH7wqd', 'Blockhead - A N...', 1, false)
#5 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(99): CcFiles::createAndImport(Array, '/tmp/phpHH7wqd', 'Blockhead - A N...')
#6 /usr/share/airtime/php/airtime_mvc/application/modules/rest/controllers/MediaController.php(144): CcFiles::createFromUpload(Array)
#7 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Rest_MediaController->postAction()
#8 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#9 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#13 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#14 {main}
2017-03-09T21:39:27+02:00 INFO (6): radio.site Moving file /tmp/phpD25IWW to /srv/airtime/stor/organize/Art Bleek - Los Bangeles.mp3
```
and one more thing. I also looked rabbitmq logs, and there is no errors.

I also had an issue with rabbitmq every time while installed (air)libretime.
I do not know the reason why the installation had  an error every time on step with rabbitmq. it showed failed instead ok.
I found the solution installing erlang-solutions_1.0 and making file /etc/rabbitmq/rabbitmq-env.conf
with text `NODENAME=rabbit@localhost`
after that rabbitmq starting work.

**Comment by Robbt** [comment] 2017-03-09 21:32
This sounds like the issue I just fixed with the install script. 
Make sure you have the file 
rabbitmq-analyzer.ini in /etc/airtime
with the following contents
[rabbitmq]
host = 127.0.0.1
port = 5672
user = airtime
password = airtime
vhost = /airtime

Then restart the airtime_analyzer service and it will hopefully resolve this issue. Once my latest commit is merged this should no longer be a problem on a fresh install.

**Comment by korotkov13** [comment] 2017-03-09 21:39
thanks @Robbt  It uploads now without issues.
I will test it tomorrow with "big upload" and report.

**Comment by hairmare** [comment] 2017-03-10 08:45
@korotkov13 That you needed to install RabbitMQ manually is weird. It should have been installed automatically with the systems hostname in `NODENAME`. The one from erlang-solutions is fine as well but there might be some issues with the api_client connecting to it (I'd need to retest).

Are you using media-monitor? If so, you should switch to airtime_analyzer. The analyzer is more robust and has workarounds for silan. It does not (yet) support watched directories, but those are missing from the UI as well.

**Comment by korotkov13** [comment] 2017-03-10 08:49
@hairmare It's weird. On my home virtual machine I don't have issues with RabbitMQ, but on working/test VPS i have. Maybe there is another solution with erlang-solutions?
with this [one](https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb) installation completes well and RabbitMQ installing without issues.

**Comment by hairmare** [comment] 2017-03-10 09:07
That look like a pretty old version. The version provided by Ubuntu is `rabbitmq-server 3.2.4-1` (taken from `dpkg-query -l 'rabbitmq*'`).

What OS is your VPS on? I have `jessie/sid` in `/etc/debian_version` and my `/etc/os-release` contains the following:

```bash
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Could you post yours from the VPS?

**Comment by korotkov13** [comment] 2017-03-10 09:10
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by korotkov13** [comment] 2017-03-10 09:17
I tried to install new erlang version thru official repo and after installing RabbitMQ i have failed to start service.
in logs i have in startup_err
`
Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
`
in startup_log
`{error_logger,{{2017,3,10},{12,13,20}},"Protocol: ~tp: register/listen error: ~tp~n",["inet_tcp",econnrefused]}
{error_logger,{{2017,3,10},{12,13,20}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,320}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.90>,<0.17.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,798}],[]]}
{error_logger,{{2017,3,10},{12,13,20}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[[rabbitmqprelaunch12845,shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2017,3,10},{12,13,20}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2017,3,10},{12,13,20}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2017,3,10},{12,13,20}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}
`

**Comment by korotkov13** [comment] 2017-03-10 09:23
with that old version installing ok

**Comment by hairmare** [comment] 2017-03-10 11:11
Ah yes. The no IPv6 RabbitMQ issue, I've seen that one before.

Modern RabbitMQ assumes you have IPv6 in the default config and erlang beam (i think) breaks badly if there is no v6 stack available. I think you should also be able to get that running by deactivating the ipv6 part in the config as per [the docs](https://www.rabbitmq.com/networking.html).

**Comment by korotkov13** [comment] 2017-03-10 12:14
Reporting!
I made a clean install and right now uploaded 10 of 20Gb music without issues.
Looks like it works!

**Closed** 2017-03-10 12:42 UTC
Labels: bug, php
