### ISSUE TITLE
Tracks playing over each other

### ISSUE THREAD

**Issue by petegriggs** [LibreTime/libretime#381] opened 2017-12-14 13:05 UTC
Hello,

Got a bug where the tracks overlap and keep looping in both smart blocks and playlists. The only way to stop this is to delete the tracks from the show and then reading. Nothing I can see in the logs? Anyone got any ideas?

**Comment by Robbt** [comment] 2017-12-14 13:39
We'd need more details from the bugs or specifics on how you created a scenario where they overlapped. I haven't seen anything like this before.

**Comment by petegriggs** [comment] 2017-12-14 13:57
So, We had a scheduled show and put a smart block in to play 1 Jingle. This then keeped randomly repeating. In other instances scheduled show with mix tracks. It was playing one track over another. The only way to fix is to restart or delete all tracks from the show.


Is there a way of enabling enhanced logging?

________________________________

**Comment by Robbt** [comment] 2017-12-14 19:09
Check out /var/log/airtime/pypo/pypo.log and /var/log/airtime/pypo-liquidsoap/ls_script.log - see if anything is in there.
Also share what distro you are using and or any more details. Does this happen everytime or was it a one time occurence ?

**Comment by Robbt** [comment] 2017-12-15 04:33
So this also sounds like you were scheduling on the fly, vs ahead of time. Is that correct ?

LibreTime doesn't always behave correctly when you add tracks to a show that is already in progress. Whereas if you schedule everything ahead of time it usually works. This has to do with the airtime-playout interaction with liquidsoap. If you can find any errors in the logs we might be able to figure it out.

**Comment by petegriggs** [comment] 2017-12-15 09:44
Hey,


No this has happened a couple of times and the schedules were built ahead of time. I'll take a look in the Logs.


Cheers

Pete


________________________________

**Comment by Robbt** [comment] 2018-12-04 02:20
So I'm going to close this because we don't have enough information to troubleshoot it and no way of reproducing it. There very well might be a problem here. If you are still having this issue @petegriggs feel free to add a comment with the various logs and we can re-open it.

**Closed by Robbt** 2018-12-04 02:20 UTC
Labels: liquidsoap, smart blocks
