### ISSUE TITLE
Can not connect to the streaming server. Problem with Liquidsoap

### ISSUE THREAD

**Issue by GFMradio** [libretime/libretime#1606] opened 2022-02-16 02:45 UTC
OS : Ubuntu 18.04.6
PC : Z440 workstation

By January, LibreTime had been installed and used on three other Z440 workstations.
These three LibreTime work well so far.

However, installing a new LibreTime from last week will cause errors such as images.

< Can not connect to the streaming server
Problem with Liquidsoap...>

Is there any way to solve this?

![libretime](https://user-images.githubusercontent.com/99778577/154186476-33fab2cb-143a-480b-a601-820da95a35e5.png)

**Comment by GFMradio** [comment] 2022-02-16 04:13
I solve it.
https://discourse.libretime.org/t/libretime-not-on-air-getting-information-from-server/1038/6

**Comment by paddatrapper** [comment] 2022-02-16 08:16
Looks like liquidsoap is having issues:

```
2022/02/16 08:13:49 [lang:3] timeout --signal=KILL 45 libretime-playout-notify stream '1' '1644999089.78' --error='could not write data to host: Broken pipe in write()' &                                        
2022/02/16 08:13:49 [LibreTime!:3] Closing connection...                                                                                                                                                          
2022/02/16 08:13:49 [LibreTime!:3] Will try to reconnect in 5.00 seconds
``

**Comment by paddatrapper** [comment] 2022-02-20 19:15
Looks like liquidsoap can connect to Icecast and continues working until it needs to stream a file/media. Then it is unable to stream successfully and eventually resets the stream to try again. This loops indefinitely.

**Comment by jooola** [comment] 2022-02-22 09:47
@paddatrapper You are described an issue that have mostly nothing to do with initial one.

I did reproduce this, and I could workaround it by installing a recent version of liquidsoap (1.4.4).

I wonder if the ppa change did affect this ? Has this been working on focal already ?

I did some research on the liquidsoap side:
- https://github.com/savonet/liquidsoap/issues/1541
- https://github.com/savonet/liquidsoap/issues/1115

**Comment by paddatrapper** [comment] 2022-02-22 11:54
@jooola the result of the issue is the same as presented above - you get an `Unable to connect to the streaming server` error

I usually test PRs on focal, so it was working previously...

**Comment by jooola** [comment] 2022-03-16 13:48
Xenial ? Aren't you referring to focal or even bionic ??

**Comment by jooola** [comment] 2022-03-18 10:52
@paddatrapper Could you report here where you are facing an issue ? I've been digging in your latest changes on salsa, and it seems the problem is ocaml-ogg ? Or are there other packages that are failing ? Should I step in and try to search for fixes ?

**Comment by paddatrapper** [comment] 2022-03-18 11:10
It was a local configuration issue which I have managed to fix. Busy building now

**Comment by paddatrapper** [comment] 2022-03-18 12:41
This issue doesn't seem to be a liquidsoap version, or at least there is a change that we have made somewhere that has caused us to run into an upstream bug. Running the same liquidsoap version and upgrading from alpha.10 to master caused the issue to appear on 18.04. Running alpha.10 worked without a problem

**Comment by jooola** [comment] 2022-03-18 13:41
Wondering if we know if the problematic libretime-playout-notify call is failing, and called again on failure ?

**Comment by paddatrapper** [comment] 2022-03-21 07:55
It doesn't appear to be failing, at least the exit code when called manually is 0

**Comment by paddatrapper** [comment] 2022-03-21 07:59
Hmmm, interesting. Testing this morning on 18.04 and I still get the `Can not connect to the streaming server. Problem with Liquidsoap...`, however, playout is still happening correctly. Which is different behaviour from 20.04. This is less of a problem, as the playout still works, just doesn't seem to report back properly (maybe missing a notify call somewhere in the script for liquidsoap 1.1.1)

**Comment by paddatrapper** [comment] 2022-03-28 13:51
Tested an upgrade on Ubuntu 18.04 from alpha.10 to current main (with #1707 merged) and playout is working fine. However it does seem something in the feedback loop is broken - the stream status and the on-air button indicate issues. There aren't any in the playout system though.

**Comment by jooola** [comment] 2022-03-28 16:04
I'll investigate tomorrow, I won't have time for today.

**Comment by jooola** [comment] 2022-03-29 10:26
Here is the problematic error message:
```
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]: Traceback (most recent call last):
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/bin/libretime-playout-notify", line 33, in <module>
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     sys.exit(load_entry_point('libretime-playout==1.0', 'console_scripts', 'libretime-playout-notify')())
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     return self.main(*args, **kwargs)
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1034, in main
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     _verify_python_env()
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 100, in _verify_python_env
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     raise RuntimeError("\n\n".join(extra))
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]: RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]: This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     export LC_ALL=C.UTF-8
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     export LANG=C.UTF-8
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]: Traceback (most recent call last):
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/bin/libretime-playout-notify", line 33, in <module>
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     sys.exit(load_entry_point('libretime-playout==1.0', 'console_scripts', 'libretime-playout-notify')())
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     return self.main(*args, **kwargs)
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1034, in main
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     _verify_python_env()
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:   File "/usr/local/lib/python3.6/dist-packages/click/_unicodefun.py", line 100, in _verify_python_env
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     raise RuntimeError("\n\n".join(extra))
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]: RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]: This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     export LC_ALL=C.UTF-8
Mar 29 10:22:01 vagrant libretime-liquidsoap[10038]:     export LANG=C.UTF-8
```

According to https://click.palletsprojects.com/en/8.1.x/unicode-support/ we need to export some of these locales info. This is only required for python 3.6, python3.7 works fine.

**Closed** 2022-03-29 11:04 UTC
Labels: is: bug
