### ISSUE TITLE
Bulk type changes

### ISSUE THREAD

**Issue by maxtimbo** [libretime/libretime#1834] opened 2022-05-05 04:12 UTC
Currently, I would have to run through each individual track and change the type for each one. If I already have a library that has been imported, changing each individual file is simply too many clicks. 

To be fair, I could create the track types ahead of time and import them as a particular type.

**Describe the solution you'd like**
Click "select all" -> Edit -> change 'Track Type' -> done.

**Comment by maxtimbo** [comment] 2022-05-05 14:49
To add to this, Bulk File Changes would be nice as well. For instance, I imported some music last night which had incorrect metadata attached. So I needed to change the Artist name for an album's worth of music. I think MusicBrainz Picard has the right idea, where you can select a bunch of tracks, what is the same is shown, what is different is greyed, but still editable.

**Comment by paddatrapper** [comment] 2022-05-05 15:06
Duplicate of #701 

It would be useful

**Closed by paddatrapper** 2022-05-05 15:06 UTC
Labels: is: feature-request
