### ISSUE TITLE
Problem: Airtime Analyzer doesn't verify track length upon import when id3 doesn't match reality

### ISSUE THREAD

**Issue by Robbt** [libretime/libretime#537] opened 2018-10-06 21:52 UTC
If an incomplete file is uploaded to LibreTime ie a partially downloaded mp3 file, Airtime Analyzer will read the track length from the id3 length field with mutagen in https://github.com/LibreTime/libretime/blob/45c81ffec41db2d7c16a840f350fbc086a2d9b7e/python_apps/airtime_analyzer/airtime_analyzer/metadata_analyzer.py#L67

So I'm not sure what the best way to fix this would be but this [site](https://askubuntu.com/questions/248811/how-can-i-fix-incorrect-mp3-duration) suggested `mid3v2 --delete-frames=TLEN filename.mp3` 

I'll test it out and see if deleting the ID3 length means mutagen will correctly import the true length of a incomplete file. 

Another option would be re-encoding everything via ffmpeg to a mp3 upon import as @ned-kelly has suggested doing with podcasts. If you re-encode a partial mp3 it should provide a new correct length etc.

**Comment by JohnnyC1951** [comment] 2018-10-08 12:14
I used to recode everything using sox (which has fmpeg underneath) which does fix this, the track plays at double speed, and some other random length issues, at the expense of some recoding loss.

**Comment by hairmare** [comment] 2018-10-08 22:01
Do we have any shareable files that exhibit this behaviour (as in creative-commons audio)? This might be a reason to update our "fronzen since ages" version of mutagen since it might have been fixed upstream.

https://github.com/LibreTime/libretime/blob/45c81ffec41db2d7c16a840f350fbc086a2d9b7e/python_apps/airtime_analyzer/setup.py#L31

BTW... Press <kbd>Y</kbd> on any GitHub page once you highlighted a line to get a link that get's rendered inline :)

**Comment by JohnnyC1951** [comment] 2018-11-02 23:30
Is it half the expected length?

**Comment by Robbt** [comment] 2018-11-03 14:51
Yeah, the issue I was having was with "bad files" - files that were only partially complete. The question is whether we should reject these files or accept them and modify the length to be their actual length. 

I think my ideal situation would be to import them and flag them as potentially problematic (but we don't have this in the UI currently). Importing them and addressing their true length could work and in theory is something that Silan is supposed to address. Having them imported and playing for an length of time out of sync with what LibreTIme expects is basically asking for weird issues one way or the other.

**Comment by Robbt** [comment] 2019-01-18 18:01
I'm making this a release-blocker because it can result in dead air which is a bug no in terms of the broadcast world and it should be avoidable with some improvements.

**Comment by Robbt** [comment] 2019-03-04 18:47
I did some investigation into this and there wasn't an obvious solution aside from trying to strip the TLEN from all of the metadata to try to force mutagen to determine the length based upon filesize etc.

I'm not sure that this won't also introduce other potential side-effects. I looked into our airtime_analyzer code and it should in theory be checking whether a file is playable with liquidsoap. In addition liquidsoap doesn't have a method for absolute determination of the length ahead of time. 

Here is some advice from Romain on the liquidsoap mailing list

> request.resolve() is the operastor you are looking for to test if liquidsoap will accept a file. It should return true when liquidsap will accept the file. (you can also keep the request and use it already resolved in request.dynamic)

> As it comes to song length, historically liquidsoap doesn't try to get an exact length. There are compelling reasons for that, most importantly because some formats are hard to predict and/or expensive to compute the length. This is really mostly intended for mp3, which sucks and requires a full decode to have a realistic estimate of  a song's length.

> Liquidsoap gets an estimate of the remaining time. which you can get while the source is playing by calling source.remaining. The closer you get to the end of the track the more accurate it will become. -1 means no known estimate.

> Another great tool from the ffmpeg suite to deal with song length is ffprobe. You can have it scan a file and return a JSON payload with a lot of information, including the song's total duration.

> Finally, if you really need a very precise duration estimate within liquidsoap, one route to go down could be to first entirely decode the file before sending it to the streaming engine. This can be done with a custom protocol since I believe 1.3.3. The `ffmpeg2wav` protocol does just that and you should be able to use simply by prefixing your request with it, e.g.:
  ffmpeg2wav:/path/to/file
The resulting wav file should be decodable by liquidsoap and, if length still isn't accurate, that's a format we could definitely work on making precise.

> Hope this helps,
Romain

I'm also going to remove release blocker because this should be a rare event, even though it is a bad one and it is a result of bad files vs. something obliquely wrong with libretime.

**Comment by kmahelona** [comment] 2020-03-07 23:35
I have this problem though the cause is different. We've exported a bunch of variable bitrate audio from something called OTS AV. So we have a bunch of files that have metadata `TLEN` saying the song is some ridiculous length like 25 minutes but it's actually much small, <10mins. I tried analysing these files with `ffprobe` to rewrite the `TLEN` but `ffprobe` doesn't even give you the right answer. The solution was apparently to do something like `ffmpeg -i input.mp3 -c:a copy -o out.mp3` which fixed the file to have the correct `TLEN`.

It would be a robust/nice feature to update incorrect `TLEN` and even `BPM` and other metadata that is derived from the audio file. But we'll probably just write some scripts to analyse all our files to help us clean up our library (it's got more than 10 years of history!).

**Comment by Robbt** [comment] 2020-03-17 14:08
Yeah, I could imagine that we could really update our import process to do a lot of things such as correcting TLEN - BPM and even detecting different songs in a mix (by using an external database). 
We could also add tips and tricks for cleaning your audio files to our documentation. Having correct metadata at least is very important.

**Comment by jooola** [comment] 2022-09-20 18:17
Since the move from silan to ffmpeg, we started to compute the length of the analyzed files using ffprobe.

If the length from the metadata differ from the one computed by ffprobe, we log a warning from the analyzer.

https://github.com/libretime/libretime/blob/5e2ec8956e0e02e3ccc0ac3709ea05f587f2c0ef/analyzer/libretime_analyzer/pipeline/analyze_cuepoint.py#L19-L32

Closing as resolved.

**Closed by jooola** 2022-09-20 18:17 UTC
Labels: is: bug, python, analyzer
